SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-iletisim','Etkili İletişim ve Toplumsal Katılım','Etkili İletişim ve Toplumsal Katılım','Etkili İletişim ve Toplumsal Katılım konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-birlikte' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-esitlik','Fırsat Eşitliği ve Millî Dayanışma','Fırsat Eşitliği ve Millî Dayanışma','Fırsat Eşitliği ve Millî Dayanışma konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-birlikte' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-nufus','Nüfus, Göç ve Yerleşme','Nüfus, Göç ve Yerleşme','Nüfus, Göç ve Yerleşme konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-dunya' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-cevre','Çevre Sorunları ve Coğrafi Etkileşim','Çevre Sorunları ve Coğrafi Etkileşim','Çevre Sorunları ve Coğrafi Etkileşim konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-dunya' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-osmanli','Osmanlı''dan Ortak Mirasa','Osmanlı''dan Ortak Mirasa','Osmanlı''dan Ortak Mirasa konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-miras' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-kultur','Kültürel Etkileşim ve Mirasın Korunması','Kültürel Etkileşim ve Mirasın Korunması','Kültürel Etkileşim ve Mirasın Korunması konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-miras' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-demokrasi','Demokratikleşme ve Katılım','Demokratikleşme ve Katılım','Demokratikleşme ve Katılım konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-demokrasi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-hak','Hak, Özgürlük ve Hukuk','Hak, Özgürlük ve Hukuk','Hak, Özgürlük ve Hukuk konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-demokrasi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-ekonomi','Üretim, Emek ve Ekonomik Sistem','Üretim, Emek ve Ekonomik Sistem','Üretim, Emek ve Ekonomik Sistem konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-ekonomi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-finans','Finansal Okuryazarlık ve Bütçe','Finansal Okuryazarlık ve Bütçe','Finansal Okuryazarlık ve Bütçe konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-ekonomi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-bilim','Bilimsel Gelişmeler ve Toplum','Bilimsel Gelişmeler ve Toplum','Bilimsel Gelişmeler ve Toplum konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-teknoloji' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-dijital','Dijital Toplum, Medya ve Etik','Dijital Toplum, Medya ve Etik','Dijital Toplum, Medya ve Etik konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-teknoloji' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-1','coktan_secmeli','Etkili iletişim toplumsal katılımı destekler mi?','["Evet","Hayır","Sadece bireysel","İletişim gerekmez"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-2','coktan_secmeli','Aktif dinleme çatışma çözümüne katkı sağlar mı?','["Hayır","Söz kesmek gerekir","Evet","Dinleme zararlıdır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-3','coktan_secmeli','Fırsat eşitliği herkesin aynı ihtiyaca sahip olduğu anlamına mı gelir?','["Hayır","Evet","Her zaman","Eşitlik yoktur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-4','coktan_secmeli','Millî meselelerde dayanışma toplumsal birlikle ilişkili midir?','["Hayır","Sadece bireysel","Evet","Birlik önemsiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-5','coktan_secmeli','Göç nüfus dağılışını etkileyebilir mi?','["Evet","Hayır","Sadece iklim","Nüfus sabittir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-6','coktan_secmeli','Kentleşme ekonomik ve sosyal nedenlerle artabilir mi?','["Hayır","Sadece hava durumu","Evet","Kentleşme değişmez"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-7','coktan_secmeli','İnsan faaliyetleri çevre sorunlarını artırabilir mi?','["Evet","Hayır","Sadece doğal olaylar","İnsan etkisi yok"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-8','coktan_secmeli','Sürdürülebilir şehir planlaması çevresel etkiyi azaltabilir mi?','["Hayır","Sadece maliyet artırır","Evet","Çevreyle ilgisiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-9','coktan_secmeli','Tarihî belgeler geçmiş toplumlar hakkında kanıt sunar mı?','["Evet","Hayır","Sadece süs","Tarih anlatmaz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-10','coktan_secmeli','Osmanlı mirası mimari ve kültürel ögelerde görülebilir mi?','["Hayır","Sadece siyasette","Evet","Miras yoktur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-11','coktan_secmeli','Kültürel etkileşim ticaret ve göçle artabilir mi?','["Evet","Hayır","Kültür değişmez","Sadece savaşla"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-12','coktan_secmeli','Mirası korumak gelecek kuşaklar için önemli midir?','["Hayır","Sadece turistler","Evet","Koruma gereksiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-13','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir?','["Evet","Hayır","Sadece oyun","Sadece ekonomi"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-14','coktan_secmeli','Sivil toplum katılımı destekleyebilir mi?','["Hayır","Sadece devlet","Evet","Katılım yoktur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-15','coktan_secmeli','Hukukun üstünlüğü herkesin hukuk kurallarına bağlı olmasını ifade eder mi?','["Evet","Hayır","Sadece vatandaşlar","Sadece yöneticiler"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-16','coktan_secmeli','Özgürlükler başkalarının haklarıyla dengelenmeli midir?','["Hayır","Sınırsızdır","Evet","Haklarla ilgisiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-17','coktan_secmeli','Emek üretim faktörlerinden biri midir?','["Evet","Hayır","Sadece tüketim","Sadece reklam"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-18','coktan_secmeli','Girişimcilik ekonomik faaliyeti etkileyebilir mi?','["Hayır","Sadece kamu","Evet","Ekonomiyle ilgisiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-19','coktan_secmeli','Bütçe gelir-gider planı mıdır?','["Evet","Hayır","Harita","Sadece vergi"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-20','coktan_secmeli','Tasarruf finansal hedefe ulaşmayı destekleyebilir mi?','["Hayır","Sadece harcama","Evet","Tasarruf zararlıdır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-21','coktan_secmeli','Bilimsel gelişmeler toplumsal yaşamı değiştirebilir mi?','["Evet","Hayır","Sadece laboratuvar","Toplumu etkilemez"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-22','coktan_secmeli','Bilim insanlarının katkıları farklı toplumlarda ortaya çıkabilir mi?','["Hayır","Tek toplum","Evet","Bilim kültürden bağımsızdır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-23','coktan_secmeli','Dijital medya okuryazarlığı yanlış bilgiyi ayırt etmeye yardım eder mi?','["Evet","Hayır","Her içerik doğrudur","Paylaşım sayısı yeter"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-24','coktan_secmeli','Çevrim içi etik gerçek hayattaki saygı kurallarıyla ilişkili midir?','["Hayır","İnternette kural yok","Evet","Sadece okulda"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-1','coktan_secmeli','Etkili iletişim toplumsal katılımı destekler mi? Benzer bir örneği düşün.','["Hayır","Evet","Sadece bireysel","İletişim gerekmez"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-2','coktan_secmeli','Aktif dinleme çatışma çözümüne katkı sağlar mı? Benzer bir örneği düşün.','["Hayır","Söz kesmek gerekir","Dinleme zararlıdır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-3','coktan_secmeli','Fırsat eşitliği herkesin aynı ihtiyaca sahip olduğu anlamına mı gelir? Benzer bir örneği düşün.','["Evet","Hayır","Her zaman","Eşitlik yoktur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-4','coktan_secmeli','Millî meselelerde dayanışma toplumsal birlikle ilişkili midir? Benzer bir örneği düşün.','["Hayır","Sadece bireysel","Birlik önemsiz","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-5','coktan_secmeli','Göç nüfus dağılışını etkileyebilir mi? Benzer bir örneği düşün.','["Hayır","Evet","Sadece iklim","Nüfus sabittir"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-6','coktan_secmeli','Kentleşme ekonomik ve sosyal nedenlerle artabilir mi? Benzer bir örneği düşün.','["Hayır","Sadece hava durumu","Kentleşme değişmez","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-7','coktan_secmeli','İnsan faaliyetleri çevre sorunlarını artırabilir mi? Benzer bir örneği düşün.','["Hayır","Evet","Sadece doğal olaylar","İnsan etkisi yok"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-8','coktan_secmeli','Sürdürülebilir şehir planlaması çevresel etkiyi azaltabilir mi? Benzer bir örneği düşün.','["Hayır","Sadece maliyet artırır","Çevreyle ilgisiz","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-9','coktan_secmeli','Tarihî belgeler geçmiş toplumlar hakkında kanıt sunar mı? Benzer bir örneği düşün.','["Hayır","Evet","Sadece süs","Tarih anlatmaz"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-10','coktan_secmeli','Osmanlı mirası mimari ve kültürel ögelerde görülebilir mi? Benzer bir örneği düşün.','["Hayır","Sadece siyasette","Miras yoktur","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-11','coktan_secmeli','Kültürel etkileşim ticaret ve göçle artabilir mi? Benzer bir örneği düşün.','["Hayır","Evet","Kültür değişmez","Sadece savaşla"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-12','coktan_secmeli','Mirası korumak gelecek kuşaklar için önemli midir? Benzer bir örneği düşün.','["Hayır","Sadece turistler","Koruma gereksiz","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-13','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir? Benzer bir örneği düşün.','["Hayır","Evet","Sadece oyun","Sadece ekonomi"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-14','coktan_secmeli','Sivil toplum katılımı destekleyebilir mi? Benzer bir örneği düşün.','["Hayır","Sadece devlet","Katılım yoktur","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-15','coktan_secmeli','Hukukun üstünlüğü herkesin hukuk kurallarına bağlı olmasını ifade eder mi? Benzer bir örneği düşün.','["Hayır","Evet","Sadece vatandaşlar","Sadece yöneticiler"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-16','coktan_secmeli','Özgürlükler başkalarının haklarıyla dengelenmeli midir? Benzer bir örneği düşün.','["Hayır","Sınırsızdır","Haklarla ilgisiz","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-17','coktan_secmeli','Emek üretim faktörlerinden biri midir? Benzer bir örneği düşün.','["Hayır","Evet","Sadece tüketim","Sadece reklam"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-18','coktan_secmeli','Girişimcilik ekonomik faaliyeti etkileyebilir mi? Benzer bir örneği düşün.','["Hayır","Sadece kamu","Ekonomiyle ilgisiz","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-19','coktan_secmeli','Bütçe gelir-gider planı mıdır? Benzer bir örneği düşün.','["Hayır","Evet","Harita","Sadece vergi"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-20','coktan_secmeli','Tasarruf finansal hedefe ulaşmayı destekleyebilir mi? Benzer bir örneği düşün.','["Hayır","Sadece harcama","Tasarruf zararlıdır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-21','coktan_secmeli','Bilimsel gelişmeler toplumsal yaşamı değiştirebilir mi? Benzer bir örneği düşün.','["Hayır","Evet","Sadece laboratuvar","Toplumu etkilemez"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,121,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-22','coktan_secmeli','Bilim insanlarının katkıları farklı toplumlarda ortaya çıkabilir mi? Benzer bir örneği düşün.','["Hayır","Tek toplum","Bilim kültürden bağımsızdır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,122,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-23','coktan_secmeli','Dijital medya okuryazarlığı yanlış bilgiyi ayırt etmeye yardım eder mi? Benzer bir örneği düşün.','["Hayır","Evet","Her içerik doğrudur","Paylaşım sayısı yeter"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,123,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-2-24','coktan_secmeli','Çevrim içi etik gerçek hayattaki saygı kurallarıyla ilişkili midir? Benzer bir örneği düşün.','["Hayır","İnternette kural yok","Sadece okulda","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,124,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-1','coktan_secmeli','Etkili iletişim toplumsal katılımı destekler mi? Yeni bir bağlama uygula.','["Hayır","Sadece bireysel","Evet","İletişim gerekmez"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-2','coktan_secmeli','Aktif dinleme çatışma çözümüne katkı sağlar mı? Yeni bir bağlama uygula.','["Evet","Hayır","Söz kesmek gerekir","Dinleme zararlıdır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-3','coktan_secmeli','Fırsat eşitliği herkesin aynı ihtiyaca sahip olduğu anlamına mı gelir? Yeni bir bağlama uygula.','["Evet","Her zaman","Hayır","Eşitlik yoktur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-4','coktan_secmeli','Millî meselelerde dayanışma toplumsal birlikle ilişkili midir? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece bireysel","Birlik önemsiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-5','coktan_secmeli','Göç nüfus dağılışını etkileyebilir mi? Yeni bir bağlama uygula.','["Hayır","Sadece iklim","Evet","Nüfus sabittir"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-6','coktan_secmeli','Kentleşme ekonomik ve sosyal nedenlerle artabilir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece hava durumu","Kentleşme değişmez"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-7','coktan_secmeli','İnsan faaliyetleri çevre sorunlarını artırabilir mi? Yeni bir bağlama uygula.','["Hayır","Sadece doğal olaylar","Evet","İnsan etkisi yok"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-8','coktan_secmeli','Sürdürülebilir şehir planlaması çevresel etkiyi azaltabilir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece maliyet artırır","Çevreyle ilgisiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-9','coktan_secmeli','Tarihî belgeler geçmiş toplumlar hakkında kanıt sunar mı? Yeni bir bağlama uygula.','["Hayır","Sadece süs","Evet","Tarih anlatmaz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-10','coktan_secmeli','Osmanlı mirası mimari ve kültürel ögelerde görülebilir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece siyasette","Miras yoktur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-11','coktan_secmeli','Kültürel etkileşim ticaret ve göçle artabilir mi? Yeni bir bağlama uygula.','["Hayır","Kültür değişmez","Evet","Sadece savaşla"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-12','coktan_secmeli','Mirası korumak gelecek kuşaklar için önemli midir? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece turistler","Koruma gereksiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-13','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir? Yeni bir bağlama uygula.','["Hayır","Sadece oyun","Evet","Sadece ekonomi"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-14','coktan_secmeli','Sivil toplum katılımı destekleyebilir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece devlet","Katılım yoktur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-15','coktan_secmeli','Hukukun üstünlüğü herkesin hukuk kurallarına bağlı olmasını ifade eder mi? Yeni bir bağlama uygula.','["Hayır","Sadece vatandaşlar","Evet","Sadece yöneticiler"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-16','coktan_secmeli','Özgürlükler başkalarının haklarıyla dengelenmeli midir? Yeni bir bağlama uygula.','["Evet","Hayır","Sınırsızdır","Haklarla ilgisiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-17','coktan_secmeli','Emek üretim faktörlerinden biri midir? Yeni bir bağlama uygula.','["Hayır","Sadece tüketim","Evet","Sadece reklam"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-18','coktan_secmeli','Girişimcilik ekonomik faaliyeti etkileyebilir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece kamu","Ekonomiyle ilgisiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-19','coktan_secmeli','Bütçe gelir-gider planı mıdır? Yeni bir bağlama uygula.','["Hayır","Harita","Evet","Sadece vergi"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-20','coktan_secmeli','Tasarruf finansal hedefe ulaşmayı destekleyebilir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece harcama","Tasarruf zararlıdır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-21','coktan_secmeli','Bilimsel gelişmeler toplumsal yaşamı değiştirebilir mi? Yeni bir bağlama uygula.','["Hayır","Sadece laboratuvar","Evet","Toplumu etkilemez"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,221,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-22','coktan_secmeli','Bilim insanlarının katkıları farklı toplumlarda ortaya çıkabilir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Tek toplum","Bilim kültürden bağımsızdır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,222,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-23','coktan_secmeli','Dijital medya okuryazarlığı yanlış bilgiyi ayırt etmeye yardım eder mi? Yeni bir bağlama uygula.','["Hayır","Her içerik doğrudur","Evet","Paylaşım sayısı yeter"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,223,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-3-24','coktan_secmeli','Çevrim içi etik gerçek hayattaki saygı kurallarıyla ilişkili midir? Yeni bir bağlama uygula.','["Evet","Hayır","İnternette kural yok","Sadece okulda"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,224,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-1','coktan_secmeli','Etkili iletişim toplumsal katılımı destekler mi? En uygun açıklamayı seç.','["Hayır","Sadece bireysel","İletişim gerekmez","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,301,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-2','coktan_secmeli','Aktif dinleme çatışma çözümüne katkı sağlar mı? En uygun açıklamayı seç.','["Hayır","Evet","Söz kesmek gerekir","Dinleme zararlıdır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,302,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-3','coktan_secmeli','Fırsat eşitliği herkesin aynı ihtiyaca sahip olduğu anlamına mı gelir? En uygun açıklamayı seç.','["Evet","Her zaman","Eşitlik yoktur","Hayır"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,303,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-4','coktan_secmeli','Millî meselelerde dayanışma toplumsal birlikle ilişkili midir? En uygun açıklamayı seç.','["Hayır","Evet","Sadece bireysel","Birlik önemsiz"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,304,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-5','coktan_secmeli','Göç nüfus dağılışını etkileyebilir mi? En uygun açıklamayı seç.','["Hayır","Sadece iklim","Nüfus sabittir","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,305,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-6','coktan_secmeli','Kentleşme ekonomik ve sosyal nedenlerle artabilir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece hava durumu","Kentleşme değişmez"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,306,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-7','coktan_secmeli','İnsan faaliyetleri çevre sorunlarını artırabilir mi? En uygun açıklamayı seç.','["Hayır","Sadece doğal olaylar","İnsan etkisi yok","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,307,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-8','coktan_secmeli','Sürdürülebilir şehir planlaması çevresel etkiyi azaltabilir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece maliyet artırır","Çevreyle ilgisiz"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,308,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-9','coktan_secmeli','Tarihî belgeler geçmiş toplumlar hakkında kanıt sunar mı? En uygun açıklamayı seç.','["Hayır","Sadece süs","Tarih anlatmaz","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,309,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-10','coktan_secmeli','Osmanlı mirası mimari ve kültürel ögelerde görülebilir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece siyasette","Miras yoktur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,310,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-11','coktan_secmeli','Kültürel etkileşim ticaret ve göçle artabilir mi? En uygun açıklamayı seç.','["Hayır","Kültür değişmez","Sadece savaşla","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,311,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-12','coktan_secmeli','Mirası korumak gelecek kuşaklar için önemli midir? En uygun açıklamayı seç.','["Hayır","Evet","Sadece turistler","Koruma gereksiz"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,312,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-13','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir? En uygun açıklamayı seç.','["Hayır","Sadece oyun","Sadece ekonomi","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,313,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-14','coktan_secmeli','Sivil toplum katılımı destekleyebilir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece devlet","Katılım yoktur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,314,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-15','coktan_secmeli','Hukukun üstünlüğü herkesin hukuk kurallarına bağlı olmasını ifade eder mi? En uygun açıklamayı seç.','["Hayır","Sadece vatandaşlar","Sadece yöneticiler","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,315,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-16','coktan_secmeli','Özgürlükler başkalarının haklarıyla dengelenmeli midir? En uygun açıklamayı seç.','["Hayır","Evet","Sınırsızdır","Haklarla ilgisiz"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,316,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-17','coktan_secmeli','Emek üretim faktörlerinden biri midir? En uygun açıklamayı seç.','["Hayır","Sadece tüketim","Sadece reklam","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,317,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-18','coktan_secmeli','Girişimcilik ekonomik faaliyeti etkileyebilir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece kamu","Ekonomiyle ilgisiz"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,318,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-19','coktan_secmeli','Bütçe gelir-gider planı mıdır? En uygun açıklamayı seç.','["Hayır","Harita","Sadece vergi","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,319,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-20','coktan_secmeli','Tasarruf finansal hedefe ulaşmayı destekleyebilir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece harcama","Tasarruf zararlıdır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,320,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-21','coktan_secmeli','Bilimsel gelişmeler toplumsal yaşamı değiştirebilir mi? En uygun açıklamayı seç.','["Hayır","Sadece laboratuvar","Toplumu etkilemez","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,321,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-22','coktan_secmeli','Bilim insanlarının katkıları farklı toplumlarda ortaya çıkabilir mi? En uygun açıklamayı seç.','["Hayır","Evet","Tek toplum","Bilim kültürden bağımsızdır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,322,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-23','coktan_secmeli','Dijital medya okuryazarlığı yanlış bilgiyi ayırt etmeye yardım eder mi? En uygun açıklamayı seç.','["Hayır","Her içerik doğrudur","Paylaşım sayısı yeter","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,323,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-4-24','coktan_secmeli','Çevrim içi etik gerçek hayattaki saygı kurallarıyla ilişkili midir? En uygun açıklamayı seç.','["Hayır","Evet","İnternette kural yok","Sadece okulda"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,324,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

