SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-gs-tasarim','Tasarım, Kompozisyon ve Görsel Dil','Tasarım, Kompozisyon ve Görsel Dil','Tasarım, Kompozisyon ve Görsel Dil becerilerini uygular.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='gs7-uretme' WHERE d.kod='gorsel' OR d.ad='Görsel Sanatlar' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-gs-miras','Sanat ve Kültürel Miras','Sanat ve Kültürel Miras','Sanat ve Kültürel Miras becerilerini uygular.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='gs7-miras' WHERE d.kod='gorsel' OR d.ad='Görsel Sanatlar' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-gs-elestiri','Sanat Eleştirisi ve Estetik','Sanat Eleştirisi ve Estetik','Sanat Eleştirisi ve Estetik becerilerini uygular.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='gs7-estetik' WHERE d.kod='gorsel' OR d.ad='Görsel Sanatlar' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-muz-ses','Dinleme ve Söyleme','Dinleme ve Söyleme','Dinleme ve Söyleme becerilerini uygular.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='muz7-dinleme' WHERE d.kod='muzik' OR d.ad='Müzik' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-muz-ritim','Ritim ve Müzik Dili','Ritim ve Müzik Dili','Ritim ve Müzik Dili becerilerini uygular.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='muz7-ritim' WHERE d.kod='muzik' OR d.ad='Müzik' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-muz-uret','Müziksel Yaratıcılık','Müziksel Yaratıcılık','Müziksel Yaratıcılık becerilerini uygular.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='muz7-yaratici' WHERE d.kod='muzik' OR d.ad='Müzik' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-muz-kultur','Müzik Kültürü','Müzik Kültürü','Müzik Kültürü becerilerini uygular.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='muz7-kultur' WHERE d.kod='muzik' OR d.ad='Müzik' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-be-hareket','Hareket Yetkinliği','Hareket Yetkinliği','Hareket Yetkinliği becerilerini uygular.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='bes7-hareket' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-be-zindelik','Fiziksel Uygunluk','Fiziksel Uygunluk','Fiziksel Uygunluk becerilerini uygular.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='bes7-zindelik' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-be-takim','Takım Stratejileri ve Adil Oyun','Takım Stratejileri ve Adil Oyun','Takım Stratejileri ve Adil Oyun becerilerini uygular.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='bes7-takim' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-be-kultur','Spor Kültürü','Spor Kültürü','Spor Kültürü becerilerini uygular.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='bes7-kultur' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-reh-kendim','Öz Farkındalık','Öz Farkındalık','Öz Farkındalık becerilerini uygular.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='reh7-kendim' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-reh-hedef','Akademik Hedef ve Öz Düzenleme','Akademik Hedef ve Öz Düzenleme','Akademik Hedef ve Öz Düzenleme becerilerini uygular.','',130,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='reh7-hedef' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-reh-iliski','İletişim ve Akran İlişkileri','İletişim ve Akran İlişkileri','İletişim ve Akran İlişkileri becerilerini uygular.','',140,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='reh7-iliski' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-reh-guven','Güvenli ve Sağlıklı Yaşam','Güvenli ve Sağlıklı Yaşam','Güvenli ve Sağlıklı Yaşam becerilerini uygular.','',150,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='reh7-guven' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'o7-reh-kariyer','Kariyer Farkındalığı','Kariyer Farkındalığı','Kariyer Farkındalığı becerilerini uygular.','',160,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='reh7-kariyer' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-1','coktan_secmeli','Vurgu ve denge görsel tasarım ilkeleri midir?','["Evet","Hayır","Sadece müzik","Sadece matematik"]',0,'Beceri bağlama göre değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-2','coktan_secmeli','Perspektif derinlik oluşturmada kullanılabilir mi?','["Hayır","Sadece renk","Evet","Sadece doku"]',2,'Beceri bağlama göre değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-3','coktan_secmeli','Sanat eserleri kültürel kimlik hakkında bilgi verebilir mi?','["Evet","Hayır","Sadece fiyat","Kültürle ilgisiz"]',0,'Beceri bağlama göre değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-4','coktan_secmeli','Miras eserleri korunmalı mıdır?','["Hayır","Sadece turistler için","Evet","Koruma gereksiz"]',2,'Beceri bağlama göre değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-5','coktan_secmeli','Sanat eserini bağlamıyla değerlendirmek mümkün mü?','["Evet","Hayır","Sadece renk","Sadece çerçeve"]',0,'Beceri bağlama göre değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-6','coktan_secmeli','Estetik yargılar gerekçelendirilebilir mi?','["Hayır","Sadece beğeni","Evet","Gerekçe gerekmez"]',2,'Beceri bağlama göre değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-7','coktan_secmeli','Çok sesli müzikte farklı sesler birlikte uyum oluşturabilir mi?','["Evet","Hayır","Tek ses zorunlu","Müzik olmaz"]',0,'Beceri bağlama göre değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-8','coktan_secmeli','Ses sağlığı korunmalı mıdır?','["Hayır","Bağırmak iyidir","Evet","Ses etkilenmez"]',2,'Beceri bağlama göre değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-9','coktan_secmeli','Tempo ve ölçü müzik yapısını etkiler mi?','["Evet","Hayır","Sadece renk","Sadece söz"]',0,'Beceri bağlama göre değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-10','coktan_secmeli','Ritim kalıpları karşılaştırılabilir mi?','["Hayır","Ritim değişmez","Evet","Sadece ses yüksekliği"]',2,'Beceri bağlama göre değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-11','coktan_secmeli','Kendi ezgi veya ritim fikrini geliştirmek yaratıcılık mıdır?','["Evet","Hayır","Sadece kopya","Müzik değildir"]',0,'Beceri bağlama göre değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-12','coktan_secmeli','Dijital araçlar müzik üretiminde kullanılabilir mi?','["Hayır","Sadece kalem","Evet","Teknoloji yasaktır"]',2,'Beceri bağlama göre değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-13','coktan_secmeli','Farklı müzik türleri kültürel çeşitliliği yansıtabilir mi?','["Evet","Hayır","Hepsi aynıdır","Kültürle ilgisiz"]',0,'Beceri bağlama göre değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-14','coktan_secmeli','Müzik mirasını korumak önemli midir?','["Hayır","Sadece yeni müzik","Evet","Miras gereksiz"]',2,'Beceri bağlama göre değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-15','coktan_secmeli','Koordinasyon karmaşık hareketlerde önemli midir?','["Evet","Hayır","Sadece güç","Koordinasyon gereksiz"]',0,'Beceri bağlama göre değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-16','coktan_secmeli','Güvenli teknik sakatlanma riskini azaltır mı?','["Hayır","Sadece hız","Evet","Teknik önemsiz"]',2,'Beceri bağlama göre değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-17','coktan_secmeli','Dayanıklılık düzenli egzersizle gelişebilir mi?','["Evet","Hayır","Sabit kalır","Sadece besinle"]',0,'Beceri bağlama göre değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-18','coktan_secmeli','Dinlenme ve toparlanma antrenmanın parçası mıdır?','["Hayır","Sadece yarış","Evet","Dinlenme zararlı"]',2,'Beceri bağlama göre değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-19','coktan_secmeli','Takım stratejisi iletişim gerektirir mi?','["Evet","Hayır","Sadece bireysel","İletişim gereksiz"]',0,'Beceri bağlama göre değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-20','coktan_secmeli','Adil oyun kurala ve rakibe saygı içerir mi?','["Hayır","Hile kabul edilir","Evet","Sadece skor"]',2,'Beceri bağlama göre değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-21','coktan_secmeli','Spor toplumsal kültürün parçası olabilir mi?','["Evet","Hayır","Sadece yarış","Kültürle ilgisiz"]',0,'Beceri bağlama göre değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-22','coktan_secmeli','Geleneksel sporlar kültürel miras olabilir mi?','["Hayır","Sadece modern spor","Evet","Miras değildir"]',2,'Beceri bağlama göre değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-23','coktan_secmeli','Kendi değerlerini fark etmek karar vermeyi etkileyebilir mi?','["Evet","Hayır","Sadece notlar","Değerler önemsiz"]',0,'Beceri bağlama göre değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-24','coktan_secmeli','Güçlü ve gelişime açık yönleri birlikte görmek yararlı mıdır?','["Hayır","Sadece güçlü yön","Evet","Gelişim gerekmez"]',2,'Beceri bağlama göre değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-25','coktan_secmeli','Uzun vadeli hedefi ara hedeflere bölmek yararlı mıdır?','["Evet","Hayır","Hedefi bozar","Plan gereksiz"]',0,'Beceri bağlama göre değerlendirilir.',1,25,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-26','coktan_secmeli','Çalışma sürecini izlemek öz düzenleme midir?','["Hayır","Sadece öğretmen işi","Evet","İzleme gereksiz"]',2,'Beceri bağlama göre değerlendirilir.',1,26,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-27','coktan_secmeli','Akran baskısında kendi sınırını ifade etmek önemli midir?','["Evet","Hayır","Her isteğe uyulmalı","Sınır yoktur"]',0,'Beceri bağlama göre değerlendirilir.',1,27,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-28','coktan_secmeli','Çatışmada ben dili kullanılabilir mi?','["Hayır","Sadece suçlama","Evet","Konuşma gerekmez"]',2,'Beceri bağlama göre değerlendirilir.',1,28,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-29','coktan_secmeli','Dijital mahremiyet güvenli yaşamın parçası mıdır?','["Evet","Hayır","Şifreler paylaşılmalı","İnternette mahremiyet yoktur"]',0,'Beceri bağlama göre değerlendirilir.',1,29,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-30','coktan_secmeli','Uyku, hareket ve beslenme dengesi önemlidir mi?','["Hayır","Sadece ders","Evet","Sağlıkla ilgisiz"]',2,'Beceri bağlama göre değerlendirilir.',1,30,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-31','coktan_secmeli','Meslek araştırmasında görevler ve beceriler incelenmeli midir?','["Evet","Hayır","Sadece maaş","Sadece isim"]',0,'Beceri bağlama göre değerlendirilir.',1,31,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-1-32','coktan_secmeli','İlgi alanları zamanla gelişebilir mi?','["Hayır","Tamamen sabittir","Evet","Sadece çocuklukta"]',2,'Beceri bağlama göre değerlendirilir.',1,32,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-1','coktan_secmeli','Vurgu ve denge görsel tasarım ilkeleri midir? Uygulama örneğini düşün.','["Hayır","Evet","Sadece müzik","Sadece matematik"]',1,'Beceri bağlama göre değerlendirilir.',2,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-2','coktan_secmeli','Perspektif derinlik oluşturmada kullanılabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece renk","Sadece doku","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-3','coktan_secmeli','Sanat eserleri kültürel kimlik hakkında bilgi verebilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece fiyat","Kültürle ilgisiz"]',1,'Beceri bağlama göre değerlendirilir.',2,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-4','coktan_secmeli','Miras eserleri korunmalı mıdır? Uygulama örneğini düşün.','["Hayır","Sadece turistler için","Koruma gereksiz","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-5','coktan_secmeli','Sanat eserini bağlamıyla değerlendirmek mümkün mü? Uygulama örneğini düşün.','["Hayır","Evet","Sadece renk","Sadece çerçeve"]',1,'Beceri bağlama göre değerlendirilir.',2,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-6','coktan_secmeli','Estetik yargılar gerekçelendirilebilir mi? Uygulama örneğini düşün.','["Hayır","Sadece beğeni","Gerekçe gerekmez","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-7','coktan_secmeli','Çok sesli müzikte farklı sesler birlikte uyum oluşturabilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Tek ses zorunlu","Müzik olmaz"]',1,'Beceri bağlama göre değerlendirilir.',2,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-8','coktan_secmeli','Ses sağlığı korunmalı mıdır? Uygulama örneğini düşün.','["Hayır","Bağırmak iyidir","Ses etkilenmez","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-9','coktan_secmeli','Tempo ve ölçü müzik yapısını etkiler mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece renk","Sadece söz"]',1,'Beceri bağlama göre değerlendirilir.',2,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-10','coktan_secmeli','Ritim kalıpları karşılaştırılabilir mi? Uygulama örneğini düşün.','["Hayır","Ritim değişmez","Sadece ses yüksekliği","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-11','coktan_secmeli','Kendi ezgi veya ritim fikrini geliştirmek yaratıcılık mıdır? Uygulama örneğini düşün.','["Hayır","Evet","Sadece kopya","Müzik değildir"]',1,'Beceri bağlama göre değerlendirilir.',2,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-12','coktan_secmeli','Dijital araçlar müzik üretiminde kullanılabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece kalem","Teknoloji yasaktır","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-13','coktan_secmeli','Farklı müzik türleri kültürel çeşitliliği yansıtabilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Hepsi aynıdır","Kültürle ilgisiz"]',1,'Beceri bağlama göre değerlendirilir.',2,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-14','coktan_secmeli','Müzik mirasını korumak önemli midir? Uygulama örneğini düşün.','["Hayır","Sadece yeni müzik","Miras gereksiz","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-15','coktan_secmeli','Koordinasyon karmaşık hareketlerde önemli midir? Uygulama örneğini düşün.','["Hayır","Evet","Sadece güç","Koordinasyon gereksiz"]',1,'Beceri bağlama göre değerlendirilir.',2,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-16','coktan_secmeli','Güvenli teknik sakatlanma riskini azaltır mı? Uygulama örneğini düşün.','["Hayır","Sadece hız","Teknik önemsiz","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-17','coktan_secmeli','Dayanıklılık düzenli egzersizle gelişebilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Sabit kalır","Sadece besinle"]',1,'Beceri bağlama göre değerlendirilir.',2,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-18','coktan_secmeli','Dinlenme ve toparlanma antrenmanın parçası mıdır? Uygulama örneğini düşün.','["Hayır","Sadece yarış","Dinlenme zararlı","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-19','coktan_secmeli','Takım stratejisi iletişim gerektirir mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece bireysel","İletişim gereksiz"]',1,'Beceri bağlama göre değerlendirilir.',2,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-20','coktan_secmeli','Adil oyun kurala ve rakibe saygı içerir mi? Uygulama örneğini düşün.','["Hayır","Hile kabul edilir","Sadece skor","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-21','coktan_secmeli','Spor toplumsal kültürün parçası olabilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece yarış","Kültürle ilgisiz"]',1,'Beceri bağlama göre değerlendirilir.',2,121,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-22','coktan_secmeli','Geleneksel sporlar kültürel miras olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece modern spor","Miras değildir","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,122,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-23','coktan_secmeli','Kendi değerlerini fark etmek karar vermeyi etkileyebilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece notlar","Değerler önemsiz"]',1,'Beceri bağlama göre değerlendirilir.',2,123,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-24','coktan_secmeli','Güçlü ve gelişime açık yönleri birlikte görmek yararlı mıdır? Uygulama örneğini düşün.','["Hayır","Sadece güçlü yön","Gelişim gerekmez","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,124,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-25','coktan_secmeli','Uzun vadeli hedefi ara hedeflere bölmek yararlı mıdır? Uygulama örneğini düşün.','["Hayır","Evet","Hedefi bozar","Plan gereksiz"]',1,'Beceri bağlama göre değerlendirilir.',2,125,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-26','coktan_secmeli','Çalışma sürecini izlemek öz düzenleme midir? Uygulama örneğini düşün.','["Hayır","Sadece öğretmen işi","İzleme gereksiz","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,126,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-27','coktan_secmeli','Akran baskısında kendi sınırını ifade etmek önemli midir? Uygulama örneğini düşün.','["Hayır","Evet","Her isteğe uyulmalı","Sınır yoktur"]',1,'Beceri bağlama göre değerlendirilir.',2,127,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-28','coktan_secmeli','Çatışmada ben dili kullanılabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece suçlama","Konuşma gerekmez","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,128,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-29','coktan_secmeli','Dijital mahremiyet güvenli yaşamın parçası mıdır? Uygulama örneğini düşün.','["Hayır","Evet","Şifreler paylaşılmalı","İnternette mahremiyet yoktur"]',1,'Beceri bağlama göre değerlendirilir.',2,129,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-30','coktan_secmeli','Uyku, hareket ve beslenme dengesi önemlidir mi? Uygulama örneğini düşün.','["Hayır","Sadece ders","Sağlıkla ilgisiz","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,130,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-31','coktan_secmeli','Meslek araştırmasında görevler ve beceriler incelenmeli midir? Uygulama örneğini düşün.','["Hayır","Evet","Sadece maaş","Sadece isim"]',1,'Beceri bağlama göre değerlendirilir.',2,131,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-2-32','coktan_secmeli','İlgi alanları zamanla gelişebilir mi? Uygulama örneğini düşün.','["Hayır","Tamamen sabittir","Sadece çocuklukta","Evet"]',3,'Beceri bağlama göre değerlendirilir.',2,132,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-1','coktan_secmeli','Vurgu ve denge görsel tasarım ilkeleri midir? Uygulama örneğini düşün.','["Hayır","Sadece müzik","Evet","Sadece matematik"]',2,'Beceri bağlama göre değerlendirilir.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-2','coktan_secmeli','Perspektif derinlik oluşturmada kullanılabilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece renk","Sadece doku"]',0,'Beceri bağlama göre değerlendirilir.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-3','coktan_secmeli','Sanat eserleri kültürel kimlik hakkında bilgi verebilir mi? Uygulama örneğini düşün.','["Hayır","Sadece fiyat","Evet","Kültürle ilgisiz"]',2,'Beceri bağlama göre değerlendirilir.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-4','coktan_secmeli','Miras eserleri korunmalı mıdır? Uygulama örneğini düşün.','["Evet","Hayır","Sadece turistler için","Koruma gereksiz"]',0,'Beceri bağlama göre değerlendirilir.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-5','coktan_secmeli','Sanat eserini bağlamıyla değerlendirmek mümkün mü? Uygulama örneğini düşün.','["Hayır","Sadece renk","Evet","Sadece çerçeve"]',2,'Beceri bağlama göre değerlendirilir.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-6','coktan_secmeli','Estetik yargılar gerekçelendirilebilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece beğeni","Gerekçe gerekmez"]',0,'Beceri bağlama göre değerlendirilir.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-7','coktan_secmeli','Çok sesli müzikte farklı sesler birlikte uyum oluşturabilir mi? Uygulama örneğini düşün.','["Hayır","Tek ses zorunlu","Evet","Müzik olmaz"]',2,'Beceri bağlama göre değerlendirilir.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-8','coktan_secmeli','Ses sağlığı korunmalı mıdır? Uygulama örneğini düşün.','["Evet","Hayır","Bağırmak iyidir","Ses etkilenmez"]',0,'Beceri bağlama göre değerlendirilir.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-9','coktan_secmeli','Tempo ve ölçü müzik yapısını etkiler mi? Uygulama örneğini düşün.','["Hayır","Sadece renk","Evet","Sadece söz"]',2,'Beceri bağlama göre değerlendirilir.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-10','coktan_secmeli','Ritim kalıpları karşılaştırılabilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Ritim değişmez","Sadece ses yüksekliği"]',0,'Beceri bağlama göre değerlendirilir.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-11','coktan_secmeli','Kendi ezgi veya ritim fikrini geliştirmek yaratıcılık mıdır? Uygulama örneğini düşün.','["Hayır","Sadece kopya","Evet","Müzik değildir"]',2,'Beceri bağlama göre değerlendirilir.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-12','coktan_secmeli','Dijital araçlar müzik üretiminde kullanılabilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece kalem","Teknoloji yasaktır"]',0,'Beceri bağlama göre değerlendirilir.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-13','coktan_secmeli','Farklı müzik türleri kültürel çeşitliliği yansıtabilir mi? Uygulama örneğini düşün.','["Hayır","Hepsi aynıdır","Evet","Kültürle ilgisiz"]',2,'Beceri bağlama göre değerlendirilir.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-14','coktan_secmeli','Müzik mirasını korumak önemli midir? Uygulama örneğini düşün.','["Evet","Hayır","Sadece yeni müzik","Miras gereksiz"]',0,'Beceri bağlama göre değerlendirilir.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-15','coktan_secmeli','Koordinasyon karmaşık hareketlerde önemli midir? Uygulama örneğini düşün.','["Hayır","Sadece güç","Evet","Koordinasyon gereksiz"]',2,'Beceri bağlama göre değerlendirilir.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-16','coktan_secmeli','Güvenli teknik sakatlanma riskini azaltır mı? Uygulama örneğini düşün.','["Evet","Hayır","Sadece hız","Teknik önemsiz"]',0,'Beceri bağlama göre değerlendirilir.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-17','coktan_secmeli','Dayanıklılık düzenli egzersizle gelişebilir mi? Uygulama örneğini düşün.','["Hayır","Sabit kalır","Evet","Sadece besinle"]',2,'Beceri bağlama göre değerlendirilir.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-18','coktan_secmeli','Dinlenme ve toparlanma antrenmanın parçası mıdır? Uygulama örneğini düşün.','["Evet","Hayır","Sadece yarış","Dinlenme zararlı"]',0,'Beceri bağlama göre değerlendirilir.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-19','coktan_secmeli','Takım stratejisi iletişim gerektirir mi? Uygulama örneğini düşün.','["Hayır","Sadece bireysel","Evet","İletişim gereksiz"]',2,'Beceri bağlama göre değerlendirilir.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-20','coktan_secmeli','Adil oyun kurala ve rakibe saygı içerir mi? Uygulama örneğini düşün.','["Evet","Hayır","Hile kabul edilir","Sadece skor"]',0,'Beceri bağlama göre değerlendirilir.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-21','coktan_secmeli','Spor toplumsal kültürün parçası olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece yarış","Evet","Kültürle ilgisiz"]',2,'Beceri bağlama göre değerlendirilir.',2,221,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-22','coktan_secmeli','Geleneksel sporlar kültürel miras olabilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece modern spor","Miras değildir"]',0,'Beceri bağlama göre değerlendirilir.',2,222,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-23','coktan_secmeli','Kendi değerlerini fark etmek karar vermeyi etkileyebilir mi? Uygulama örneğini düşün.','["Hayır","Sadece notlar","Evet","Değerler önemsiz"]',2,'Beceri bağlama göre değerlendirilir.',2,223,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-24','coktan_secmeli','Güçlü ve gelişime açık yönleri birlikte görmek yararlı mıdır? Uygulama örneğini düşün.','["Evet","Hayır","Sadece güçlü yön","Gelişim gerekmez"]',0,'Beceri bağlama göre değerlendirilir.',2,224,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-25','coktan_secmeli','Uzun vadeli hedefi ara hedeflere bölmek yararlı mıdır? Uygulama örneğini düşün.','["Hayır","Hedefi bozar","Evet","Plan gereksiz"]',2,'Beceri bağlama göre değerlendirilir.',2,225,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-26','coktan_secmeli','Çalışma sürecini izlemek öz düzenleme midir? Uygulama örneğini düşün.','["Evet","Hayır","Sadece öğretmen işi","İzleme gereksiz"]',0,'Beceri bağlama göre değerlendirilir.',2,226,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-27','coktan_secmeli','Akran baskısında kendi sınırını ifade etmek önemli midir? Uygulama örneğini düşün.','["Hayır","Her isteğe uyulmalı","Evet","Sınır yoktur"]',2,'Beceri bağlama göre değerlendirilir.',2,227,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-28','coktan_secmeli','Çatışmada ben dili kullanılabilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece suçlama","Konuşma gerekmez"]',0,'Beceri bağlama göre değerlendirilir.',2,228,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-29','coktan_secmeli','Dijital mahremiyet güvenli yaşamın parçası mıdır? Uygulama örneğini düşün.','["Hayır","Şifreler paylaşılmalı","Evet","İnternette mahremiyet yoktur"]',2,'Beceri bağlama göre değerlendirilir.',2,229,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-30','coktan_secmeli','Uyku, hareket ve beslenme dengesi önemlidir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece ders","Sağlıkla ilgisiz"]',0,'Beceri bağlama göre değerlendirilir.',2,230,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-31','coktan_secmeli','Meslek araştırmasında görevler ve beceriler incelenmeli midir? Uygulama örneğini düşün.','["Hayır","Sadece maaş","Evet","Sadece isim"]',2,'Beceri bağlama göre değerlendirilir.',2,231,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7o-3-32','coktan_secmeli','İlgi alanları zamanla gelişebilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Tamamen sabittir","Sadece çocuklukta"]',0,'Beceri bağlama göre değerlendirilir.',2,232,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='o7-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

