const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const bridge=fs.readFileSync(__dirname+'/../adimbot-ai-bridge.js','utf8'),chat=fs.readFileSync(__dirname+'/../adimbot-chat-ui.js','utf8');
const bridgeFns=bridge.slice(bridge.indexOf('  const prepareRequest='),bridge.indexOf('  const responseViolatesPolicy='));
function bridgeHarness(){const c={window:{dispatchEvent(){}},CustomEvent:class{},AbortController,Date,Error,TypeError,fetch:()=>{throw Error('unexpected fetch');},setTimeout,clearTimeout,navigator:{onLine:true}};vm.createContext(c);vm.runInContext(bridge,c);return c.window.AdimBotAI;}
function helperHarness(start,end,extras={}){const c={Date,Math,Set,Boolean,String,Number,Promise,Error,console,clean:value=>String(value??'').normalize('NFC').replace(/\s+/g,' ').trim(),...extras};vm.createContext(c);const code=chat.slice(chat.indexOf(start),chat.indexOf(end,chat.indexOf(start)));const id=(code.match(/const\s+([A-Za-z_$][\w$]*)\s*=/)||[])[1];vm.runInContext(code+(id?`\nthis.__helper=${id};`:''),c);return c;}
async function run(){
// 1: cancellation also wins for registered/custom providers that ignore AbortSignal.
{const ai=bridgeHarness();let finish;ai.registerProvider(()=>new Promise(resolve=>finish=resolve));const controller=new AbortController();const pending=ai.ask('Merhaba',{},[],{signal:controller.signal});await new Promise(setImmediate);controller.abort();const cancelled=await pending;assert.equal(cancelled.reason,'cancelled');finish({text:'Artık geç.'});await new Promise(setImmediate);assert.equal(cancelled.text,'İstek durduruldu.');}
// 2: output containing no word/number becomes the safe generic response.
{const ai=bridgeHarness();for(const raw of ['?!','...','👋']){const result=ai.sanitizeResponse(raw);assert.equal(result.blocked,true);assert.equal(result.reason,'empty');assert.match(result.text,/güvenli/);}}
// 3: provider cooldown applies only to quota categories.
{const c={Date,Math,Number,String};vm.createContext(c);vm.runInContext(chat.slice(chat.indexOf('  const retryAfterSeconds='),chat.indexOf('  const cooldownRemaining='))+"const quotaChatReasons=new Set(['provider_rate_limit','rate_limit']);"+chat.slice(chat.indexOf('  const chatCooldownSeconds='),chat.indexOf('  const isUnclearTranscript='))+'\nthis.cooldown=chatCooldownSeconds;',c);assert.equal(c.cooldown('provider_rate_limit','27'),27);assert.equal(c.cooldown('rate_limit','27'),27);for(const reason of ['provider_auth_error','provider_permission_error','provider_config_error','invalid_response'])assert.equal(c.cooldown(reason,'27'),0);}
// 4: fixable provider/model diagnostics retain the typed question for retry.
{const start=chat.indexOf('  const retryableChatReasons='),end=chat.indexOf('  const microphoneStartMessage=',start),c={Set};vm.createContext(c);vm.runInContext(chat.slice(start,end)+'\nthis.retryableChatReasons=retryableChatReasons;this.retryHint=retryHint;',c);for(const reason of ['provider_auth_error','provider_permission_error','api_key_missing','model_missing','provider_model_retired','provider_model_unavailable','provider_config_error','provider_disabled','ai_disabled','curl_missing']){assert.equal(c.retryableChatReasons.has(reason),true,reason);assert.doesNotMatch(c.retryHint(reason),/api.?key|model id|403|401/i);}}
// 5: repeated failed submissions update one existing retry bubble instead of stacking errors.
{let added=0,body={textContent:''},bubble={isConnected:true,querySelector:()=>body};const extras={failedReplyBubble:null,appendMessage(){added++;return bubble;}};const c=helperHarness('  const appendFailureReply=','  const requestRecognizedSubmit=',extras);const box={scrollHeight:100,scrollTop:100,clientHeight:80};c.__helper(box,'Ağ yanıt vermedi.',false);c.__helper(box,'Modeli kontrol et.',true);assert.equal(added,1);assert.equal(body.textContent,'Modeli kontrol et.');}
// 6: the question context passed to AI is the same snapshot used for final sanitizing.
assert.match(chat,/const requestContext=learningContext\(\);[\s\S]*?ai\.ask\(message,requestContext,/);assert.match(chat,/ai\.deliver\(answer,\{activeQuestion:Boolean\(requestContext\.question\)\}\)/);
// 7: reopening saved chat moves to the last message after layout; stale callbacks do nothing.
{let callback;const dialog={hidden:false,querySelector:()=>messages};const messages={scrollHeight:940,scrollTop:0};const c={focusGeneration:4,focusToken:4,dialog:{hidden:false},messages,window:{requestAnimationFrame(fn){callback=fn;}},setTimeout};vm.createContext(c);const i=chat.indexOf('    const alignHistory='),j=chat.indexOf('    setTimeout(()=>{',i);vm.runInContext(chat.slice(i,j),c);callback();assert.equal(messages.scrollTop,940);messages.scrollTop=2;c.focusGeneration++;callback();assert.equal(messages.scrollTop,2);}
// 8: microphone control cannot start while the AI request is busy and gets a clear label.
{const c=helperHarness('  const setChatControlsBusy=','  const appendFailureReply=',{input:{},submit:{},mic:{setAttribute(k,v){this[k]=v;}}});c.__helper(true,c.input,c.submit,c.mic);assert.equal(c.input.disabled,true);assert.equal(c.submit.disabled,true);assert.equal(c.mic.disabled,true);assert.match(c.mic['aria-label'],/yanıt verirken/);c.__helper(false,c.input,c.submit,c.mic);assert.equal(c.mic.disabled,false);assert.equal(c.mic['aria-label'],'Mikrofonla sor');}
// 9,10: blank-audio and media markers are rejected; real single-word questions remain.
{const c=helperHarness('  const isUnclearTranscript=','  const answerEmotion=');for(const marker of ['[BLANK_AUDIO]','[blank audio]','[NO_SPEECH]','[MUSIC]','[APPLAUSE]','(sessizlik)','...','?!'])assert.equal(c.__helper(marker),true,marker);for(const word of ['Müzik','A','2','Merhaba'])assert.equal(c.__helper(word),false,word);assert.equal(c.__helper({text:'soru'}),true);}
// 11: older Safari sends via the actual submit button when requestSubmit is missing.
{const c=helperHarness('  const requestRecognizedSubmit=','  const cancelChat=',{status:{textContent:''}});let clicked=0;assert.equal(c.__helper({querySelector(sel){assert.equal(sel,'button[type="submit"]');return {click(){clicked++;}};}},c.status),true);assert.equal(clicked,1);assert.equal(c.__helper({},c.status),false);assert.match(c.status.textContent,/Gönder düğmesine/);}
// 12: recognized speech appends to a draft without discarding or duplicating the student's typed words.
{const c=helperHarness('  const mergeRecognizedDraft=','  const answerEmotion=');assert.equal(c.__helper('Dersim matematik','yardım eder misin?'),'Dersim matematik yardım eder misin?');assert.equal(c.__helper('Matematik','matematik'),'Matematik');assert.equal(c.__helper('','Sorumu dinle'),'Sorumu dinle');}
// 13: ordinary answers use thoughtful/positive face; blocked replies remain supportive.
{const c=helperHarness('  const answerEmotion=','  const setChatControlsBusy=');assert.equal(c.__helper({ok:true},'Harika bir örnek.'),'happy');assert.equal(c.__helper({ok:true},'Nasıl düşünüyorsun?'),'think');assert.equal(c.__helper({blocked:true},'Güvendiğin bir yetişkine haber ver.'),'encourage');}
// 14: the safety path still asks delivery for the calm gesture mode.
{const spoken=[];const harness={window:{AdimBotStudent:{speakLong:(text,options)=>spoken.push({text,options})}},CustomEvent:class{},Date};
// Execute the bridge with the real robot stub so deliver reaches its speech option.
vm.createContext(harness);vm.runInContext(bridge,harness);harness.window.AdimBotAI.deliver({text:'Güvendiğin bir yetişkine haber ver.',blocked:true,reason:'self_harm'});assert.equal(spoken.at(-1).options.gentle,true);}
// 15: a replaced chat request owns its retry bubble only while its generation is current.
{assert.match(chat,/if\(requestGeneration!==chatGeneration\)return;/);assert.match(chat,/const requestGeneration=\+\+chatGeneration/);}
// 16: technical provider errors stay in the student-safe wording; secrets and provider codes never render.
{const c=helperHarness('  const retryableChatReasons=','  const microphoneStartMessage=',{Set});vm.runInContext('this.retryHint=retryHint;',c);for(const reason of ['provider_auth_error','provider_permission_error','provider_config_error','curl_missing'])assert.doesNotMatch(c.retryHint(reason),/\d{3}|api[ _-]?key|sk-|token/i);}
console.log('PASS: 16 chat cancellation, retry ownership, draft preservation, student-safe diagnostics, voice submission and expression scenarios.');
}
run().catch(error=>{console.error(error);process.exitCode=1;});
