SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-cocukluk','Mustafa Kemal''in Çocukluğu ve Eğitimi','Mustafa Kemal''in Çocukluğu ve Eğitimi','Mustafa Kemal''in Çocukluğu ve Eğitimi becerilerini uygular.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-kahraman' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-fikir','Fikir Hayatı ve Askerlik','Fikir Hayatı ve Askerlik','Fikir Hayatı ve Askerlik becerilerini uygular.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-kahraman' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-savas','I. Dünya Savaşı ve Osmanlı Devleti','I. Dünya Savaşı ve Osmanlı Devleti','I. Dünya Savaşı ve Osmanlı Devleti becerilerini uygular.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-uyanis' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-milli','Mondros, İşgaller ve Millî Mücadele Hazırlığı','Mondros, İşgaller ve Millî Mücadele Hazırlığı','Mondros, İşgaller ve Millî Mücadele Hazırlığı becerilerini uygular.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-uyanis' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-cephe','Cepheler ve Millî Mücadele','Cepheler ve Millî Mücadele','Cepheler ve Millî Mücadele becerilerini uygular.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-destan' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-antlasma','Mudanya ve Lozan','Mudanya ve Lozan','Mudanya ve Lozan becerilerini uygular.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-destan' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-ilke','Atatürk İlkeleri','Atatürk İlkeleri','Atatürk İlkeleri becerilerini uygular.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-ataturkculuk' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-inkilap','Siyasi, Hukuki, Eğitim ve Toplumsal İnkılaplar','Siyasi, Hukuki, Eğitim ve Toplumsal İnkılaplar','Siyasi, Hukuki, Eğitim ve Toplumsal İnkılaplar becerilerini uygular.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-ataturkculuk' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-cokparti','Çok Partili Hayata Geçiş Denemeleri','Çok Partili Hayata Geçiş Denemeleri','Çok Partili Hayata Geçiş Denemeleri becerilerini uygular.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-demokrasi' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-demokrasi','Demokrasi ve Cumhuriyet','Demokrasi ve Cumhuriyet','Demokrasi ve Cumhuriyet becerilerini uygular.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-demokrasi' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-dis-politika','Atatürk Dönemi Dış Politika İlkeleri','Atatürk Dönemi Dış Politika İlkeleri','Atatürk Dönemi Dış Politika İlkeleri becerilerini uygular.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-dis' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-hatay','Hatay ve Bölgesel Gelişmeler','Hatay ve Bölgesel Gelişmeler','Hatay ve Bölgesel Gelişmeler becerilerini uygular.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-dis' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-olum','Atatürk''ün Ölümü ve Mirası','Atatürk''ün Ölümü ve Mirası','Atatürk''ün Ölümü ve Mirası becerilerini uygular.','',130,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-sonrasi' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',8,'i8-ikinci-savas','II. Dünya Savaşı ve Türkiye','II. Dünya Savaşı ve Türkiye','II. Dünya Savaşı ve Türkiye becerilerini uygular.','',140,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=8 AND b.kod='ink8-sonrasi' WHERE d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-1','coktan_secmeli','Mustafa Kemal Selanik''te doğmuştur. Doğru mu?','["Evet","Hayır","Ankara''da","İstanbul''da"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cocukluk' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-2','coktan_secmeli','Askerî eğitim onun kariyerinde önemli olmuş mudur?','["Hayır","Sadece hukuk okudu","Evet","Eğitim almamıştır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cocukluk' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-3','coktan_secmeli','Fransız İhtilali''nin milliyetçilik düşüncesi Osmanlı''yı etkilemiş midir?','["Evet","Hayır","Sadece ekonomiyi","Hiçbir etkisi yok"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-fikir' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-4','coktan_secmeli','Mustafa Kemal farklı düşünce akımlarını takip etmiş midir?','["Hayır","Sadece askerî emirleri","Evet","Fikir hayatı yoktur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-fikir' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-5','coktan_secmeli','Osmanlı Devleti I. Dünya Savaşı''na katılmış mıdır?','["Evet","Hayır","Tarafsız kalmıştır","Savaş sonrası kurulmuştur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-6','coktan_secmeli','Çanakkale Cephesi Mustafa Kemal''in askerî başarısıyla ilişkilidir mi?','["Hayır","Sadece Kafkas Cephesi","Evet","Mustafa Kemal katılmamıştır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-7','coktan_secmeli','Mondros Ateşkes Antlaşması sonrası işgaller başlamış mıdır?','["Evet","Hayır","Lozan imzalanmıştır","Cumhuriyet kurulmuştur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-milli' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-8','coktan_secmeli','Amasya Genelgesi Millî Mücadele açısından önemli midir?','["Hayır","Sadece ekonomik belge","Evet","Savaş sonrası yazılmıştır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-milli' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-9','coktan_secmeli','Sakarya Meydan Muharebesi Millî Mücadele''nin önemli savaşlarından mıdır?','["Evet","Hayır","I. Dünya Savaşı cephesidir","Balkan Savaşıdır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cephe' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-10','coktan_secmeli','Büyük Taarruz işgal kuvvetlerinin Anadolu''dan çıkarılmasında belirleyici olmuş mudur?','["Hayır","Sadece savunma savaşı","Evet","Cumhuriyet sonrası olmuştur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cephe' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-11','coktan_secmeli','Mudanya Ateşkes Antlaşması silahlı çatışmaları büyük ölçüde sona erdirmiş midir?','["Evet","Hayır","Savaşı başlatmıştır","I. Dünya Savaşı öncesidir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-antlasma' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-12','coktan_secmeli','Lozan Antlaşması yeni Türk devletinin uluslararası tanınması açısından önemli midir?','["Hayır","Sadece yerel anlaşma","Evet","Osmanlı''nın kuruluş belgesidir"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-antlasma' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-13','coktan_secmeli','Cumhuriyetçilik halk egemenliğiyle ilişkilidir mi?','["Evet","Hayır","Sadece ekonomi","Sadece eğitim"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ilke' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-14','coktan_secmeli','Laiklik din ve devlet işlerinin düzenlenmesiyle ilişkilidir mi?','["Hayır","Sadece dış politika","Evet","Sadece tarım"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ilke' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-15','coktan_secmeli','Harf İnkılabı eğitim ve kültür alanıyla ilişkili midir?','["Evet","Hayır","Sadece askerî","Sadece dış politika"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-inkilap' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-16','coktan_secmeli','Medeni Kanun hukuk alanındaki inkılaplardan mıdır?','["Hayır","Sadece eğitim","Evet","Sadece ekonomi"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-inkilap' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-17','coktan_secmeli','Terakkiperver Cumhuriyet Fırkası çok partili hayat denemelerinden biri midir?','["Evet","Hayır","Cumhuriyet öncesi padişahlık","Yabancı parti"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cokparti' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-18','coktan_secmeli','Serbest Cumhuriyet Fırkası da bir çok partili hayat denemesi midir?','["Hayır","Sadece dernek","Evet","Sadece gazete"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cokparti' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-19','coktan_secmeli','Cumhuriyet yönetimi millî egemenlik ilkesini esas alır mı?','["Evet","Hayır","Saltanat esaslıdır","Sadece ekonomik modeldir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-demokrasi' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-20','coktan_secmeli','Seçimler demokratik katılım araçlarından biri midir?','["Hayır","Sadece tören","Evet","Sadece yargı"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-demokrasi' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-21','coktan_secmeli','“Yurtta sulh, cihanda sulh” barışçı dış politika anlayışıyla ilişkili midir?','["Evet","Hayır","Saldırganlık","İçe kapanma"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-dis-politika' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-22','coktan_secmeli','Türkiye Milletler Cemiyetine katılmış mıdır?','["Hayır","Hiç uluslararası kuruma katılmadı","Evet","Sadece NATO''ya kuruluşta"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-dis-politika' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-23','coktan_secmeli','Hatay Türkiye''ye Atatürk döneminin hemen ardından katılmıştır. Bu süreç Atatürk''ün dış politika hedefleriyle ilişkili midir?','["Evet","Hayır","Hatay hiç katılmadı","Sadece ekonomik meseleydi"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-hatay' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-24','coktan_secmeli','Hatay meselesinde diplomasi önemli rol oynamış mıdır?','["Hayır","Sadece savaş","Evet","Diplomasi kullanılmamıştır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-hatay' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-25','coktan_secmeli','Atatürk 1938 yılında vefat etmiştir. Doğru mu?','["Evet","Hayır","1923","1950"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,25,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-olum' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-26','coktan_secmeli','Atatürk''ün ilke ve inkılapları Cumhuriyet''in gelişiminde etkili olmuş mudur?','["Hayır","Sadece askerî alan","Evet","Hiç etkisi yok"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,26,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-olum' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-27','coktan_secmeli','Türkiye II. Dünya Savaşı''nın büyük bölümünde savaş dışında kalmaya çalışmış mıdır?','["Evet","Hayır","Başından beri cephedeydi","Savaş Türkiye''de başladı"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,27,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ikinci-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-1-28','coktan_secmeli','II. Dünya Savaşı Türkiye''nin ekonomi ve dış politikasını etkilemiş midir?','["Hayır","Hiç etkisi yok","Evet","Sadece sporu etkiledi"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,28,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ikinci-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-1','coktan_secmeli','Mustafa Kemal Selanik''te doğmuştur. Doğru mu? Benzer bir örneği düşün.','["Hayır","Evet","Ankara''da","İstanbul''da"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cocukluk' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-2','coktan_secmeli','Askerî eğitim onun kariyerinde önemli olmuş mudur? Benzer bir örneği düşün.','["Hayır","Sadece hukuk okudu","Eğitim almamıştır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cocukluk' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-3','coktan_secmeli','Fransız İhtilali''nin milliyetçilik düşüncesi Osmanlı''yı etkilemiş midir? Benzer bir örneği düşün.','["Hayır","Evet","Sadece ekonomiyi","Hiçbir etkisi yok"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-fikir' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-4','coktan_secmeli','Mustafa Kemal farklı düşünce akımlarını takip etmiş midir? Benzer bir örneği düşün.','["Hayır","Sadece askerî emirleri","Fikir hayatı yoktur","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-fikir' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-5','coktan_secmeli','Osmanlı Devleti I. Dünya Savaşı''na katılmış mıdır? Benzer bir örneği düşün.','["Hayır","Evet","Tarafsız kalmıştır","Savaş sonrası kurulmuştur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-6','coktan_secmeli','Çanakkale Cephesi Mustafa Kemal''in askerî başarısıyla ilişkilidir mi? Benzer bir örneği düşün.','["Hayır","Sadece Kafkas Cephesi","Mustafa Kemal katılmamıştır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-7','coktan_secmeli','Mondros Ateşkes Antlaşması sonrası işgaller başlamış mıdır? Benzer bir örneği düşün.','["Hayır","Evet","Lozan imzalanmıştır","Cumhuriyet kurulmuştur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-milli' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-8','coktan_secmeli','Amasya Genelgesi Millî Mücadele açısından önemli midir? Benzer bir örneği düşün.','["Hayır","Sadece ekonomik belge","Savaş sonrası yazılmıştır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-milli' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-9','coktan_secmeli','Sakarya Meydan Muharebesi Millî Mücadele''nin önemli savaşlarından mıdır? Benzer bir örneği düşün.','["Hayır","Evet","I. Dünya Savaşı cephesidir","Balkan Savaşıdır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cephe' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-10','coktan_secmeli','Büyük Taarruz işgal kuvvetlerinin Anadolu''dan çıkarılmasında belirleyici olmuş mudur? Benzer bir örneği düşün.','["Hayır","Sadece savunma savaşı","Cumhuriyet sonrası olmuştur","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cephe' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-11','coktan_secmeli','Mudanya Ateşkes Antlaşması silahlı çatışmaları büyük ölçüde sona erdirmiş midir? Benzer bir örneği düşün.','["Hayır","Evet","Savaşı başlatmıştır","I. Dünya Savaşı öncesidir"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-antlasma' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-12','coktan_secmeli','Lozan Antlaşması yeni Türk devletinin uluslararası tanınması açısından önemli midir? Benzer bir örneği düşün.','["Hayır","Sadece yerel anlaşma","Osmanlı''nın kuruluş belgesidir","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-antlasma' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-13','coktan_secmeli','Cumhuriyetçilik halk egemenliğiyle ilişkilidir mi? Benzer bir örneği düşün.','["Hayır","Evet","Sadece ekonomi","Sadece eğitim"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ilke' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-14','coktan_secmeli','Laiklik din ve devlet işlerinin düzenlenmesiyle ilişkilidir mi? Benzer bir örneği düşün.','["Hayır","Sadece dış politika","Sadece tarım","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ilke' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-15','coktan_secmeli','Harf İnkılabı eğitim ve kültür alanıyla ilişkili midir? Benzer bir örneği düşün.','["Hayır","Evet","Sadece askerî","Sadece dış politika"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-inkilap' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-16','coktan_secmeli','Medeni Kanun hukuk alanındaki inkılaplardan mıdır? Benzer bir örneği düşün.','["Hayır","Sadece eğitim","Sadece ekonomi","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-inkilap' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-17','coktan_secmeli','Terakkiperver Cumhuriyet Fırkası çok partili hayat denemelerinden biri midir? Benzer bir örneği düşün.','["Hayır","Evet","Cumhuriyet öncesi padişahlık","Yabancı parti"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cokparti' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-18','coktan_secmeli','Serbest Cumhuriyet Fırkası da bir çok partili hayat denemesi midir? Benzer bir örneği düşün.','["Hayır","Sadece dernek","Sadece gazete","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cokparti' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-19','coktan_secmeli','Cumhuriyet yönetimi millî egemenlik ilkesini esas alır mı? Benzer bir örneği düşün.','["Hayır","Evet","Saltanat esaslıdır","Sadece ekonomik modeldir"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-demokrasi' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-20','coktan_secmeli','Seçimler demokratik katılım araçlarından biri midir? Benzer bir örneği düşün.','["Hayır","Sadece tören","Sadece yargı","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-demokrasi' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-21','coktan_secmeli','“Yurtta sulh, cihanda sulh” barışçı dış politika anlayışıyla ilişkili midir? Benzer bir örneği düşün.','["Hayır","Evet","Saldırganlık","İçe kapanma"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,121,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-dis-politika' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-22','coktan_secmeli','Türkiye Milletler Cemiyetine katılmış mıdır? Benzer bir örneği düşün.','["Hayır","Hiç uluslararası kuruma katılmadı","Sadece NATO''ya kuruluşta","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,122,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-dis-politika' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-23','coktan_secmeli','Hatay Türkiye''ye Atatürk döneminin hemen ardından katılmıştır. Bu süreç Atatürk''ün dış politika hedefleriyle ilişkili midir? Benzer bir örneği düşün.','["Hayır","Evet","Hatay hiç katılmadı","Sadece ekonomik meseleydi"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,123,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-hatay' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-24','coktan_secmeli','Hatay meselesinde diplomasi önemli rol oynamış mıdır? Benzer bir örneği düşün.','["Hayır","Sadece savaş","Diplomasi kullanılmamıştır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,124,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-hatay' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-25','coktan_secmeli','Atatürk 1938 yılında vefat etmiştir. Doğru mu? Benzer bir örneği düşün.','["Hayır","Evet","1923","1950"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,125,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-olum' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-26','coktan_secmeli','Atatürk''ün ilke ve inkılapları Cumhuriyet''in gelişiminde etkili olmuş mudur? Benzer bir örneği düşün.','["Hayır","Sadece askerî alan","Hiç etkisi yok","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,126,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-olum' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-27','coktan_secmeli','Türkiye II. Dünya Savaşı''nın büyük bölümünde savaş dışında kalmaya çalışmış mıdır? Benzer bir örneği düşün.','["Hayır","Evet","Başından beri cephedeydi","Savaş Türkiye''de başladı"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,127,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ikinci-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-2-28','coktan_secmeli','II. Dünya Savaşı Türkiye''nin ekonomi ve dış politikasını etkilemiş midir? Benzer bir örneği düşün.','["Hayır","Hiç etkisi yok","Sadece sporu etkiledi","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,128,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ikinci-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-1','coktan_secmeli','Mustafa Kemal Selanik''te doğmuştur. Doğru mu? Yeni bir bağlama uygula.','["Hayır","Ankara''da","Evet","İstanbul''da"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cocukluk' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-2','coktan_secmeli','Askerî eğitim onun kariyerinde önemli olmuş mudur? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece hukuk okudu","Eğitim almamıştır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cocukluk' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-3','coktan_secmeli','Fransız İhtilali''nin milliyetçilik düşüncesi Osmanlı''yı etkilemiş midir? Yeni bir bağlama uygula.','["Hayır","Sadece ekonomiyi","Evet","Hiçbir etkisi yok"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-fikir' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-4','coktan_secmeli','Mustafa Kemal farklı düşünce akımlarını takip etmiş midir? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece askerî emirleri","Fikir hayatı yoktur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-fikir' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-5','coktan_secmeli','Osmanlı Devleti I. Dünya Savaşı''na katılmış mıdır? Yeni bir bağlama uygula.','["Hayır","Tarafsız kalmıştır","Evet","Savaş sonrası kurulmuştur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-6','coktan_secmeli','Çanakkale Cephesi Mustafa Kemal''in askerî başarısıyla ilişkilidir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece Kafkas Cephesi","Mustafa Kemal katılmamıştır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-7','coktan_secmeli','Mondros Ateşkes Antlaşması sonrası işgaller başlamış mıdır? Yeni bir bağlama uygula.','["Hayır","Lozan imzalanmıştır","Evet","Cumhuriyet kurulmuştur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-milli' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-8','coktan_secmeli','Amasya Genelgesi Millî Mücadele açısından önemli midir? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece ekonomik belge","Savaş sonrası yazılmıştır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-milli' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-9','coktan_secmeli','Sakarya Meydan Muharebesi Millî Mücadele''nin önemli savaşlarından mıdır? Yeni bir bağlama uygula.','["Hayır","I. Dünya Savaşı cephesidir","Evet","Balkan Savaşıdır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cephe' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-10','coktan_secmeli','Büyük Taarruz işgal kuvvetlerinin Anadolu''dan çıkarılmasında belirleyici olmuş mudur? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece savunma savaşı","Cumhuriyet sonrası olmuştur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cephe' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-11','coktan_secmeli','Mudanya Ateşkes Antlaşması silahlı çatışmaları büyük ölçüde sona erdirmiş midir? Yeni bir bağlama uygula.','["Hayır","Savaşı başlatmıştır","Evet","I. Dünya Savaşı öncesidir"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-antlasma' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-12','coktan_secmeli','Lozan Antlaşması yeni Türk devletinin uluslararası tanınması açısından önemli midir? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece yerel anlaşma","Osmanlı''nın kuruluş belgesidir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-antlasma' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-13','coktan_secmeli','Cumhuriyetçilik halk egemenliğiyle ilişkilidir mi? Yeni bir bağlama uygula.','["Hayır","Sadece ekonomi","Evet","Sadece eğitim"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ilke' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-14','coktan_secmeli','Laiklik din ve devlet işlerinin düzenlenmesiyle ilişkilidir mi? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece dış politika","Sadece tarım"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ilke' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-15','coktan_secmeli','Harf İnkılabı eğitim ve kültür alanıyla ilişkili midir? Yeni bir bağlama uygula.','["Hayır","Sadece askerî","Evet","Sadece dış politika"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-inkilap' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-16','coktan_secmeli','Medeni Kanun hukuk alanındaki inkılaplardan mıdır? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece eğitim","Sadece ekonomi"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-inkilap' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-17','coktan_secmeli','Terakkiperver Cumhuriyet Fırkası çok partili hayat denemelerinden biri midir? Yeni bir bağlama uygula.','["Hayır","Cumhuriyet öncesi padişahlık","Evet","Yabancı parti"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cokparti' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-18','coktan_secmeli','Serbest Cumhuriyet Fırkası da bir çok partili hayat denemesi midir? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece dernek","Sadece gazete"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cokparti' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-19','coktan_secmeli','Cumhuriyet yönetimi millî egemenlik ilkesini esas alır mı? Yeni bir bağlama uygula.','["Hayır","Saltanat esaslıdır","Evet","Sadece ekonomik modeldir"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-demokrasi' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-20','coktan_secmeli','Seçimler demokratik katılım araçlarından biri midir? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece tören","Sadece yargı"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-demokrasi' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-21','coktan_secmeli','“Yurtta sulh, cihanda sulh” barışçı dış politika anlayışıyla ilişkili midir? Yeni bir bağlama uygula.','["Hayır","Saldırganlık","Evet","İçe kapanma"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,221,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-dis-politika' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-22','coktan_secmeli','Türkiye Milletler Cemiyetine katılmış mıdır? Yeni bir bağlama uygula.','["Evet","Hayır","Hiç uluslararası kuruma katılmadı","Sadece NATO''ya kuruluşta"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,222,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-dis-politika' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-23','coktan_secmeli','Hatay Türkiye''ye Atatürk döneminin hemen ardından katılmıştır. Bu süreç Atatürk''ün dış politika hedefleriyle ilişkili midir? Yeni bir bağlama uygula.','["Hayır","Hatay hiç katılmadı","Evet","Sadece ekonomik meseleydi"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,223,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-hatay' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-24','coktan_secmeli','Hatay meselesinde diplomasi önemli rol oynamış mıdır? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece savaş","Diplomasi kullanılmamıştır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,224,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-hatay' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-25','coktan_secmeli','Atatürk 1938 yılında vefat etmiştir. Doğru mu? Yeni bir bağlama uygula.','["Hayır","1923","Evet","1950"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,225,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-olum' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-26','coktan_secmeli','Atatürk''ün ilke ve inkılapları Cumhuriyet''in gelişiminde etkili olmuş mudur? Yeni bir bağlama uygula.','["Evet","Hayır","Sadece askerî alan","Hiç etkisi yok"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,226,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-olum' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-27','coktan_secmeli','Türkiye II. Dünya Savaşı''nın büyük bölümünde savaş dışında kalmaya çalışmış mıdır? Yeni bir bağlama uygula.','["Hayır","Başından beri cephedeydi","Evet","Savaş Türkiye''de başladı"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,227,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ikinci-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-3-28','coktan_secmeli','II. Dünya Savaşı Türkiye''nin ekonomi ve dış politikasını etkilemiş midir? Yeni bir bağlama uygula.','["Evet","Hayır","Hiç etkisi yok","Sadece sporu etkiledi"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,228,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ikinci-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-1','coktan_secmeli','Mustafa Kemal Selanik''te doğmuştur. Doğru mu? En uygun açıklamayı seç.','["Hayır","Ankara''da","İstanbul''da","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,301,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cocukluk' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-2','coktan_secmeli','Askerî eğitim onun kariyerinde önemli olmuş mudur? En uygun açıklamayı seç.','["Hayır","Evet","Sadece hukuk okudu","Eğitim almamıştır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,302,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cocukluk' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-3','coktan_secmeli','Fransız İhtilali''nin milliyetçilik düşüncesi Osmanlı''yı etkilemiş midir? En uygun açıklamayı seç.','["Hayır","Sadece ekonomiyi","Hiçbir etkisi yok","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,303,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-fikir' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-4','coktan_secmeli','Mustafa Kemal farklı düşünce akımlarını takip etmiş midir? En uygun açıklamayı seç.','["Hayır","Evet","Sadece askerî emirleri","Fikir hayatı yoktur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,304,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-fikir' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-5','coktan_secmeli','Osmanlı Devleti I. Dünya Savaşı''na katılmış mıdır? En uygun açıklamayı seç.','["Hayır","Tarafsız kalmıştır","Savaş sonrası kurulmuştur","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,305,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-6','coktan_secmeli','Çanakkale Cephesi Mustafa Kemal''in askerî başarısıyla ilişkilidir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece Kafkas Cephesi","Mustafa Kemal katılmamıştır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,306,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-7','coktan_secmeli','Mondros Ateşkes Antlaşması sonrası işgaller başlamış mıdır? En uygun açıklamayı seç.','["Hayır","Lozan imzalanmıştır","Cumhuriyet kurulmuştur","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,307,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-milli' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-8','coktan_secmeli','Amasya Genelgesi Millî Mücadele açısından önemli midir? En uygun açıklamayı seç.','["Hayır","Evet","Sadece ekonomik belge","Savaş sonrası yazılmıştır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,308,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-milli' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-9','coktan_secmeli','Sakarya Meydan Muharebesi Millî Mücadele''nin önemli savaşlarından mıdır? En uygun açıklamayı seç.','["Hayır","I. Dünya Savaşı cephesidir","Balkan Savaşıdır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,309,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cephe' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-10','coktan_secmeli','Büyük Taarruz işgal kuvvetlerinin Anadolu''dan çıkarılmasında belirleyici olmuş mudur? En uygun açıklamayı seç.','["Hayır","Evet","Sadece savunma savaşı","Cumhuriyet sonrası olmuştur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,310,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cephe' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-11','coktan_secmeli','Mudanya Ateşkes Antlaşması silahlı çatışmaları büyük ölçüde sona erdirmiş midir? En uygun açıklamayı seç.','["Hayır","Savaşı başlatmıştır","I. Dünya Savaşı öncesidir","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,311,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-antlasma' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-12','coktan_secmeli','Lozan Antlaşması yeni Türk devletinin uluslararası tanınması açısından önemli midir? En uygun açıklamayı seç.','["Hayır","Evet","Sadece yerel anlaşma","Osmanlı''nın kuruluş belgesidir"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,312,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-antlasma' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-13','coktan_secmeli','Cumhuriyetçilik halk egemenliğiyle ilişkilidir mi? En uygun açıklamayı seç.','["Hayır","Sadece ekonomi","Sadece eğitim","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,313,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ilke' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-14','coktan_secmeli','Laiklik din ve devlet işlerinin düzenlenmesiyle ilişkilidir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece dış politika","Sadece tarım"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,314,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ilke' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-15','coktan_secmeli','Harf İnkılabı eğitim ve kültür alanıyla ilişkili midir? En uygun açıklamayı seç.','["Hayır","Sadece askerî","Sadece dış politika","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,315,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-inkilap' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-16','coktan_secmeli','Medeni Kanun hukuk alanındaki inkılaplardan mıdır? En uygun açıklamayı seç.','["Hayır","Evet","Sadece eğitim","Sadece ekonomi"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,316,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-inkilap' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-17','coktan_secmeli','Terakkiperver Cumhuriyet Fırkası çok partili hayat denemelerinden biri midir? En uygun açıklamayı seç.','["Hayır","Cumhuriyet öncesi padişahlık","Yabancı parti","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,317,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cokparti' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-18','coktan_secmeli','Serbest Cumhuriyet Fırkası da bir çok partili hayat denemesi midir? En uygun açıklamayı seç.','["Hayır","Evet","Sadece dernek","Sadece gazete"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,318,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-cokparti' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-19','coktan_secmeli','Cumhuriyet yönetimi millî egemenlik ilkesini esas alır mı? En uygun açıklamayı seç.','["Hayır","Saltanat esaslıdır","Sadece ekonomik modeldir","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,319,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-demokrasi' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-20','coktan_secmeli','Seçimler demokratik katılım araçlarından biri midir? En uygun açıklamayı seç.','["Hayır","Evet","Sadece tören","Sadece yargı"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,320,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-demokrasi' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-21','coktan_secmeli','“Yurtta sulh, cihanda sulh” barışçı dış politika anlayışıyla ilişkili midir? En uygun açıklamayı seç.','["Hayır","Saldırganlık","İçe kapanma","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,321,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-dis-politika' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-22','coktan_secmeli','Türkiye Milletler Cemiyetine katılmış mıdır? En uygun açıklamayı seç.','["Hayır","Evet","Hiç uluslararası kuruma katılmadı","Sadece NATO''ya kuruluşta"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,322,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-dis-politika' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-23','coktan_secmeli','Hatay Türkiye''ye Atatürk döneminin hemen ardından katılmıştır. Bu süreç Atatürk''ün dış politika hedefleriyle ilişkili midir? En uygun açıklamayı seç.','["Hayır","Hatay hiç katılmadı","Sadece ekonomik meseleydi","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,323,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-hatay' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-24','coktan_secmeli','Hatay meselesinde diplomasi önemli rol oynamış mıdır? En uygun açıklamayı seç.','["Hayır","Evet","Sadece savaş","Diplomasi kullanılmamıştır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,324,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-hatay' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-25','coktan_secmeli','Atatürk 1938 yılında vefat etmiştir. Doğru mu? En uygun açıklamayı seç.','["Hayır","1923","1950","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,325,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-olum' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-26','coktan_secmeli','Atatürk''ün ilke ve inkılapları Cumhuriyet''in gelişiminde etkili olmuş mudur? En uygun açıklamayı seç.','["Hayır","Evet","Sadece askerî alan","Hiç etkisi yok"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,326,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-olum' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-27','coktan_secmeli','Türkiye II. Dünya Savaşı''nın büyük bölümünde savaş dışında kalmaya çalışmış mıdır? En uygun açıklamayı seç.','["Hayır","Başından beri cephedeydi","Savaş Türkiye''de başladı","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,327,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ikinci-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g8i-4-28','coktan_secmeli','II. Dünya Savaşı Türkiye''nin ekonomi ve dış politikasını etkilemiş midir? En uygun açıklamayı seç.','["Hayır","Evet","Hiç etkisi yok","Sadece sporu etkiledi"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,328,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=8 AND k.konu_kodu='i8-ikinci-savas' AND (d.kod='inkilap' OR d.ad='T.C. İnkılap Tarihi ve Atatürkçülük') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

