SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-kimlik','Gruplar, Roller ve Aidiyet','Gruplar, Roller ve Aidiyet','Gruplar, Roller ve Aidiyet konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-birlikte' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-farklilik','Farklılıklar, Empati ve Birlikte Yaşam','Farklılıklar, Empati ve Birlikte Yaşam','Farklılıklar, Empati ve Birlikte Yaşam konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-birlikte' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-harita','Harita, Konum ve Coğrafi Bilgi','Harita, Konum ve Coğrafi Bilgi','Harita, Konum ve Coğrafi Bilgi konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-dunya' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-afet','Doğal Ortam, İnsan ve Afet Bilinci','Doğal Ortam, İnsan ve Afet Bilinci','Doğal Ortam, İnsan ve Afet Bilinci konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-dunya' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-anadolu','Anadolu''nun Kültürel Mirası','Anadolu''nun Kültürel Mirası','Anadolu''nun Kültürel Mirası konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-miras' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-ortak-miras','Ortak Miras ve Koruma','Ortak Miras ve Koruma','Ortak Miras ve Koruma konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-miras' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-hak','Hak, Sorumluluk ve Katılım','Hak, Sorumluluk ve Katılım','Hak, Sorumluluk ve Katılım konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-demokrasi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-demokrasi-kurum','Demokratik Kurumlar ve Karar Süreçleri','Demokratik Kurumlar ve Karar Süreçleri','Demokratik Kurumlar ve Karar Süreçleri konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-demokrasi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-uretim','Üretim, Dağıtım ve Tüketim','Üretim, Dağıtım ve Tüketim','Üretim, Dağıtım ve Tüketim konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-ekonomi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-butce','Kaynak, Bütçe ve Bilinçli Tüketim','Kaynak, Bütçe ve Bilinçli Tüketim','Kaynak, Bütçe ve Bilinçli Tüketim konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-ekonomi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-dijital','Dijital Teknolojiler ve Toplum','Dijital Teknolojiler ve Toplum','Dijital Teknolojiler ve Toplum konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-teknoloji' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'sos5-bilim','Bilimsel Gelişmeler ve Sosyal Değişim','Bilimsel Gelişmeler ve Sosyal Değişim','Bilimsel Gelişmeler ve Sosyal Değişim konusunu kanıt, harita, örnek olay ve günlük yaşamla ilişkilendirir.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='sos5-teknoloji' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-1','coktan_secmeli','Bir kişinin aynı anda aile, sınıf ve spor takımı gibi farklı gruplarda rolü olabilir mi?','["Evet","Hayır","Sadece bir grupta olur","Rol kavramı yoktur"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-kimlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-2','coktan_secmeli','Rol neyi anlatır?','["Sadece kişinin yaşını","Sadece adresi","Bir grup içindeki görev ve beklentileri","Sadece hobiyi"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-kimlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-3','coktan_secmeli','Farklılıklara saygı birlikte yaşamı destekler mi?','["Evet","Hayır","Sadece benzerlik önemlidir","Farklılıklar yasaktır"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-farklilik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-4','coktan_secmeli','Empati neye yardım eder?','["Dışlamaya","Kavga etmeye","Başkasının bakış açısını anlamaya","Sadece kendini düşünmeye"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-farklilik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-5','coktan_secmeli','Haritada ölçek ne işe yarar?','["Gerçek uzaklıkların küçültülerek gösterilmesine","Sadece renk seçmeye","Yönleri kaldırmaya","Başlığı yazmaya"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-harita' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-6','coktan_secmeli','Haritada kuzey yönü genellikle nasıl gösterilir?','["Teraziyle","Saatle","Yön işaretiyle","Müzik notasıyla"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-harita' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-7','coktan_secmeli','Afet riskini azaltmada hazırlık önemli midir?','["Evet","Hayır","Afetler etkilenmez","Sadece sonrasında önemlidir"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-afet' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-8','coktan_secmeli','Yerleşim alanı seçerken doğal riskler düşünülmeli midir?','["Hayır","Sadece manzara önemlidir","Evet","Sadece fiyat önemlidir"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-afet' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-9','coktan_secmeli','Kültürel miras geçmiş toplumlar hakkında bilgi verir mi?','["Evet","Hayır","Sadece bugünü anlatır","Sadece parayla ilgilidir"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-anadolu' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-10','coktan_secmeli','Anadolu''daki tarihî yapılar korunmalı mıdır?','["Hayır","Yıkılmalı","Evet","Üzerine yazılmalı"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-anadolu' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-11','coktan_secmeli','Ortak miras sadece tek bir kişinin malı mıdır?','["Hayır","Evet","Sadece turistlerindir","Sadece müzelerindir"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-ortak-miras' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-12','coktan_secmeli','Müzeler mirası korumaya ve tanıtmaya yardım eder mi?','["Hayır","Sadece satış yapar","Evet","Sadece eğlence yeridir"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-ortak-miras' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-13','coktan_secmeli','Haklarla sorumluluklar arasında ilişki var mıdır?','["Evet","Hayır","Sadece hak vardır","Sadece sorumluluk vardır"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-14','coktan_secmeli','Kararlara görüş bildirerek katılmak demokratik davranış mıdır?','["Hayır","Sadece yetişkinler yapabilir","Evet","Katılım yasaktır"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-15','coktan_secmeli','Oylama ortak karar yöntemlerinden biri olabilir mi?','["Evet","Hayır","Sadece oyunlarda","Sadece evde"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-demokrasi-kurum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-16','coktan_secmeli','Demokraside farklı görüşlerin ifade edilmesi önemli midir?','["Hayır","Tek görüş olmalı","Evet","Farklı görüş yasaktır"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-demokrasi-kurum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-17','coktan_secmeli','Üretim ne demektir?','["Mal veya hizmet ortaya koymak","Sadece tüketmek","Sadece satın almak","Sadece taşımak"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-uretim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-18','coktan_secmeli','Dağıtım neyi sağlar?','["Ürünü yok etmeyi","Sadece reklamı","Ürünlerin üreticiden tüketiciye ulaşmasını","Sadece fiyatı"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-uretim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-19','coktan_secmeli','Bütçe neyi planlar?','["Gelir ve giderleri","Hava durumunu","Harita yönlerini","Ders notlarını"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-butce' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-20','coktan_secmeli','Bilinçli tüketici ne yapar?','["Rastgele alır","Etiketi okumaz","İhtiyaç, kalite ve bütçeyi değerlendirir.","Fiyatı önemsemez"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-butce' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-21','coktan_secmeli','Dijital ayak izi neyi anlatır?','["Çevrim içi etkinliklerin bıraktığı izleri","Ayakkabı numarasını","Harita ölçeğini","Kütleyi"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-22','coktan_secmeli','Kişisel bilgiler çevrim içi ortamda korunmalı mıdır?','["Hayır","Herkesle paylaşılmalı","Evet","Şifre açık yazılmalı"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-23','coktan_secmeli','Bilimsel gelişmeler toplum yaşamını değiştirebilir mi?','["Evet","Hayır","Sadece laboratuvarı etkiler","Toplumla ilgisiz"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-1-24','coktan_secmeli','Yeni teknolojilerin yararları yanında riskleri de değerlendirilmeli midir?','["Hayır","Teknoloji her zaman risksizdir","Evet","Sadece fiyat önemli"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-1','coktan_secmeli','Bir kişinin aynı anda aile, sınıf ve spor takımı gibi farklı gruplarda rolü olabilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece bir grupta olur","Rol kavramı yoktur"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-kimlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-2','coktan_secmeli','Rol neyi anlatır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Sadece kişinin yaşını","Sadece adresi","Sadece hobiyi","Bir grup içindeki görev ve beklentileri"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-kimlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-3','coktan_secmeli','Farklılıklara saygı birlikte yaşamı destekler mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece benzerlik önemlidir","Farklılıklar yasaktır"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-farklilik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-4','coktan_secmeli','Empati neye yardım eder? Günlük yaşam veya toplumsal bir örneğe uygula.','["Dışlamaya","Kavga etmeye","Sadece kendini düşünmeye","Başkasının bakış açısını anlamaya"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-farklilik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-5','coktan_secmeli','Haritada ölçek ne işe yarar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Sadece renk seçmeye","Gerçek uzaklıkların küçültülerek gösterilmesine","Yönleri kaldırmaya","Başlığı yazmaya"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-harita' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-6','coktan_secmeli','Haritada kuzey yönü genellikle nasıl gösterilir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Teraziyle","Saatle","Müzik notasıyla","Yön işaretiyle"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-harita' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-7','coktan_secmeli','Afet riskini azaltmada hazırlık önemli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Afetler etkilenmez","Sadece sonrasında önemlidir"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-afet' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-8','coktan_secmeli','Yerleşim alanı seçerken doğal riskler düşünülmeli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece manzara önemlidir","Sadece fiyat önemlidir","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-afet' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-9','coktan_secmeli','Kültürel miras geçmiş toplumlar hakkında bilgi verir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece bugünü anlatır","Sadece parayla ilgilidir"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-anadolu' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-10','coktan_secmeli','Anadolu''daki tarihî yapılar korunmalı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Yıkılmalı","Üzerine yazılmalı","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-anadolu' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-11','coktan_secmeli','Ortak miras sadece tek bir kişinin malı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece turistlerindir","Sadece müzelerindir"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-ortak-miras' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-12','coktan_secmeli','Müzeler mirası korumaya ve tanıtmaya yardım eder mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece satış yapar","Sadece eğlence yeridir","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-ortak-miras' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-13','coktan_secmeli','Haklarla sorumluluklar arasında ilişki var mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece hak vardır","Sadece sorumluluk vardır"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-14','coktan_secmeli','Kararlara görüş bildirerek katılmak demokratik davranış mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece yetişkinler yapabilir","Katılım yasaktır","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-15','coktan_secmeli','Oylama ortak karar yöntemlerinden biri olabilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece oyunlarda","Sadece evde"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-demokrasi-kurum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-16','coktan_secmeli','Demokraside farklı görüşlerin ifade edilmesi önemli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Tek görüş olmalı","Farklı görüş yasaktır","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-demokrasi-kurum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-17','coktan_secmeli','Üretim ne demektir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Sadece tüketmek","Mal veya hizmet ortaya koymak","Sadece satın almak","Sadece taşımak"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-uretim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-18','coktan_secmeli','Dağıtım neyi sağlar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Ürünü yok etmeyi","Sadece reklamı","Sadece fiyatı","Ürünlerin üreticiden tüketiciye ulaşmasını"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-uretim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-19','coktan_secmeli','Bütçe neyi planlar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hava durumunu","Gelir ve giderleri","Harita yönlerini","Ders notlarını"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-butce' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-20','coktan_secmeli','Bilinçli tüketici ne yapar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Rastgele alır","Etiketi okumaz","Fiyatı önemsemez","İhtiyaç, kalite ve bütçeyi değerlendirir."]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-butce' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-21','coktan_secmeli','Dijital ayak izi neyi anlatır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Ayakkabı numarasını","Çevrim içi etkinliklerin bıraktığı izleri","Harita ölçeğini","Kütleyi"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,121,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-22','coktan_secmeli','Kişisel bilgiler çevrim içi ortamda korunmalı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Herkesle paylaşılmalı","Şifre açık yazılmalı","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,122,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-23','coktan_secmeli','Bilimsel gelişmeler toplum yaşamını değiştirebilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece laboratuvarı etkiler","Toplumla ilgisiz"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,123,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-2-24','coktan_secmeli','Yeni teknolojilerin yararları yanında riskleri de değerlendirilmeli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Teknoloji her zaman risksizdir","Sadece fiyat önemli","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,124,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-1','coktan_secmeli','Bir kişinin aynı anda aile, sınıf ve spor takımı gibi farklı gruplarda rolü olabilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece bir grupta olur","Evet","Rol kavramı yoktur"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-kimlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-2','coktan_secmeli','Rol neyi anlatır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Bir grup içindeki görev ve beklentileri","Sadece kişinin yaşını","Sadece adresi","Sadece hobiyi"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-kimlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-3','coktan_secmeli','Farklılıklara saygı birlikte yaşamı destekler mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece benzerlik önemlidir","Evet","Farklılıklar yasaktır"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-farklilik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-4','coktan_secmeli','Empati neye yardım eder? Günlük yaşam veya toplumsal bir örneğe uygula.','["Başkasının bakış açısını anlamaya","Dışlamaya","Kavga etmeye","Sadece kendini düşünmeye"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-farklilik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-5','coktan_secmeli','Haritada ölçek ne işe yarar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Sadece renk seçmeye","Yönleri kaldırmaya","Gerçek uzaklıkların küçültülerek gösterilmesine","Başlığı yazmaya"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-harita' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-6','coktan_secmeli','Haritada kuzey yönü genellikle nasıl gösterilir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Yön işaretiyle","Teraziyle","Saatle","Müzik notasıyla"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-harita' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-7','coktan_secmeli','Afet riskini azaltmada hazırlık önemli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Afetler etkilenmez","Evet","Sadece sonrasında önemlidir"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-afet' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-8','coktan_secmeli','Yerleşim alanı seçerken doğal riskler düşünülmeli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece manzara önemlidir","Sadece fiyat önemlidir"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-afet' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-9','coktan_secmeli','Kültürel miras geçmiş toplumlar hakkında bilgi verir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece bugünü anlatır","Evet","Sadece parayla ilgilidir"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-anadolu' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-10','coktan_secmeli','Anadolu''daki tarihî yapılar korunmalı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Hayır","Yıkılmalı","Üzerine yazılmalı"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-anadolu' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-11','coktan_secmeli','Ortak miras sadece tek bir kişinin malı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Sadece turistlerindir","Hayır","Sadece müzelerindir"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-ortak-miras' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-12','coktan_secmeli','Müzeler mirası korumaya ve tanıtmaya yardım eder mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece satış yapar","Sadece eğlence yeridir"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-ortak-miras' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-13','coktan_secmeli','Haklarla sorumluluklar arasında ilişki var mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece hak vardır","Evet","Sadece sorumluluk vardır"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-14','coktan_secmeli','Kararlara görüş bildirerek katılmak demokratik davranış mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece yetişkinler yapabilir","Katılım yasaktır"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-15','coktan_secmeli','Oylama ortak karar yöntemlerinden biri olabilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece oyunlarda","Evet","Sadece evde"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-demokrasi-kurum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-16','coktan_secmeli','Demokraside farklı görüşlerin ifade edilmesi önemli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Hayır","Tek görüş olmalı","Farklı görüş yasaktır"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-demokrasi-kurum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-17','coktan_secmeli','Üretim ne demektir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Sadece tüketmek","Sadece satın almak","Mal veya hizmet ortaya koymak","Sadece taşımak"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-uretim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-18','coktan_secmeli','Dağıtım neyi sağlar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Ürünlerin üreticiden tüketiciye ulaşmasını","Ürünü yok etmeyi","Sadece reklamı","Sadece fiyatı"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-uretim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-19','coktan_secmeli','Bütçe neyi planlar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hava durumunu","Harita yönlerini","Gelir ve giderleri","Ders notlarını"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-butce' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-20','coktan_secmeli','Bilinçli tüketici ne yapar? Günlük yaşam veya toplumsal bir örneğe uygula.','["İhtiyaç, kalite ve bütçeyi değerlendirir.","Rastgele alır","Etiketi okumaz","Fiyatı önemsemez"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-butce' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-21','coktan_secmeli','Dijital ayak izi neyi anlatır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Ayakkabı numarasını","Harita ölçeğini","Çevrim içi etkinliklerin bıraktığı izleri","Kütleyi"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,221,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-22','coktan_secmeli','Kişisel bilgiler çevrim içi ortamda korunmalı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Hayır","Herkesle paylaşılmalı","Şifre açık yazılmalı"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,222,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-23','coktan_secmeli','Bilimsel gelişmeler toplum yaşamını değiştirebilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece laboratuvarı etkiler","Evet","Toplumla ilgisiz"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,223,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-3-24','coktan_secmeli','Yeni teknolojilerin yararları yanında riskleri de değerlendirilmeli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Hayır","Teknoloji her zaman risksizdir","Sadece fiyat önemli"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,224,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-1','coktan_secmeli','Bir kişinin aynı anda aile, sınıf ve spor takımı gibi farklı gruplarda rolü olabilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece bir grupta olur","Rol kavramı yoktur","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,301,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-kimlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-2','coktan_secmeli','Rol neyi anlatır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Sadece kişinin yaşını","Bir grup içindeki görev ve beklentileri","Sadece adresi","Sadece hobiyi"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,302,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-kimlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-3','coktan_secmeli','Farklılıklara saygı birlikte yaşamı destekler mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece benzerlik önemlidir","Farklılıklar yasaktır","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,303,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-farklilik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-4','coktan_secmeli','Empati neye yardım eder? Günlük yaşam veya toplumsal bir örneğe uygula.','["Dışlamaya","Başkasının bakış açısını anlamaya","Kavga etmeye","Sadece kendini düşünmeye"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,304,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-farklilik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-5','coktan_secmeli','Haritada ölçek ne işe yarar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Sadece renk seçmeye","Yönleri kaldırmaya","Başlığı yazmaya","Gerçek uzaklıkların küçültülerek gösterilmesine"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,305,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-harita' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-6','coktan_secmeli','Haritada kuzey yönü genellikle nasıl gösterilir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Teraziyle","Yön işaretiyle","Saatle","Müzik notasıyla"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,306,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-harita' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-7','coktan_secmeli','Afet riskini azaltmada hazırlık önemli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Afetler etkilenmez","Sadece sonrasında önemlidir","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,307,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-afet' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-8','coktan_secmeli','Yerleşim alanı seçerken doğal riskler düşünülmeli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece manzara önemlidir","Sadece fiyat önemlidir"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,308,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-afet' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-9','coktan_secmeli','Kültürel miras geçmiş toplumlar hakkında bilgi verir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece bugünü anlatır","Sadece parayla ilgilidir","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,309,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-anadolu' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-10','coktan_secmeli','Anadolu''daki tarihî yapılar korunmalı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Yıkılmalı","Üzerine yazılmalı"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,310,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-anadolu' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-11','coktan_secmeli','Ortak miras sadece tek bir kişinin malı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Evet","Sadece turistlerindir","Sadece müzelerindir","Hayır"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,311,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-ortak-miras' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-12','coktan_secmeli','Müzeler mirası korumaya ve tanıtmaya yardım eder mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece satış yapar","Sadece eğlence yeridir"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,312,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-ortak-miras' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-13','coktan_secmeli','Haklarla sorumluluklar arasında ilişki var mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece hak vardır","Sadece sorumluluk vardır","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,313,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-14','coktan_secmeli','Kararlara görüş bildirerek katılmak demokratik davranış mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece yetişkinler yapabilir","Katılım yasaktır"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,314,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-15','coktan_secmeli','Oylama ortak karar yöntemlerinden biri olabilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece oyunlarda","Sadece evde","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,315,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-demokrasi-kurum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-16','coktan_secmeli','Demokraside farklı görüşlerin ifade edilmesi önemli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Tek görüş olmalı","Farklı görüş yasaktır"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,316,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-demokrasi-kurum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-17','coktan_secmeli','Üretim ne demektir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Sadece tüketmek","Sadece satın almak","Sadece taşımak","Mal veya hizmet ortaya koymak"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,317,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-uretim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-18','coktan_secmeli','Dağıtım neyi sağlar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Ürünü yok etmeyi","Ürünlerin üreticiden tüketiciye ulaşmasını","Sadece reklamı","Sadece fiyatı"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,318,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-uretim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-19','coktan_secmeli','Bütçe neyi planlar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hava durumunu","Harita yönlerini","Ders notlarını","Gelir ve giderleri"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,319,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-butce' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-20','coktan_secmeli','Bilinçli tüketici ne yapar? Günlük yaşam veya toplumsal bir örneğe uygula.','["Rastgele alır","İhtiyaç, kalite ve bütçeyi değerlendirir.","Etiketi okumaz","Fiyatı önemsemez"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,320,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-butce' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-21','coktan_secmeli','Dijital ayak izi neyi anlatır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Ayakkabı numarasını","Harita ölçeğini","Kütleyi","Çevrim içi etkinliklerin bıraktığı izleri"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,321,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-22','coktan_secmeli','Kişisel bilgiler çevrim içi ortamda korunmalı mıdır? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Herkesle paylaşılmalı","Şifre açık yazılmalı"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,322,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-23','coktan_secmeli','Bilimsel gelişmeler toplum yaşamını değiştirebilir mi? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Sadece laboratuvarı etkiler","Toplumla ilgisiz","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,323,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5s-4-24','coktan_secmeli','Yeni teknolojilerin yararları yanında riskleri de değerlendirilmeli midir? Günlük yaşam veya toplumsal bir örneğe uygula.','["Hayır","Evet","Teknoloji her zaman risksizdir","Sadece fiyat önemli"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,324,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='sos5-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

