SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-dijital-sistem','Dijital Sistemler ve Günlük Yaşam','Dijital Sistemler ve Günlük Yaşam','Dijital Sistemler ve Günlük Yaşam konusunda güvenli ve üretken dijital beceriler geliştirir.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-hayat' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-veri','Veri, Bilgi ve Dosyalar','Veri, Bilgi ve Dosyalar','Veri, Bilgi ve Dosyalar konusunda güvenli ve üretken dijital beceriler geliştirir.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-hayat' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-tasarim','Dijital Ürün Tasarım Süreci','Dijital Ürün Tasarım Süreci','Dijital Ürün Tasarım Süreci konusunda güvenli ve üretken dijital beceriler geliştirir.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-urun' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-sunum','Görsel Sunum ve İçerik Üretimi','Görsel Sunum ve İçerik Üretimi','Görsel Sunum ve İçerik Üretimi konusunda güvenli ve üretken dijital beceriler geliştirir.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-urun' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-ag-temel','Bilgisayar Ağlarının Temelleri','Bilgisayar Ağlarının Temelleri','Bilgisayar Ağlarının Temelleri konusunda güvenli ve üretken dijital beceriler geliştirir.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-ag' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-internet','İnternet ve İletişim','İnternet ve İletişim','İnternet ve İletişim konusunda güvenli ve üretken dijital beceriler geliştirir.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-ag' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-etik-konu','Bilişim Etiği ve Dijital Vatandaşlık','Bilişim Etiği ve Dijital Vatandaşlık','Bilişim Etiği ve Dijital Vatandaşlık konusunda güvenli ve üretken dijital beceriler geliştirir.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-etik' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-siber','Şifre, Gizlilik ve Siber Güvenlik','Şifre, Gizlilik ve Siber Güvenlik','Şifre, Gizlilik ve Siber Güvenlik konusunda güvenli ve üretken dijital beceriler geliştirir.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-etik' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-ai-temel','Yapay Zekâya Giriş','Yapay Zekâya Giriş','Yapay Zekâya Giriş konusunda güvenli ve üretken dijital beceriler geliştirir.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-ai' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-ai-sorumlu','Yapay Zekâyı Sorumlu Kullanma','Yapay Zekâyı Sorumlu Kullanma','Yapay Zekâyı Sorumlu Kullanma konusunda güvenli ve üretken dijital beceriler geliştirir.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-ai' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-algoritma','Algoritma ve Akış','Algoritma ve Akış','Algoritma ve Akış konusunda güvenli ve üretken dijital beceriler geliştirir.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-kod' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'bt5-program','Blok Tabanlı Programlama','Blok Tabanlı Programlama','Blok Tabanlı Programlama konusunda güvenli ve üretken dijital beceriler geliştirir.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='bt5-kod' WHERE d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-1','coktan_secmeli','Bilgisayarın fiziksel parçalarına ne denir?','["Donanım","Yazılım","Dosya","Ağ"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-dijital-sistem' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-2','coktan_secmeli','Uygulama ve işletim sistemi neye örnektir?','["Donanım","Kablo","Yazılım","Klavye"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-dijital-sistem' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-3','coktan_secmeli','Dosyaları klasörlerde düzenlemek ne sağlar?','["Düzenli saklama ve bulmayı","Veriyi silmeyi","İnterneti kapatmayı","Şifreyi kaldırmayı"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-veri' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-4','coktan_secmeli','Dosya uzantısı ne hakkında ipucu verebilir?','["Kullanıcının yaşı","Bilgisayarın ağırlığı","Dosya türü hakkında","İnternet hızı"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-veri' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-5','coktan_secmeli','Dijital ürün tasarımında ilk adımlardan biri nedir?','["İhtiyacı veya problemi belirlemek","Rastgele renk seçmek","Ürünü bitmiş saymak","Dosyayı silmek"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-tasarim' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-6','coktan_secmeli','Taslak/prototip neye yardım eder?','["Şifreyi paylaşmaya","Ağı kapatmaya","Fikri denemeye ve geliştirmeye","Veriyi yok etmeye"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-tasarim' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-7','coktan_secmeli','Sunumda okunabilir yazı kullanmak önemli midir?','["Evet","Hayır","Sadece renk önemlidir","Metin görünmemelidir"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-sunum' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-8','coktan_secmeli','Telif ve kaynak bilgisi dijital içerikte önemli midir?','["Hayır","Her içerik serbesttir","Evet","Kaynak gizlenmelidir"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-sunum' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-9','coktan_secmeli','Bilgisayar ağı ne sağlar?','["Cihazların veri ve kaynak paylaşmasını","Sadece şarj olmasını","Ekranı büyütmeyi","Dosyayı kağıda çevirmeyi"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ag-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-10','coktan_secmeli','Wi-Fi kablosuz ağ bağlantısı sağlayabilir mi?','["Hayır","Sadece yazıcıdır","Evet","Sadece depolamadır"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ag-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-11','coktan_secmeli','İnternet bir bilgisayar ağı ağı olarak düşünülebilir mi?','["Evet","Hayır","Tek bir bilgisayardır","Sadece uygulamadır"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-internet' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-12','coktan_secmeli','E-posta dijital iletişim aracı mıdır?','["Hayır","Sadece dosya türüdür","Evet","Donanımdır"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-internet' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-13','coktan_secmeli','Başkasının fotoğrafını izinsiz paylaşmak doğru mudur?','["Hayır","Evet her zaman","Sadece arkadaşsa","İnternette izin gerekmez"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-etik-konu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-14','coktan_secmeli','Dijital ortamda saygılı dil gerekli midir?','["Hayır","Kurallar geçersizdir","Evet","Sadece öğretmene"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-etik-konu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-15','coktan_secmeli','Güçlü şifre nasıl olmalıdır?','["Tahmini zor ve kişiye özel","Ad-soyad kadar basit","123456","Herkesle aynı"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-siber' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-16','coktan_secmeli','Şüpheli bağlantıya tıklamadan önce ne yapılmalıdır?','["Hemen açılmalıdır.","Şifre verilmelidir.","Kaynak ve güvenilirlik kontrol edilmelidir.","Arkadaşlara gönderilmelidir."]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-siber' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-17','coktan_secmeli','Yapay zekâ ne yapabilir?','["Verilerden örüntü öğrenerek bazı görevleri gerçekleştirebilir.","Her zaman insan gibi düşünür","Hatasızdır","İnternetsiz hiçbir şey değildir"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-18','coktan_secmeli','Yapay zekâ çıktıları kontrol edilmeli midir?','["Hayır","Her zaman doğrudur","Evet","Kaynak gerekmez"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-19','coktan_secmeli','Yapay zekâya kişisel sırlar yazmak güvenli midir?','["Genellikle hayır","Evet her zaman","Şifre de yazılmalı","Adres paylaşılmalı"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-sorumlu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-20','coktan_secmeli','AI ile üretilen bilgi kaynakla doğrulanmalı mıdır?','["Hayır","AI yanılmaz","Evet","Sadece uzun cevapsa"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-sorumlu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-21','coktan_secmeli','Algoritma neyi ifade eder?','["Bir işi çözmek için sıralı adımları","Sadece kod rengini","Bilgisayar markasını","Dosya uzantısını"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-algoritma' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-22','coktan_secmeli','Adımların sırası sonucu etkileyebilir mi?','["Hayır","Algoritmada sıra yoktur","Evet","Sadece görsel etkiler"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-algoritma' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-23','coktan_secmeli','Döngü ne işe yarar?','["Tekrarlanan işlemleri düzenlemeye","Şifreyi silmeye","Ekranı kapatmaya","Dosyayı yazdırmaya"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-program' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-1-24','coktan_secmeli','Koşul yapısı neyi sağlar?','["Her zaman aynı işlemi","Sadece ses çıkarmayı","Bir duruma göre farklı işlem seçmeyi","Ağı kapatmayı"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-program' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-1','coktan_secmeli','Bilgisayarın fiziksel parçalarına ne denir? Dijital bir örnek üzerinden değerlendir.','["Yazılım","Donanım","Dosya","Ağ"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-dijital-sistem' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-2','coktan_secmeli','Uygulama ve işletim sistemi neye örnektir? Dijital bir örnek üzerinden değerlendir.','["Donanım","Kablo","Klavye","Yazılım"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-dijital-sistem' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-3','coktan_secmeli','Dosyaları klasörlerde düzenlemek ne sağlar? Dijital bir örnek üzerinden değerlendir.','["Veriyi silmeyi","Düzenli saklama ve bulmayı","İnterneti kapatmayı","Şifreyi kaldırmayı"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-veri' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-4','coktan_secmeli','Dosya uzantısı ne hakkında ipucu verebilir? Dijital bir örnek üzerinden değerlendir.','["Kullanıcının yaşı","Bilgisayarın ağırlığı","İnternet hızı","Dosya türü hakkında"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-veri' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-5','coktan_secmeli','Dijital ürün tasarımında ilk adımlardan biri nedir? Dijital bir örnek üzerinden değerlendir.','["Rastgele renk seçmek","İhtiyacı veya problemi belirlemek","Ürünü bitmiş saymak","Dosyayı silmek"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-tasarim' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-6','coktan_secmeli','Taslak/prototip neye yardım eder? Dijital bir örnek üzerinden değerlendir.','["Şifreyi paylaşmaya","Ağı kapatmaya","Veriyi yok etmeye","Fikri denemeye ve geliştirmeye"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-tasarim' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-7','coktan_secmeli','Sunumda okunabilir yazı kullanmak önemli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","Sadece renk önemlidir","Metin görünmemelidir"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-sunum' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-8','coktan_secmeli','Telif ve kaynak bilgisi dijital içerikte önemli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Her içerik serbesttir","Kaynak gizlenmelidir","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-sunum' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-9','coktan_secmeli','Bilgisayar ağı ne sağlar? Dijital bir örnek üzerinden değerlendir.','["Sadece şarj olmasını","Cihazların veri ve kaynak paylaşmasını","Ekranı büyütmeyi","Dosyayı kağıda çevirmeyi"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ag-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-10','coktan_secmeli','Wi-Fi kablosuz ağ bağlantısı sağlayabilir mi? Dijital bir örnek üzerinden değerlendir.','["Hayır","Sadece yazıcıdır","Sadece depolamadır","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ag-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-11','coktan_secmeli','İnternet bir bilgisayar ağı ağı olarak düşünülebilir mi? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","Tek bir bilgisayardır","Sadece uygulamadır"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-internet' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-12','coktan_secmeli','E-posta dijital iletişim aracı mıdır? Dijital bir örnek üzerinden değerlendir.','["Hayır","Sadece dosya türüdür","Donanımdır","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-internet' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-13','coktan_secmeli','Başkasının fotoğrafını izinsiz paylaşmak doğru mudur? Dijital bir örnek üzerinden değerlendir.','["Evet her zaman","Hayır","Sadece arkadaşsa","İnternette izin gerekmez"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-etik-konu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-14','coktan_secmeli','Dijital ortamda saygılı dil gerekli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Kurallar geçersizdir","Sadece öğretmene","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-etik-konu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-15','coktan_secmeli','Güçlü şifre nasıl olmalıdır? Dijital bir örnek üzerinden değerlendir.','["Ad-soyad kadar basit","Tahmini zor ve kişiye özel","123456","Herkesle aynı"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-siber' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-16','coktan_secmeli','Şüpheli bağlantıya tıklamadan önce ne yapılmalıdır? Dijital bir örnek üzerinden değerlendir.','["Hemen açılmalıdır.","Şifre verilmelidir.","Arkadaşlara gönderilmelidir.","Kaynak ve güvenilirlik kontrol edilmelidir."]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-siber' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-17','coktan_secmeli','Yapay zekâ ne yapabilir? Dijital bir örnek üzerinden değerlendir.','["Her zaman insan gibi düşünür","Verilerden örüntü öğrenerek bazı görevleri gerçekleştirebilir.","Hatasızdır","İnternetsiz hiçbir şey değildir"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-18','coktan_secmeli','Yapay zekâ çıktıları kontrol edilmeli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Her zaman doğrudur","Kaynak gerekmez","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-19','coktan_secmeli','Yapay zekâya kişisel sırlar yazmak güvenli midir? Dijital bir örnek üzerinden değerlendir.','["Evet her zaman","Genellikle hayır","Şifre de yazılmalı","Adres paylaşılmalı"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-sorumlu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-20','coktan_secmeli','AI ile üretilen bilgi kaynakla doğrulanmalı mıdır? Dijital bir örnek üzerinden değerlendir.','["Hayır","AI yanılmaz","Sadece uzun cevapsa","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-sorumlu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-21','coktan_secmeli','Algoritma neyi ifade eder? Dijital bir örnek üzerinden değerlendir.','["Sadece kod rengini","Bir işi çözmek için sıralı adımları","Bilgisayar markasını","Dosya uzantısını"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,121,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-algoritma' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-22','coktan_secmeli','Adımların sırası sonucu etkileyebilir mi? Dijital bir örnek üzerinden değerlendir.','["Hayır","Algoritmada sıra yoktur","Sadece görsel etkiler","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,122,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-algoritma' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-23','coktan_secmeli','Döngü ne işe yarar? Dijital bir örnek üzerinden değerlendir.','["Şifreyi silmeye","Tekrarlanan işlemleri düzenlemeye","Ekranı kapatmaya","Dosyayı yazdırmaya"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,123,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-program' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-2-24','coktan_secmeli','Koşul yapısı neyi sağlar? Dijital bir örnek üzerinden değerlendir.','["Her zaman aynı işlemi","Sadece ses çıkarmayı","Ağı kapatmayı","Bir duruma göre farklı işlem seçmeyi"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',1,124,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-program' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-1','coktan_secmeli','Bilgisayarın fiziksel parçalarına ne denir? Dijital bir örnek üzerinden değerlendir.','["Yazılım","Dosya","Donanım","Ağ"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-dijital-sistem' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-2','coktan_secmeli','Uygulama ve işletim sistemi neye örnektir? Dijital bir örnek üzerinden değerlendir.','["Yazılım","Donanım","Kablo","Klavye"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-dijital-sistem' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-3','coktan_secmeli','Dosyaları klasörlerde düzenlemek ne sağlar? Dijital bir örnek üzerinden değerlendir.','["Veriyi silmeyi","İnterneti kapatmayı","Düzenli saklama ve bulmayı","Şifreyi kaldırmayı"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-veri' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-4','coktan_secmeli','Dosya uzantısı ne hakkında ipucu verebilir? Dijital bir örnek üzerinden değerlendir.','["Dosya türü hakkında","Kullanıcının yaşı","Bilgisayarın ağırlığı","İnternet hızı"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-veri' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-5','coktan_secmeli','Dijital ürün tasarımında ilk adımlardan biri nedir? Dijital bir örnek üzerinden değerlendir.','["Rastgele renk seçmek","Ürünü bitmiş saymak","İhtiyacı veya problemi belirlemek","Dosyayı silmek"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-tasarim' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-6','coktan_secmeli','Taslak/prototip neye yardım eder? Dijital bir örnek üzerinden değerlendir.','["Fikri denemeye ve geliştirmeye","Şifreyi paylaşmaya","Ağı kapatmaya","Veriyi yok etmeye"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-tasarim' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-7','coktan_secmeli','Sunumda okunabilir yazı kullanmak önemli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Sadece renk önemlidir","Evet","Metin görünmemelidir"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-sunum' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-8','coktan_secmeli','Telif ve kaynak bilgisi dijital içerikte önemli midir? Dijital bir örnek üzerinden değerlendir.','["Evet","Hayır","Her içerik serbesttir","Kaynak gizlenmelidir"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-sunum' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-9','coktan_secmeli','Bilgisayar ağı ne sağlar? Dijital bir örnek üzerinden değerlendir.','["Sadece şarj olmasını","Ekranı büyütmeyi","Cihazların veri ve kaynak paylaşmasını","Dosyayı kağıda çevirmeyi"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ag-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-10','coktan_secmeli','Wi-Fi kablosuz ağ bağlantısı sağlayabilir mi? Dijital bir örnek üzerinden değerlendir.','["Evet","Hayır","Sadece yazıcıdır","Sadece depolamadır"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ag-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-11','coktan_secmeli','İnternet bir bilgisayar ağı ağı olarak düşünülebilir mi? Dijital bir örnek üzerinden değerlendir.','["Hayır","Tek bir bilgisayardır","Evet","Sadece uygulamadır"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-internet' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-12','coktan_secmeli','E-posta dijital iletişim aracı mıdır? Dijital bir örnek üzerinden değerlendir.','["Evet","Hayır","Sadece dosya türüdür","Donanımdır"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-internet' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-13','coktan_secmeli','Başkasının fotoğrafını izinsiz paylaşmak doğru mudur? Dijital bir örnek üzerinden değerlendir.','["Evet her zaman","Sadece arkadaşsa","Hayır","İnternette izin gerekmez"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-etik-konu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-14','coktan_secmeli','Dijital ortamda saygılı dil gerekli midir? Dijital bir örnek üzerinden değerlendir.','["Evet","Hayır","Kurallar geçersizdir","Sadece öğretmene"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-etik-konu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-15','coktan_secmeli','Güçlü şifre nasıl olmalıdır? Dijital bir örnek üzerinden değerlendir.','["Ad-soyad kadar basit","123456","Tahmini zor ve kişiye özel","Herkesle aynı"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-siber' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-16','coktan_secmeli','Şüpheli bağlantıya tıklamadan önce ne yapılmalıdır? Dijital bir örnek üzerinden değerlendir.','["Kaynak ve güvenilirlik kontrol edilmelidir.","Hemen açılmalıdır.","Şifre verilmelidir.","Arkadaşlara gönderilmelidir."]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-siber' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-17','coktan_secmeli','Yapay zekâ ne yapabilir? Dijital bir örnek üzerinden değerlendir.','["Her zaman insan gibi düşünür","Hatasızdır","Verilerden örüntü öğrenerek bazı görevleri gerçekleştirebilir.","İnternetsiz hiçbir şey değildir"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-18','coktan_secmeli','Yapay zekâ çıktıları kontrol edilmeli midir? Dijital bir örnek üzerinden değerlendir.','["Evet","Hayır","Her zaman doğrudur","Kaynak gerekmez"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-19','coktan_secmeli','Yapay zekâya kişisel sırlar yazmak güvenli midir? Dijital bir örnek üzerinden değerlendir.','["Evet her zaman","Şifre de yazılmalı","Genellikle hayır","Adres paylaşılmalı"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-sorumlu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-20','coktan_secmeli','AI ile üretilen bilgi kaynakla doğrulanmalı mıdır? Dijital bir örnek üzerinden değerlendir.','["Evet","Hayır","AI yanılmaz","Sadece uzun cevapsa"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-sorumlu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-21','coktan_secmeli','Algoritma neyi ifade eder? Dijital bir örnek üzerinden değerlendir.','["Sadece kod rengini","Bilgisayar markasını","Bir işi çözmek için sıralı adımları","Dosya uzantısını"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,221,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-algoritma' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-22','coktan_secmeli','Adımların sırası sonucu etkileyebilir mi? Dijital bir örnek üzerinden değerlendir.','["Evet","Hayır","Algoritmada sıra yoktur","Sadece görsel etkiler"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,222,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-algoritma' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-23','coktan_secmeli','Döngü ne işe yarar? Dijital bir örnek üzerinden değerlendir.','["Şifreyi silmeye","Ekranı kapatmaya","Tekrarlanan işlemleri düzenlemeye","Dosyayı yazdırmaya"]',2,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,223,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-program' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-3-24','coktan_secmeli','Koşul yapısı neyi sağlar? Dijital bir örnek üzerinden değerlendir.','["Bir duruma göre farklı işlem seçmeyi","Her zaman aynı işlemi","Sadece ses çıkarmayı","Ağı kapatmayı"]',0,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,224,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-program' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-1','coktan_secmeli','Bilgisayarın fiziksel parçalarına ne denir? Dijital bir örnek üzerinden değerlendir.','["Yazılım","Dosya","Ağ","Donanım"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,301,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-dijital-sistem' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-2','coktan_secmeli','Uygulama ve işletim sistemi neye örnektir? Dijital bir örnek üzerinden değerlendir.','["Donanım","Yazılım","Kablo","Klavye"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,302,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-dijital-sistem' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-3','coktan_secmeli','Dosyaları klasörlerde düzenlemek ne sağlar? Dijital bir örnek üzerinden değerlendir.','["Veriyi silmeyi","İnterneti kapatmayı","Şifreyi kaldırmayı","Düzenli saklama ve bulmayı"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,303,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-veri' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-4','coktan_secmeli','Dosya uzantısı ne hakkında ipucu verebilir? Dijital bir örnek üzerinden değerlendir.','["Kullanıcının yaşı","Dosya türü hakkında","Bilgisayarın ağırlığı","İnternet hızı"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,304,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-veri' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-5','coktan_secmeli','Dijital ürün tasarımında ilk adımlardan biri nedir? Dijital bir örnek üzerinden değerlendir.','["Rastgele renk seçmek","Ürünü bitmiş saymak","Dosyayı silmek","İhtiyacı veya problemi belirlemek"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,305,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-tasarim' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-6','coktan_secmeli','Taslak/prototip neye yardım eder? Dijital bir örnek üzerinden değerlendir.','["Şifreyi paylaşmaya","Fikri denemeye ve geliştirmeye","Ağı kapatmaya","Veriyi yok etmeye"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,306,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-tasarim' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-7','coktan_secmeli','Sunumda okunabilir yazı kullanmak önemli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Sadece renk önemlidir","Metin görünmemelidir","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,307,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-sunum' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-8','coktan_secmeli','Telif ve kaynak bilgisi dijital içerikte önemli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","Her içerik serbesttir","Kaynak gizlenmelidir"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,308,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-sunum' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-9','coktan_secmeli','Bilgisayar ağı ne sağlar? Dijital bir örnek üzerinden değerlendir.','["Sadece şarj olmasını","Ekranı büyütmeyi","Dosyayı kağıda çevirmeyi","Cihazların veri ve kaynak paylaşmasını"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,309,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ag-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-10','coktan_secmeli','Wi-Fi kablosuz ağ bağlantısı sağlayabilir mi? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","Sadece yazıcıdır","Sadece depolamadır"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,310,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ag-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-11','coktan_secmeli','İnternet bir bilgisayar ağı ağı olarak düşünülebilir mi? Dijital bir örnek üzerinden değerlendir.','["Hayır","Tek bir bilgisayardır","Sadece uygulamadır","Evet"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,311,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-internet' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-12','coktan_secmeli','E-posta dijital iletişim aracı mıdır? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","Sadece dosya türüdür","Donanımdır"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,312,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-internet' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-13','coktan_secmeli','Başkasının fotoğrafını izinsiz paylaşmak doğru mudur? Dijital bir örnek üzerinden değerlendir.','["Evet her zaman","Sadece arkadaşsa","İnternette izin gerekmez","Hayır"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,313,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-etik-konu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-14','coktan_secmeli','Dijital ortamda saygılı dil gerekli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","Kurallar geçersizdir","Sadece öğretmene"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,314,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-etik-konu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-15','coktan_secmeli','Güçlü şifre nasıl olmalıdır? Dijital bir örnek üzerinden değerlendir.','["Ad-soyad kadar basit","123456","Herkesle aynı","Tahmini zor ve kişiye özel"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,315,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-siber' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-16','coktan_secmeli','Şüpheli bağlantıya tıklamadan önce ne yapılmalıdır? Dijital bir örnek üzerinden değerlendir.','["Hemen açılmalıdır.","Kaynak ve güvenilirlik kontrol edilmelidir.","Şifre verilmelidir.","Arkadaşlara gönderilmelidir."]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,316,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-siber' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-17','coktan_secmeli','Yapay zekâ ne yapabilir? Dijital bir örnek üzerinden değerlendir.','["Her zaman insan gibi düşünür","Hatasızdır","İnternetsiz hiçbir şey değildir","Verilerden örüntü öğrenerek bazı görevleri gerçekleştirebilir."]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,317,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-18','coktan_secmeli','Yapay zekâ çıktıları kontrol edilmeli midir? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","Her zaman doğrudur","Kaynak gerekmez"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,318,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-temel' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-19','coktan_secmeli','Yapay zekâya kişisel sırlar yazmak güvenli midir? Dijital bir örnek üzerinden değerlendir.','["Evet her zaman","Şifre de yazılmalı","Adres paylaşılmalı","Genellikle hayır"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,319,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-sorumlu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-20','coktan_secmeli','AI ile üretilen bilgi kaynakla doğrulanmalı mıdır? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","AI yanılmaz","Sadece uzun cevapsa"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,320,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-ai-sorumlu' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-21','coktan_secmeli','Algoritma neyi ifade eder? Dijital bir örnek üzerinden değerlendir.','["Sadece kod rengini","Bilgisayar markasını","Dosya uzantısını","Bir işi çözmek için sıralı adımları"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,321,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-algoritma' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-22','coktan_secmeli','Adımların sırası sonucu etkileyebilir mi? Dijital bir örnek üzerinden değerlendir.','["Hayır","Evet","Algoritmada sıra yoktur","Sadece görsel etkiler"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,322,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-algoritma' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-23','coktan_secmeli','Döngü ne işe yarar? Dijital bir örnek üzerinden değerlendir.','["Şifreyi silmeye","Ekranı kapatmaya","Dosyayı yazdırmaya","Tekrarlanan işlemleri düzenlemeye"]',3,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,323,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-program' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5bt-4-24','coktan_secmeli','Koşul yapısı neyi sağlar? Dijital bir örnek üzerinden değerlendir.','["Her zaman aynı işlemi","Bir duruma göre farklı işlem seçmeyi","Sadece ses çıkarmayı","Ağı kapatmayı"]',1,'Bilişim kavramı güvenlik, etik ve problem çözme açısından değerlendirilir.',2,324,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='bt5-program' AND (d.kod='bilisim' OR d.ad='Bilişim Teknolojileri ve Yazılım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

