SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-allah-inanc','Allah''ın Varlığı ve Birliği','Allah''ın Varlığı ve Birliği','Allah''ın Varlığı ve Birliği kavramlarını anlam ve değer boyutuyla açıklar.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-allah' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-esma','Allah''ın Güzel İsimleri ve Evrendeki Düzen','Allah''ın Güzel İsimleri ve Evrendeki Düzen','Allah''ın Güzel İsimleri ve Evrendeki Düzen kavramlarını anlam ve değer boyutuyla açıklar.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-allah' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-namaz-anlam','Namazın Anlamı ve Önemi','Namazın Anlamı ve Önemi','Namazın Anlamı ve Önemi kavramlarını anlam ve değer boyutuyla açıklar.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-namaz' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-namaz-uyg','Namazın Hazırlık ve Uygulama Esasları','Namazın Hazırlık ve Uygulama Esasları','Namazın Hazırlık ve Uygulama Esasları kavramlarını anlam ve değer boyutuyla açıklar.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-namaz' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-kuran-yapi','Kur''an-ı Kerim''in Yapısı','Kur''an-ı Kerim''in Yapısı','Kur''an-ı Kerim''in Yapısı kavramlarını anlam ve değer boyutuyla açıklar.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-kuran' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-kuran-mesaj','Kur''an''ın Temel Mesajları','Kur''an''ın Temel Mesajları','Kur''an''ın Temel Mesajları kavramlarını anlam ve değer boyutuyla açıklar.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-kuran' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-peygamber','Peygamber Kıssalarının Mesajları','Peygamber Kıssalarının Mesajları','Peygamber Kıssalarının Mesajları kavramlarını anlam ve değer boyutuyla açıklar.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-kissa' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-deger','Kıssalardan Ahlaki Değerler','Kıssalardan Ahlaki Değerler','Kıssalardan Ahlaki Değerler kavramlarını anlam ve değer boyutuyla açıklar.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-kissa' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-cami','Cami ve Dinî Mimari Unsurları','Cami ve Dinî Mimari Unsurları','Cami ve Dinî Mimari Unsurları kavramlarını anlam ve değer boyutuyla açıklar.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-mimari' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif)
SELECT d.id,b.id,'temel_egitim',5,'din5-motif','Mimarimizde Dinî ve Kültürel Motifler','Mimarimizde Dinî ve Kültürel Motifler','Mimarimizde Dinî ve Kültürel Motifler kavramlarını anlam ve değer boyutuyla açıklar.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=5 AND b.kod='din5-mimari' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-1','coktan_secmeli','Tevhid neyi ifade eder?','["Allah''ın birliğini","Çok tanrıcılığı","Sadece ibadet yerini","Mimariyi"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-allah-inanc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-2','coktan_secmeli','İslam inancında yaratıcı kimdir?','["Bir insan","Bir yıldız","Allah","Bir melek"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-allah-inanc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-3','coktan_secmeli','Esmaülhüsna neyi anlatır?','["Allah''ın güzel isimlerini","Surelerin sayısını","Cami bölümlerini","Namaz vakitlerini"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-esma' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-4','coktan_secmeli','Evrendeki düzen üzerinde düşünmek inançla ilişkilendirilebilir mi?','["Hayır","Sadece bilimle","Evet","Düşünmek yasaktır"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-esma' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-5','coktan_secmeli','Namaz İslam''da bir ibadet midir?','["Evet","Hayır","Sadece gelenek","Sadece spor"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-anlam' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-6','coktan_secmeli','Namaz insanın Allah''a yönelmesini destekler mi?','["Hayır","Sadece sosyal etkinlik","Evet","İbadetle ilgisiz"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-anlam' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-7','coktan_secmeli','Abdest namaz hazırlığıyla ilişkili midir?','["Evet","Hayır","Sadece yemek","Sadece yolculuk"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-uyg' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-8','coktan_secmeli','Kıble neyi ifade eder?','["Namaz süresini","Cami yüksekliğini","Namazda yönelinen yönü","Kur''an sayfasını"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-uyg' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-9','coktan_secmeli','Kur''an bölümlerine ne denir?','["Sure","Bölge","Sınıf","Mihrap"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-yapi' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-10','coktan_secmeli','Ayet neyi ifade eder?','["Caminin kapısını","Namaz vaktini","Kur''an''daki vahiy cümle veya bölümlerini","Mimari süsü"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-yapi' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-11','coktan_secmeli','Kur''an doğruluk ve adalet gibi değerlere önem verir mi?','["Evet","Hayır","Sadece tarih anlatır","Değerlerle ilgisiz"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-mesaj' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-12','coktan_secmeli','Kur''an''ın mesajlarını anlamaya çalışmak önemli midir?','["Hayır","Sadece ezber gerekir","Evet","Anlamak gerekmez"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-mesaj' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-13','coktan_secmeli','Peygamber kıssaları ne sağlar?','["Geçmiş peygamberlerden mesaj ve dersler sunar.","Sadece tarih listesi","Sadece coğrafya","Sadece sayı"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-14','coktan_secmeli','Kıssalar sabır ve güven gibi değerleri anlatabilir mi?','["Hayır","Sadece savaş","Evet","Değer içermez"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-15','coktan_secmeli','Hz. Nuh kıssası sabırla ilişkilendirilebilir mi?','["Evet","Hayır","Sadece mimari","Sadece ekonomi"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-16','coktan_secmeli','Peygamber kıssalarındaki örnek davranışlar günlük yaşama uygulanabilir mi?','["Hayır","Sadece geçmişte kalır","Evet","Davranışla ilgisiz"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-17','coktan_secmeli','Mihrap camide neyi gösterir?','["Kıble yönünü","Giriş kapısını","Minareyi","Şadırvanı"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-cami' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-18','coktan_secmeli','Minare hangi yapıyla ilişkilidir?','["Köprü","Ev","Cami","Okul"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-cami' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-19','coktan_secmeli','Hat sanatı dinî mimaride görülebilir mi?','["Evet","Hayır","Sadece sporda","Sadece trafikte"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-1-20','coktan_secmeli','Geometrik ve bitkisel motifler cami süslemelerinde kullanılabilir mi?','["Hayır","Sadece yazı olur","Evet","Süsleme yoktur"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-1','coktan_secmeli','Tevhid neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Çok tanrıcılığı","Allah''ın birliğini","Sadece ibadet yerini","Mimariyi"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-allah-inanc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-2','coktan_secmeli','İslam inancında yaratıcı kimdir? Kavramı günlük yaşam ve değerler açısından düşün.','["Bir insan","Bir yıldız","Bir melek","Allah"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-allah-inanc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-3','coktan_secmeli','Esmaülhüsna neyi anlatır? Kavramı günlük yaşam ve değerler açısından düşün.','["Surelerin sayısını","Allah''ın güzel isimlerini","Cami bölümlerini","Namaz vakitlerini"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-esma' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-4','coktan_secmeli','Evrendeki düzen üzerinde düşünmek inançla ilişkilendirilebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece bilimle","Düşünmek yasaktır","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-esma' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-5','coktan_secmeli','Namaz İslam''da bir ibadet midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece gelenek","Sadece spor"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-anlam' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-6','coktan_secmeli','Namaz insanın Allah''a yönelmesini destekler mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece sosyal etkinlik","İbadetle ilgisiz","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-anlam' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-7','coktan_secmeli','Abdest namaz hazırlığıyla ilişkili midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece yemek","Sadece yolculuk"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-uyg' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-8','coktan_secmeli','Kıble neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Namaz süresini","Cami yüksekliğini","Kur''an sayfasını","Namazda yönelinen yönü"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-uyg' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-9','coktan_secmeli','Kur''an bölümlerine ne denir? Kavramı günlük yaşam ve değerler açısından düşün.','["Bölge","Sure","Sınıf","Mihrap"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-yapi' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-10','coktan_secmeli','Ayet neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Caminin kapısını","Namaz vaktini","Mimari süsü","Kur''an''daki vahiy cümle veya bölümlerini"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-yapi' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-11','coktan_secmeli','Kur''an doğruluk ve adalet gibi değerlere önem verir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece tarih anlatır","Değerlerle ilgisiz"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-mesaj' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-12','coktan_secmeli','Kur''an''ın mesajlarını anlamaya çalışmak önemli midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece ezber gerekir","Anlamak gerekmez","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-mesaj' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-13','coktan_secmeli','Peygamber kıssaları ne sağlar? Kavramı günlük yaşam ve değerler açısından düşün.','["Sadece tarih listesi","Geçmiş peygamberlerden mesaj ve dersler sunar.","Sadece coğrafya","Sadece sayı"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-14','coktan_secmeli','Kıssalar sabır ve güven gibi değerleri anlatabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece savaş","Değer içermez","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-15','coktan_secmeli','Hz. Nuh kıssası sabırla ilişkilendirilebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece mimari","Sadece ekonomi"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-16','coktan_secmeli','Peygamber kıssalarındaki örnek davranışlar günlük yaşama uygulanabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece geçmişte kalır","Davranışla ilgisiz","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-17','coktan_secmeli','Mihrap camide neyi gösterir? Kavramı günlük yaşam ve değerler açısından düşün.','["Giriş kapısını","Kıble yönünü","Minareyi","Şadırvanı"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-cami' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-18','coktan_secmeli','Minare hangi yapıyla ilişkilidir? Kavramı günlük yaşam ve değerler açısından düşün.','["Köprü","Ev","Okul","Cami"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-cami' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-19','coktan_secmeli','Hat sanatı dinî mimaride görülebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece sporda","Sadece trafikte"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-2-20','coktan_secmeli','Geometrik ve bitkisel motifler cami süslemelerinde kullanılabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece yazı olur","Süsleme yoktur","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',1,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-1','coktan_secmeli','Tevhid neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Çok tanrıcılığı","Sadece ibadet yerini","Allah''ın birliğini","Mimariyi"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-allah-inanc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-2','coktan_secmeli','İslam inancında yaratıcı kimdir? Kavramı günlük yaşam ve değerler açısından düşün.','["Allah","Bir insan","Bir yıldız","Bir melek"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-allah-inanc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-3','coktan_secmeli','Esmaülhüsna neyi anlatır? Kavramı günlük yaşam ve değerler açısından düşün.','["Surelerin sayısını","Cami bölümlerini","Allah''ın güzel isimlerini","Namaz vakitlerini"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-esma' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-4','coktan_secmeli','Evrendeki düzen üzerinde düşünmek inançla ilişkilendirilebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Evet","Hayır","Sadece bilimle","Düşünmek yasaktır"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-esma' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-5','coktan_secmeli','Namaz İslam''da bir ibadet midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece gelenek","Evet","Sadece spor"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-anlam' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-6','coktan_secmeli','Namaz insanın Allah''a yönelmesini destekler mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Evet","Hayır","Sadece sosyal etkinlik","İbadetle ilgisiz"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-anlam' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-7','coktan_secmeli','Abdest namaz hazırlığıyla ilişkili midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece yemek","Evet","Sadece yolculuk"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-uyg' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-8','coktan_secmeli','Kıble neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Namazda yönelinen yönü","Namaz süresini","Cami yüksekliğini","Kur''an sayfasını"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-uyg' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-9','coktan_secmeli','Kur''an bölümlerine ne denir? Kavramı günlük yaşam ve değerler açısından düşün.','["Bölge","Sınıf","Sure","Mihrap"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-yapi' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-10','coktan_secmeli','Ayet neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Kur''an''daki vahiy cümle veya bölümlerini","Caminin kapısını","Namaz vaktini","Mimari süsü"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-yapi' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-11','coktan_secmeli','Kur''an doğruluk ve adalet gibi değerlere önem verir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece tarih anlatır","Evet","Değerlerle ilgisiz"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-mesaj' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-12','coktan_secmeli','Kur''an''ın mesajlarını anlamaya çalışmak önemli midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Evet","Hayır","Sadece ezber gerekir","Anlamak gerekmez"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-mesaj' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-13','coktan_secmeli','Peygamber kıssaları ne sağlar? Kavramı günlük yaşam ve değerler açısından düşün.','["Sadece tarih listesi","Sadece coğrafya","Geçmiş peygamberlerden mesaj ve dersler sunar.","Sadece sayı"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-14','coktan_secmeli','Kıssalar sabır ve güven gibi değerleri anlatabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Evet","Hayır","Sadece savaş","Değer içermez"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-15','coktan_secmeli','Hz. Nuh kıssası sabırla ilişkilendirilebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece mimari","Evet","Sadece ekonomi"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-16','coktan_secmeli','Peygamber kıssalarındaki örnek davranışlar günlük yaşama uygulanabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Evet","Hayır","Sadece geçmişte kalır","Davranışla ilgisiz"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-17','coktan_secmeli','Mihrap camide neyi gösterir? Kavramı günlük yaşam ve değerler açısından düşün.','["Giriş kapısını","Minareyi","Kıble yönünü","Şadırvanı"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-cami' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-18','coktan_secmeli','Minare hangi yapıyla ilişkilidir? Kavramı günlük yaşam ve değerler açısından düşün.','["Cami","Köprü","Ev","Okul"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-cami' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-19','coktan_secmeli','Hat sanatı dinî mimaride görülebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece sporda","Evet","Sadece trafikte"]',2,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-3-20','coktan_secmeli','Geometrik ve bitkisel motifler cami süslemelerinde kullanılabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Evet","Hayır","Sadece yazı olur","Süsleme yoktur"]',0,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-1','coktan_secmeli','Tevhid neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Çok tanrıcılığı","Sadece ibadet yerini","Mimariyi","Allah''ın birliğini"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,301,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-allah-inanc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-2','coktan_secmeli','İslam inancında yaratıcı kimdir? Kavramı günlük yaşam ve değerler açısından düşün.','["Bir insan","Allah","Bir yıldız","Bir melek"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,302,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-allah-inanc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-3','coktan_secmeli','Esmaülhüsna neyi anlatır? Kavramı günlük yaşam ve değerler açısından düşün.','["Surelerin sayısını","Cami bölümlerini","Namaz vakitlerini","Allah''ın güzel isimlerini"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,303,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-esma' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-4','coktan_secmeli','Evrendeki düzen üzerinde düşünmek inançla ilişkilendirilebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece bilimle","Düşünmek yasaktır"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,304,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-esma' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-5','coktan_secmeli','Namaz İslam''da bir ibadet midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece gelenek","Sadece spor","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,305,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-anlam' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-6','coktan_secmeli','Namaz insanın Allah''a yönelmesini destekler mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece sosyal etkinlik","İbadetle ilgisiz"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,306,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-anlam' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-7','coktan_secmeli','Abdest namaz hazırlığıyla ilişkili midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece yemek","Sadece yolculuk","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,307,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-uyg' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-8','coktan_secmeli','Kıble neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Namaz süresini","Namazda yönelinen yönü","Cami yüksekliğini","Kur''an sayfasını"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,308,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-namaz-uyg' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-9','coktan_secmeli','Kur''an bölümlerine ne denir? Kavramı günlük yaşam ve değerler açısından düşün.','["Bölge","Sınıf","Mihrap","Sure"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,309,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-yapi' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-10','coktan_secmeli','Ayet neyi ifade eder? Kavramı günlük yaşam ve değerler açısından düşün.','["Caminin kapısını","Kur''an''daki vahiy cümle veya bölümlerini","Namaz vaktini","Mimari süsü"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,310,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-yapi' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-11','coktan_secmeli','Kur''an doğruluk ve adalet gibi değerlere önem verir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece tarih anlatır","Değerlerle ilgisiz","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,311,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-mesaj' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-12','coktan_secmeli','Kur''an''ın mesajlarını anlamaya çalışmak önemli midir? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece ezber gerekir","Anlamak gerekmez"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,312,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-kuran-mesaj' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-13','coktan_secmeli','Peygamber kıssaları ne sağlar? Kavramı günlük yaşam ve değerler açısından düşün.','["Sadece tarih listesi","Sadece coğrafya","Sadece sayı","Geçmiş peygamberlerden mesaj ve dersler sunar."]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,313,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-14','coktan_secmeli','Kıssalar sabır ve güven gibi değerleri anlatabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece savaş","Değer içermez"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,314,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-15','coktan_secmeli','Hz. Nuh kıssası sabırla ilişkilendirilebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece mimari","Sadece ekonomi","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,315,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-16','coktan_secmeli','Peygamber kıssalarındaki örnek davranışlar günlük yaşama uygulanabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece geçmişte kalır","Davranışla ilgisiz"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,316,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-17','coktan_secmeli','Mihrap camide neyi gösterir? Kavramı günlük yaşam ve değerler açısından düşün.','["Giriş kapısını","Minareyi","Şadırvanı","Kıble yönünü"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,317,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-cami' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-18','coktan_secmeli','Minare hangi yapıyla ilişkilidir? Kavramı günlük yaşam ve değerler açısından düşün.','["Köprü","Cami","Ev","Okul"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,318,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-cami' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-19','coktan_secmeli','Hat sanatı dinî mimaride görülebilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Sadece sporda","Sadece trafikte","Evet"]',3,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,319,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif)
SELECT k.id,'g5d-4-20','coktan_secmeli','Geometrik ve bitkisel motifler cami süslemelerinde kullanılabilir mi? Kavramı günlük yaşam ve değerler açısından düşün.','["Hayır","Evet","Sadece yazı olur","Süsleme yoktur"]',1,'Din kültürü ve ahlak bilgisi kavramı doğru bağlamda değerlendirilir.',2,320,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=5 AND k.konu_kodu='din5-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

