SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-rol','Roller, Gruplar ve Toplumsal İlişkiler','Roller, Gruplar ve Toplumsal İlişkiler','Roller, Gruplar ve Toplumsal İlişkiler konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-birlikte' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-on-yargi','Ön Yargı, Ayrımcılık ve Birlikte Yaşam','Ön Yargı, Ayrımcılık ve Birlikte Yaşam','Ön Yargı, Ayrımcılık ve Birlikte Yaşam konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-birlikte' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-konum','Türkiye''nin Coğrafi Konumu','Türkiye''nin Coğrafi Konumu','Türkiye''nin Coğrafi Konumu konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-dunya' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-iklim','İklim, Nüfus ve Yerleşme','İklim, Nüfus ve Yerleşme','İklim, Nüfus ve Yerleşme konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-dunya' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-turk-tarih','Türk Tarihinden Ortak Miras','Türk Tarihinden Ortak Miras','Türk Tarihinden Ortak Miras konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-miras' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-kultur-etkilesim','Kültürel Etkileşim ve Miras','Kültürel Etkileşim ve Miras','Kültürel Etkileşim ve Miras konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-miras' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-yonetim','Yönetim ve Demokratik Katılım','Yönetim ve Demokratik Katılım','Yönetim ve Demokratik Katılım konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-demokrasi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-hak-sorum','Hak, Özgürlük ve Sorumluluk','Hak, Özgürlük ve Sorumluluk','Hak, Özgürlük ve Sorumluluk konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-demokrasi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-kaynak','Kaynaklar ve Ekonomik Faaliyetler','Kaynaklar ve Ekonomik Faaliyetler','Kaynaklar ve Ekonomik Faaliyetler konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-ekonomi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-vergi','Bütçe, Vergi ve Bilinçli Tüketim','Bütçe, Vergi ve Bilinçli Tüketim','Bütçe, Vergi ve Bilinçli Tüketim konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-ekonomi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-bilimsel-gelisim','Bilimsel Gelişmelerin Topluma Etkisi','Bilimsel Gelişmelerin Topluma Etkisi','Bilimsel Gelişmelerin Topluma Etkisi konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-teknoloji' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'sos6-medya','Medya, Dijital Bilgi ve Sorumluluk','Medya, Dijital Bilgi ve Sorumluluk','Medya, Dijital Bilgi ve Sorumluluk konusunu harita, kanıt, veri ve toplumsal örneklerle ilişkilendirir.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='sos6-teknoloji' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-1','coktan_secmeli','Toplumsal rol zaman ve ortama göre değişebilir mi?','["Evet","Hayır","Rol hiç değişmez","Sadece yetişkinlerde"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-rol' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-2','coktan_secmeli','Bir gruptaki sorumluluklar iş birliğini etkiler mi?','["Hayır","Sadece bireysel başarı","Evet","Grup kuralı yoktur"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-rol' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-3','coktan_secmeli','Ön yargı yeterli bilgi olmadan oluşan peşin yargı olabilir mi?','["Evet","Hayır","Her zaman kanıta dayanır","Sadece olumlu olur"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-on-yargi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-4','coktan_secmeli','Ayrımcılık eşitlik ilkesine uygun mudur?','["Evet","Sadece okulda","Hayır","Sadece yetişkinlerde"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-on-yargi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-5','coktan_secmeli','Türkiye hangi iki kıta arasında köprü konumundadır?','["Asya ve Avrupa","Afrika ve Amerika","Avrupa ve Avustralya","Asya ve Antarktika"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-konum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-6','coktan_secmeli','Matematik konum enlem ve boylamla ifade edilebilir mi?','["Hayır","Sadece şehir adıyla","Evet","Sadece iklimle"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-konum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-7','coktan_secmeli','İklim ekonomik faaliyetleri etkileyebilir mi?','["Evet","Hayır","Sadece haritayı","Sadece nüfusu değil"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-iklim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-8','coktan_secmeli','Nüfus her yerde eşit dağılmış mıdır?','["Evet","Her ülkede eşittir","Hayır","Sadece kırsalda farklıdır"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-iklim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-9','coktan_secmeli','Tarihî eserler geçmiş uygarlıklar hakkında kanıt sunar mı?','["Evet","Hayır","Sadece süstür","Tarih anlatmaz"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-turk-tarih' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-10','coktan_secmeli','Orta Asya Türk topluluklarının kültürü Anadolu''yu etkileyen mirasın parçalarından mıdır?','["Hayır","Kültürel bağ yoktur","Evet","Sadece coğrafya etkiler"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-turk-tarih' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-11','coktan_secmeli','Ticaret yolları kültürel etkileşimi artırabilir mi?','["Evet","Hayır","Sadece mal taşır","Kültür etkilenmez"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kultur-etkilesim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-12','coktan_secmeli','Ortak mirası korumak gelecek kuşaklar için önemli midir?','["Hayır","Sadece turistler için","Evet","Miras korunmaz"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kultur-etkilesim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-13','coktan_secmeli','Demokratik yönetimde halkın katılımı önemli midir?','["Evet","Hayır","Sadece yöneticiler","Katılım yasaktır"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-yonetim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-14','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir?','["Hayır","Sadece okul oyunu","Evet","Sadece ekonomi"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-yonetim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-15','coktan_secmeli','Hak ve özgürlükler başkalarının haklarını yok sayma yetkisi verir mi?','["Hayır","Evet","Her zaman","Sadece çevrim içi"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-hak-sorum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-16','coktan_secmeli','Sorumluluklar ortak yaşamı düzenlemeye katkı sağlar mı?','["Hayır","Kuralları kaldırır","Evet","Sadece bireyseldir"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-hak-sorum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-17','coktan_secmeli','Doğal kaynaklar ekonomik faaliyetleri etkileyebilir mi?','["Evet","Hayır","Sadece nüfusu","Ekonomi kaynakla ilgisiz"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kaynak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-18','coktan_secmeli','Üretim için emek, sermaye ve kaynaklar önemli olabilir mi?','["Hayır","Sadece reklam","Evet","Sadece tüketim"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kaynak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-19','coktan_secmeli','Vergiler kamu hizmetlerinin finansmanına katkı sağlar mı?','["Evet","Hayır","Sadece özel alışveriş","Sadece ihracat"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-vergi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-20','coktan_secmeli','Bütçe gelir ve gider planı mıdır?','["Hayır","Harita türüdür","Evet","Sadece vergi listesidir"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-vergi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-21','coktan_secmeli','Bilimsel buluşlar üretim ve iletişimi değiştirebilir mi?','["Evet","Hayır","Sadece laboratuvarda kalır","Toplumu etkilemez"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-bilimsel-gelisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-22','coktan_secmeli','Bilim tarihinde farklı toplumların katkıları olabilir mi?','["Hayır","Tek toplum katkı sağlar","Evet","Bilim kültürden bağımsızdır"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-bilimsel-gelisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-23','coktan_secmeli','Medyadaki bilgi doğrulanmalı mıdır?','["Evet","Hayır","Paylaşım sayısı yeter","Her haber doğrudur"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-medya' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-1-24','coktan_secmeli','Dijital içerik paylaşırken kişisel haklara dikkat edilmeli mi?','["Hayır","İnternette hak yoktur","Evet","Sadece ünlüler için"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-medya' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-1','coktan_secmeli','Toplumsal rol zaman ve ortama göre değişebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Rol hiç değişmez","Sadece yetişkinlerde"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-rol' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-2','coktan_secmeli','Bir gruptaki sorumluluklar iş birliğini etkiler mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece bireysel başarı","Grup kuralı yoktur","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-rol' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-3','coktan_secmeli','Ön yargı yeterli bilgi olmadan oluşan peşin yargı olabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Her zaman kanıta dayanır","Sadece olumlu olur"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-on-yargi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-4','coktan_secmeli','Ayrımcılık eşitlik ilkesine uygun mudur? Toplumsal bir örneğe uygula.','["Evet","Sadece okulda","Sadece yetişkinlerde","Hayır"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-on-yargi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-5','coktan_secmeli','Türkiye hangi iki kıta arasında köprü konumundadır? Toplumsal bir örneğe uygula.','["Afrika ve Amerika","Asya ve Avrupa","Avrupa ve Avustralya","Asya ve Antarktika"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-konum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-6','coktan_secmeli','Matematik konum enlem ve boylamla ifade edilebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece şehir adıyla","Sadece iklimle","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-konum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-7','coktan_secmeli','İklim ekonomik faaliyetleri etkileyebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece haritayı","Sadece nüfusu değil"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-iklim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-8','coktan_secmeli','Nüfus her yerde eşit dağılmış mıdır? Toplumsal bir örneğe uygula.','["Evet","Her ülkede eşittir","Sadece kırsalda farklıdır","Hayır"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-iklim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-9','coktan_secmeli','Tarihî eserler geçmiş uygarlıklar hakkında kanıt sunar mı? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece süstür","Tarih anlatmaz"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-turk-tarih' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-10','coktan_secmeli','Orta Asya Türk topluluklarının kültürü Anadolu''yu etkileyen mirasın parçalarından mıdır? Toplumsal bir örneğe uygula.','["Hayır","Kültürel bağ yoktur","Sadece coğrafya etkiler","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-turk-tarih' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-11','coktan_secmeli','Ticaret yolları kültürel etkileşimi artırabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece mal taşır","Kültür etkilenmez"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kultur-etkilesim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-12','coktan_secmeli','Ortak mirası korumak gelecek kuşaklar için önemli midir? Toplumsal bir örneğe uygula.','["Hayır","Sadece turistler için","Miras korunmaz","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kultur-etkilesim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-13','coktan_secmeli','Demokratik yönetimde halkın katılımı önemli midir? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece yöneticiler","Katılım yasaktır"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-yonetim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-14','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir? Toplumsal bir örneğe uygula.','["Hayır","Sadece okul oyunu","Sadece ekonomi","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-yonetim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-15','coktan_secmeli','Hak ve özgürlükler başkalarının haklarını yok sayma yetkisi verir mi? Toplumsal bir örneğe uygula.','["Evet","Hayır","Her zaman","Sadece çevrim içi"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-hak-sorum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-16','coktan_secmeli','Sorumluluklar ortak yaşamı düzenlemeye katkı sağlar mı? Toplumsal bir örneğe uygula.','["Hayır","Kuralları kaldırır","Sadece bireyseldir","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-hak-sorum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-17','coktan_secmeli','Doğal kaynaklar ekonomik faaliyetleri etkileyebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece nüfusu","Ekonomi kaynakla ilgisiz"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kaynak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-18','coktan_secmeli','Üretim için emek, sermaye ve kaynaklar önemli olabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece reklam","Sadece tüketim","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kaynak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-19','coktan_secmeli','Vergiler kamu hizmetlerinin finansmanına katkı sağlar mı? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece özel alışveriş","Sadece ihracat"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-vergi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-20','coktan_secmeli','Bütçe gelir ve gider planı mıdır? Toplumsal bir örneğe uygula.','["Hayır","Harita türüdür","Sadece vergi listesidir","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-vergi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-21','coktan_secmeli','Bilimsel buluşlar üretim ve iletişimi değiştirebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece laboratuvarda kalır","Toplumu etkilemez"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,121,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-bilimsel-gelisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-22','coktan_secmeli','Bilim tarihinde farklı toplumların katkıları olabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Tek toplum katkı sağlar","Bilim kültürden bağımsızdır","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,122,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-bilimsel-gelisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-23','coktan_secmeli','Medyadaki bilgi doğrulanmalı mıdır? Toplumsal bir örneğe uygula.','["Hayır","Evet","Paylaşım sayısı yeter","Her haber doğrudur"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,123,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-medya' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-2-24','coktan_secmeli','Dijital içerik paylaşırken kişisel haklara dikkat edilmeli mi? Toplumsal bir örneğe uygula.','["Hayır","İnternette hak yoktur","Sadece ünlüler için","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',1,124,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-medya' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-1','coktan_secmeli','Toplumsal rol zaman ve ortama göre değişebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Rol hiç değişmez","Evet","Sadece yetişkinlerde"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-rol' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-2','coktan_secmeli','Bir gruptaki sorumluluklar iş birliğini etkiler mi? Toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece bireysel başarı","Grup kuralı yoktur"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-rol' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-3','coktan_secmeli','Ön yargı yeterli bilgi olmadan oluşan peşin yargı olabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Her zaman kanıta dayanır","Evet","Sadece olumlu olur"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-on-yargi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-4','coktan_secmeli','Ayrımcılık eşitlik ilkesine uygun mudur? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece okulda","Sadece yetişkinlerde"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-on-yargi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-5','coktan_secmeli','Türkiye hangi iki kıta arasında köprü konumundadır? Toplumsal bir örneğe uygula.','["Afrika ve Amerika","Avrupa ve Avustralya","Asya ve Avrupa","Asya ve Antarktika"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-konum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-6','coktan_secmeli','Matematik konum enlem ve boylamla ifade edilebilir mi? Toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece şehir adıyla","Sadece iklimle"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-konum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-7','coktan_secmeli','İklim ekonomik faaliyetleri etkileyebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece haritayı","Evet","Sadece nüfusu değil"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-iklim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-8','coktan_secmeli','Nüfus her yerde eşit dağılmış mıdır? Toplumsal bir örneğe uygula.','["Hayır","Evet","Her ülkede eşittir","Sadece kırsalda farklıdır"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-iklim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-9','coktan_secmeli','Tarihî eserler geçmiş uygarlıklar hakkında kanıt sunar mı? Toplumsal bir örneğe uygula.','["Hayır","Sadece süstür","Evet","Tarih anlatmaz"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-turk-tarih' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-10','coktan_secmeli','Orta Asya Türk topluluklarının kültürü Anadolu''yu etkileyen mirasın parçalarından mıdır? Toplumsal bir örneğe uygula.','["Evet","Hayır","Kültürel bağ yoktur","Sadece coğrafya etkiler"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-turk-tarih' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-11','coktan_secmeli','Ticaret yolları kültürel etkileşimi artırabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece mal taşır","Evet","Kültür etkilenmez"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kultur-etkilesim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-12','coktan_secmeli','Ortak mirası korumak gelecek kuşaklar için önemli midir? Toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece turistler için","Miras korunmaz"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kultur-etkilesim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-13','coktan_secmeli','Demokratik yönetimde halkın katılımı önemli midir? Toplumsal bir örneğe uygula.','["Hayır","Sadece yöneticiler","Evet","Katılım yasaktır"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-yonetim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-14','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir? Toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece okul oyunu","Sadece ekonomi"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-yonetim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-15','coktan_secmeli','Hak ve özgürlükler başkalarının haklarını yok sayma yetkisi verir mi? Toplumsal bir örneğe uygula.','["Evet","Her zaman","Hayır","Sadece çevrim içi"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-hak-sorum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-16','coktan_secmeli','Sorumluluklar ortak yaşamı düzenlemeye katkı sağlar mı? Toplumsal bir örneğe uygula.','["Evet","Hayır","Kuralları kaldırır","Sadece bireyseldir"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-hak-sorum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-17','coktan_secmeli','Doğal kaynaklar ekonomik faaliyetleri etkileyebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece nüfusu","Evet","Ekonomi kaynakla ilgisiz"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kaynak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-18','coktan_secmeli','Üretim için emek, sermaye ve kaynaklar önemli olabilir mi? Toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece reklam","Sadece tüketim"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kaynak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-19','coktan_secmeli','Vergiler kamu hizmetlerinin finansmanına katkı sağlar mı? Toplumsal bir örneğe uygula.','["Hayır","Sadece özel alışveriş","Evet","Sadece ihracat"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-vergi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-20','coktan_secmeli','Bütçe gelir ve gider planı mıdır? Toplumsal bir örneğe uygula.','["Evet","Hayır","Harita türüdür","Sadece vergi listesidir"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-vergi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-21','coktan_secmeli','Bilimsel buluşlar üretim ve iletişimi değiştirebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece laboratuvarda kalır","Evet","Toplumu etkilemez"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,221,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-bilimsel-gelisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-22','coktan_secmeli','Bilim tarihinde farklı toplumların katkıları olabilir mi? Toplumsal bir örneğe uygula.','["Evet","Hayır","Tek toplum katkı sağlar","Bilim kültürden bağımsızdır"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,222,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-bilimsel-gelisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-23','coktan_secmeli','Medyadaki bilgi doğrulanmalı mıdır? Toplumsal bir örneğe uygula.','["Hayır","Paylaşım sayısı yeter","Evet","Her haber doğrudur"]',2,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,223,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-medya' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-3-24','coktan_secmeli','Dijital içerik paylaşırken kişisel haklara dikkat edilmeli mi? Toplumsal bir örneğe uygula.','["Evet","Hayır","İnternette hak yoktur","Sadece ünlüler için"]',0,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,224,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-medya' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-1','coktan_secmeli','Toplumsal rol zaman ve ortama göre değişebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Rol hiç değişmez","Sadece yetişkinlerde","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,301,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-rol' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-2','coktan_secmeli','Bir gruptaki sorumluluklar iş birliğini etkiler mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece bireysel başarı","Grup kuralı yoktur"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,302,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-rol' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-3','coktan_secmeli','Ön yargı yeterli bilgi olmadan oluşan peşin yargı olabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Her zaman kanıta dayanır","Sadece olumlu olur","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,303,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-on-yargi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-4','coktan_secmeli','Ayrımcılık eşitlik ilkesine uygun mudur? Toplumsal bir örneğe uygula.','["Evet","Hayır","Sadece okulda","Sadece yetişkinlerde"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,304,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-on-yargi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-5','coktan_secmeli','Türkiye hangi iki kıta arasında köprü konumundadır? Toplumsal bir örneğe uygula.','["Afrika ve Amerika","Avrupa ve Avustralya","Asya ve Antarktika","Asya ve Avrupa"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,305,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-konum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-6','coktan_secmeli','Matematik konum enlem ve boylamla ifade edilebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece şehir adıyla","Sadece iklimle"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,306,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-konum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-7','coktan_secmeli','İklim ekonomik faaliyetleri etkileyebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece haritayı","Sadece nüfusu değil","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,307,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-iklim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-8','coktan_secmeli','Nüfus her yerde eşit dağılmış mıdır? Toplumsal bir örneğe uygula.','["Evet","Hayır","Her ülkede eşittir","Sadece kırsalda farklıdır"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,308,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-iklim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-9','coktan_secmeli','Tarihî eserler geçmiş uygarlıklar hakkında kanıt sunar mı? Toplumsal bir örneğe uygula.','["Hayır","Sadece süstür","Tarih anlatmaz","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,309,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-turk-tarih' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-10','coktan_secmeli','Orta Asya Türk topluluklarının kültürü Anadolu''yu etkileyen mirasın parçalarından mıdır? Toplumsal bir örneğe uygula.','["Hayır","Evet","Kültürel bağ yoktur","Sadece coğrafya etkiler"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,310,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-turk-tarih' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-11','coktan_secmeli','Ticaret yolları kültürel etkileşimi artırabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece mal taşır","Kültür etkilenmez","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,311,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kultur-etkilesim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-12','coktan_secmeli','Ortak mirası korumak gelecek kuşaklar için önemli midir? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece turistler için","Miras korunmaz"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,312,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kultur-etkilesim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-13','coktan_secmeli','Demokratik yönetimde halkın katılımı önemli midir? Toplumsal bir örneğe uygula.','["Hayır","Sadece yöneticiler","Katılım yasaktır","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,313,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-yonetim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-14','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece okul oyunu","Sadece ekonomi"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,314,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-yonetim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-15','coktan_secmeli','Hak ve özgürlükler başkalarının haklarını yok sayma yetkisi verir mi? Toplumsal bir örneğe uygula.','["Evet","Her zaman","Sadece çevrim içi","Hayır"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,315,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-hak-sorum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-16','coktan_secmeli','Sorumluluklar ortak yaşamı düzenlemeye katkı sağlar mı? Toplumsal bir örneğe uygula.','["Hayır","Evet","Kuralları kaldırır","Sadece bireyseldir"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,316,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-hak-sorum' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-17','coktan_secmeli','Doğal kaynaklar ekonomik faaliyetleri etkileyebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece nüfusu","Ekonomi kaynakla ilgisiz","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,317,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kaynak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-18','coktan_secmeli','Üretim için emek, sermaye ve kaynaklar önemli olabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Sadece reklam","Sadece tüketim"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,318,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-kaynak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-19','coktan_secmeli','Vergiler kamu hizmetlerinin finansmanına katkı sağlar mı? Toplumsal bir örneğe uygula.','["Hayır","Sadece özel alışveriş","Sadece ihracat","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,319,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-vergi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-20','coktan_secmeli','Bütçe gelir ve gider planı mıdır? Toplumsal bir örneğe uygula.','["Hayır","Evet","Harita türüdür","Sadece vergi listesidir"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,320,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-vergi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-21','coktan_secmeli','Bilimsel buluşlar üretim ve iletişimi değiştirebilir mi? Toplumsal bir örneğe uygula.','["Hayır","Sadece laboratuvarda kalır","Toplumu etkilemez","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,321,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-bilimsel-gelisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-22','coktan_secmeli','Bilim tarihinde farklı toplumların katkıları olabilir mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","Tek toplum katkı sağlar","Bilim kültürden bağımsızdır"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,322,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-bilimsel-gelisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-23','coktan_secmeli','Medyadaki bilgi doğrulanmalı mıdır? Toplumsal bir örneğe uygula.','["Hayır","Paylaşım sayısı yeter","Her haber doğrudur","Evet"]',3,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,323,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-medya' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6s-4-24','coktan_secmeli','Dijital içerik paylaşırken kişisel haklara dikkat edilmeli mi? Toplumsal bir örneğe uygula.','["Hayır","Evet","İnternette hak yoktur","Sadece ünlüler için"]',1,'Sosyal Bilgiler kavramı kanıt ve bağlama göre yorumlanır.',2,324,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='sos6-medya' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

