SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-peygamber','Peygamberlik ve Vahiy','Peygamberlik ve Vahiy','Peygamberlik ve Vahiy konusunu örnek ve uygulamalarla ilişkilendirir.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-peygamber' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-kitap','İlahi Kitaplar','İlahi Kitaplar','İlahi Kitaplar konusunu örnek ve uygulamalarla ilişkilendirir.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-peygamber' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-oruc','Oruç ve Ramazan','Oruç ve Ramazan','Oruç ve Ramazan konusunu örnek ve uygulamalarla ilişkilendirir.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-ramazan' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-ramazan-deger','Ramazan, Paylaşma ve Dayanışma','Ramazan, Paylaşma ve Dayanışma','Ramazan, Paylaşma ve Dayanışma konusunu örnek ve uygulamalarla ilişkilendirir.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-ramazan' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-ahlak','Ahlaki Tutum ve Davranışlar','Ahlaki Tutum ve Davranışlar','Ahlaki Tutum ve Davranışlar konusunu örnek ve uygulamalarla ilişkilendirir.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-ahlak' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-kul-hakki','Hak, Adalet ve Sorumluluk','Hak, Adalet ve Sorumluluk','Hak, Adalet ve Sorumluluk konusunu örnek ve uygulamalarla ilişkilendirir.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-ahlak' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-cocukluk','Hz. Muhammed''in Çocukluğu ve Gençliği','Hz. Muhammed''in Çocukluğu ve Gençliği','Hz. Muhammed''in Çocukluğu ve Gençliği konusunu örnek ve uygulamalarla ilişkilendirir.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-siyer' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-guven','Hz. Muhammed''in Güvenilirliği','Hz. Muhammed''in Güvenilirliği','Hz. Muhammed''in Güvenilirliği konusunu örnek ve uygulamalarla ilişkilendirir.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-siyer' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-motif','Dinî Motifler ve Kültür','Dinî Motifler ve Kültür','Dinî Motifler ve Kültür konusunu örnek ve uygulamalarla ilişkilendirir.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-kultur' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'d6-mekan','Dinî Mekânlar ve Mimari','Dinî Mekânlar ve Mimari','Dinî Mekânlar ve Mimari konusunu örnek ve uygulamalarla ilişkilendirir.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='din6-kultur' WHERE d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-1','coktan_secmeli','Peygamberlerin temel görevi nedir?','["Allah''ın mesajını insanlara iletmek","Ticaret yapmak","Sadece savaşmak","Yönetici olmak zorunlu"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-2','coktan_secmeli','Vahiy neyi ifade eder?','["Sadece rüyayı","Bir şiiri","Allah''ın peygamberlere bildirdiği ilahi mesajı","Bir yasayı"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-3','coktan_secmeli','Kur''an-ı Kerim hangi peygambere gönderilmiştir?','["Hz. Muhammed''e","Hz. Musa''ya","Hz. İsa''ya","Hz. Davud''a"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kitap' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-4','coktan_secmeli','Tevrat hangi peygamberle ilişkilidir?','["Hz. Muhammed","Hz. İsa","Hz. Musa","Hz. Davud"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kitap' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-5','coktan_secmeli','Oruç hangi ayla özellikle ilişkilidir?','["Ramazan","Muharrem yalnız","Recep yalnız","Şevval yalnız"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-oruc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-6','coktan_secmeli','Oruç yalnız aç kalmak mıdır?','["Evet","Sadece susuz kalmaktır","Hayır","Sadece uyumaktır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-oruc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-7','coktan_secmeli','Ramazan paylaşma ve yardımlaşmayı destekler mi?','["Evet","Hayır","Sadece bireysel ibadettir","Paylaşmayla ilgisizdir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ramazan-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-8','coktan_secmeli','İftar neyi ifade eder?','["Sahuru","Namazı","Orucun açılmasını","Yolculuğu"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ramazan-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-9','coktan_secmeli','Doğruluk güzel ahlaki davranış mıdır?','["Evet","Hayır","Sadece okul kuralıdır","Sadece yetişkinlere"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ahlak' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-10','coktan_secmeli','Emanete sahip çıkmak hangi değerle ilişkilidir?','["İsraf","Kabalık","Güvenilirlik","Tembellik"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ahlak' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-11','coktan_secmeli','Başkalarının hakkını gözetmek önemli midir?','["Evet","Hayır","Sadece kendi hakkımız önemlidir","Hak kavramı yoktur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kul-hakki' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-12','coktan_secmeli','Adalet neyi gözetir?','["Kayırmayı","Hileyi","Hakkaniyeti","Sadece gücü"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kul-hakki' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-13','coktan_secmeli','Hz. Muhammed Mekke''de doğmuştur. Doğru mu?','["Evet","Hayır","Medine''de doğmuştur","Kudüs''te doğmuştur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-cocukluk' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-14','coktan_secmeli','Hz. Muhammed gençliğinde çalışmış ve toplum içinde güven kazanmış mıdır?','["Hayır","Toplumdan tamamen uzaktı","Evet","Çalışmamıştır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-cocukluk' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-15','coktan_secmeli','Hz. Muhammed''in güvenilirliğini ifade eden unvan?','["el-Emin","el-Kebir","el-Hakim zorunlu","el-Melik"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-guven' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-16','coktan_secmeli','Doğruluk ve güven onun örnek özellikleri arasında mıdır?','["Hayır","Sadece cesaret önemlidir","Evet","Güven önemsizdir"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-guven' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-17','coktan_secmeli','Hat sanatı dinî kültürle ilişkili olabilir mi?','["Evet","Hayır","Sadece sporla","Sadece trafikle"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-18','coktan_secmeli','Geometrik süslemeler dinî mimaride görülebilir mi?','["Hayır","Sadece resim vardır","Evet","Süsleme kullanılmaz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-19','coktan_secmeli','Mihrap camide kıble yönünü gösterir mi?','["Evet","Hayır","Minareyi gösterir","Kapıyı gösterir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-mekan' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-1-20','coktan_secmeli','Minare cami mimarisinin unsurlarından biri midir?','["Hayır","Sadece saraylarda","Evet","Sadece evlerde"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-mekan' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-1','coktan_secmeli','Peygamberlerin temel görevi nedir? Günlük yaşam bağlamında düşün.','["Ticaret yapmak","Allah''ın mesajını insanlara iletmek","Sadece savaşmak","Yönetici olmak zorunlu"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-2','coktan_secmeli','Vahiy neyi ifade eder? Günlük yaşam bağlamında düşün.','["Sadece rüyayı","Bir şiiri","Bir yasayı","Allah''ın peygamberlere bildirdiği ilahi mesajı"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-3','coktan_secmeli','Kur''an-ı Kerim hangi peygambere gönderilmiştir? Günlük yaşam bağlamında düşün.','["Hz. Musa''ya","Hz. Muhammed''e","Hz. İsa''ya","Hz. Davud''a"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kitap' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-4','coktan_secmeli','Tevrat hangi peygamberle ilişkilidir? Günlük yaşam bağlamında düşün.','["Hz. Muhammed","Hz. İsa","Hz. Davud","Hz. Musa"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kitap' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-5','coktan_secmeli','Oruç hangi ayla özellikle ilişkilidir? Günlük yaşam bağlamında düşün.','["Muharrem yalnız","Ramazan","Recep yalnız","Şevval yalnız"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-oruc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-6','coktan_secmeli','Oruç yalnız aç kalmak mıdır? Günlük yaşam bağlamında düşün.','["Evet","Sadece susuz kalmaktır","Sadece uyumaktır","Hayır"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-oruc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-7','coktan_secmeli','Ramazan paylaşma ve yardımlaşmayı destekler mi? Günlük yaşam bağlamında düşün.','["Hayır","Evet","Sadece bireysel ibadettir","Paylaşmayla ilgisizdir"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ramazan-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-8','coktan_secmeli','İftar neyi ifade eder? Günlük yaşam bağlamında düşün.','["Sahuru","Namazı","Yolculuğu","Orucun açılmasını"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ramazan-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-9','coktan_secmeli','Doğruluk güzel ahlaki davranış mıdır? Günlük yaşam bağlamında düşün.','["Hayır","Evet","Sadece okul kuralıdır","Sadece yetişkinlere"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ahlak' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-10','coktan_secmeli','Emanete sahip çıkmak hangi değerle ilişkilidir? Günlük yaşam bağlamında düşün.','["İsraf","Kabalık","Tembellik","Güvenilirlik"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ahlak' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-11','coktan_secmeli','Başkalarının hakkını gözetmek önemli midir? Günlük yaşam bağlamında düşün.','["Hayır","Evet","Sadece kendi hakkımız önemlidir","Hak kavramı yoktur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kul-hakki' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-12','coktan_secmeli','Adalet neyi gözetir? Günlük yaşam bağlamında düşün.','["Kayırmayı","Hileyi","Sadece gücü","Hakkaniyeti"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kul-hakki' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-13','coktan_secmeli','Hz. Muhammed Mekke''de doğmuştur. Doğru mu? Günlük yaşam bağlamında düşün.','["Hayır","Evet","Medine''de doğmuştur","Kudüs''te doğmuştur"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-cocukluk' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-14','coktan_secmeli','Hz. Muhammed gençliğinde çalışmış ve toplum içinde güven kazanmış mıdır? Günlük yaşam bağlamında düşün.','["Hayır","Toplumdan tamamen uzaktı","Çalışmamıştır","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-cocukluk' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-15','coktan_secmeli','Hz. Muhammed''in güvenilirliğini ifade eden unvan? Günlük yaşam bağlamında düşün.','["el-Kebir","el-Emin","el-Hakim zorunlu","el-Melik"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-guven' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-16','coktan_secmeli','Doğruluk ve güven onun örnek özellikleri arasında mıdır? Günlük yaşam bağlamında düşün.','["Hayır","Sadece cesaret önemlidir","Güven önemsizdir","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-guven' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-17','coktan_secmeli','Hat sanatı dinî kültürle ilişkili olabilir mi? Günlük yaşam bağlamında düşün.','["Hayır","Evet","Sadece sporla","Sadece trafikle"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-18','coktan_secmeli','Geometrik süslemeler dinî mimaride görülebilir mi? Günlük yaşam bağlamında düşün.','["Hayır","Sadece resim vardır","Süsleme kullanılmaz","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-19','coktan_secmeli','Mihrap camide kıble yönünü gösterir mi? Günlük yaşam bağlamında düşün.','["Hayır","Evet","Minareyi gösterir","Kapıyı gösterir"]',1,'Konu bilgisi bağlama göre değerlendirilir.',1,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-mekan' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-2-20','coktan_secmeli','Minare cami mimarisinin unsurlarından biri midir? Günlük yaşam bağlamında düşün.','["Hayır","Sadece saraylarda","Sadece evlerde","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',1,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-mekan' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-1','coktan_secmeli','Peygamberlerin temel görevi nedir? Kavramı başka bir örneğe uygula.','["Ticaret yapmak","Sadece savaşmak","Allah''ın mesajını insanlara iletmek","Yönetici olmak zorunlu"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-2','coktan_secmeli','Vahiy neyi ifade eder? Kavramı başka bir örneğe uygula.','["Allah''ın peygamberlere bildirdiği ilahi mesajı","Sadece rüyayı","Bir şiiri","Bir yasayı"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-3','coktan_secmeli','Kur''an-ı Kerim hangi peygambere gönderilmiştir? Kavramı başka bir örneğe uygula.','["Hz. Musa''ya","Hz. İsa''ya","Hz. Muhammed''e","Hz. Davud''a"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kitap' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-4','coktan_secmeli','Tevrat hangi peygamberle ilişkilidir? Kavramı başka bir örneğe uygula.','["Hz. Musa","Hz. Muhammed","Hz. İsa","Hz. Davud"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kitap' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-5','coktan_secmeli','Oruç hangi ayla özellikle ilişkilidir? Kavramı başka bir örneğe uygula.','["Muharrem yalnız","Recep yalnız","Ramazan","Şevval yalnız"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-oruc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-6','coktan_secmeli','Oruç yalnız aç kalmak mıdır? Kavramı başka bir örneğe uygula.','["Hayır","Evet","Sadece susuz kalmaktır","Sadece uyumaktır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-oruc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-7','coktan_secmeli','Ramazan paylaşma ve yardımlaşmayı destekler mi? Kavramı başka bir örneğe uygula.','["Hayır","Sadece bireysel ibadettir","Evet","Paylaşmayla ilgisizdir"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ramazan-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-8','coktan_secmeli','İftar neyi ifade eder? Kavramı başka bir örneğe uygula.','["Orucun açılmasını","Sahuru","Namazı","Yolculuğu"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ramazan-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-9','coktan_secmeli','Doğruluk güzel ahlaki davranış mıdır? Kavramı başka bir örneğe uygula.','["Hayır","Sadece okul kuralıdır","Evet","Sadece yetişkinlere"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ahlak' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-10','coktan_secmeli','Emanete sahip çıkmak hangi değerle ilişkilidir? Kavramı başka bir örneğe uygula.','["Güvenilirlik","İsraf","Kabalık","Tembellik"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ahlak' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-11','coktan_secmeli','Başkalarının hakkını gözetmek önemli midir? Kavramı başka bir örneğe uygula.','["Hayır","Sadece kendi hakkımız önemlidir","Evet","Hak kavramı yoktur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kul-hakki' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-12','coktan_secmeli','Adalet neyi gözetir? Kavramı başka bir örneğe uygula.','["Hakkaniyeti","Kayırmayı","Hileyi","Sadece gücü"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kul-hakki' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-13','coktan_secmeli','Hz. Muhammed Mekke''de doğmuştur. Doğru mu? Kavramı başka bir örneğe uygula.','["Hayır","Medine''de doğmuştur","Evet","Kudüs''te doğmuştur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-cocukluk' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-14','coktan_secmeli','Hz. Muhammed gençliğinde çalışmış ve toplum içinde güven kazanmış mıdır? Kavramı başka bir örneğe uygula.','["Evet","Hayır","Toplumdan tamamen uzaktı","Çalışmamıştır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-cocukluk' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-15','coktan_secmeli','Hz. Muhammed''in güvenilirliğini ifade eden unvan? Kavramı başka bir örneğe uygula.','["el-Kebir","el-Hakim zorunlu","el-Emin","el-Melik"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-guven' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-16','coktan_secmeli','Doğruluk ve güven onun örnek özellikleri arasında mıdır? Kavramı başka bir örneğe uygula.','["Evet","Hayır","Sadece cesaret önemlidir","Güven önemsizdir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-guven' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-17','coktan_secmeli','Hat sanatı dinî kültürle ilişkili olabilir mi? Kavramı başka bir örneğe uygula.','["Hayır","Sadece sporla","Evet","Sadece trafikle"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-18','coktan_secmeli','Geometrik süslemeler dinî mimaride görülebilir mi? Kavramı başka bir örneğe uygula.','["Evet","Hayır","Sadece resim vardır","Süsleme kullanılmaz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-19','coktan_secmeli','Mihrap camide kıble yönünü gösterir mi? Kavramı başka bir örneğe uygula.','["Hayır","Minareyi gösterir","Evet","Kapıyı gösterir"]',2,'Konu bilgisi bağlama göre değerlendirilir.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-mekan' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-3-20','coktan_secmeli','Minare cami mimarisinin unsurlarından biri midir? Kavramı başka bir örneğe uygula.','["Evet","Hayır","Sadece saraylarda","Sadece evlerde"]',0,'Konu bilgisi bağlama göre değerlendirilir.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-mekan' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-1','coktan_secmeli','Peygamberlerin temel görevi nedir? En uygun açıklamayı seç.','["Ticaret yapmak","Sadece savaşmak","Yönetici olmak zorunlu","Allah''ın mesajını insanlara iletmek"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,301,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-2','coktan_secmeli','Vahiy neyi ifade eder? En uygun açıklamayı seç.','["Sadece rüyayı","Allah''ın peygamberlere bildirdiği ilahi mesajı","Bir şiiri","Bir yasayı"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,302,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-peygamber' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-3','coktan_secmeli','Kur''an-ı Kerim hangi peygambere gönderilmiştir? En uygun açıklamayı seç.','["Hz. Musa''ya","Hz. İsa''ya","Hz. Davud''a","Hz. Muhammed''e"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,303,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kitap' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-4','coktan_secmeli','Tevrat hangi peygamberle ilişkilidir? En uygun açıklamayı seç.','["Hz. Muhammed","Hz. Musa","Hz. İsa","Hz. Davud"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,304,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kitap' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-5','coktan_secmeli','Oruç hangi ayla özellikle ilişkilidir? En uygun açıklamayı seç.','["Muharrem yalnız","Recep yalnız","Şevval yalnız","Ramazan"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,305,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-oruc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-6','coktan_secmeli','Oruç yalnız aç kalmak mıdır? En uygun açıklamayı seç.','["Evet","Hayır","Sadece susuz kalmaktır","Sadece uyumaktır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,306,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-oruc' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-7','coktan_secmeli','Ramazan paylaşma ve yardımlaşmayı destekler mi? En uygun açıklamayı seç.','["Hayır","Sadece bireysel ibadettir","Paylaşmayla ilgisizdir","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,307,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ramazan-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-8','coktan_secmeli','İftar neyi ifade eder? En uygun açıklamayı seç.','["Sahuru","Orucun açılmasını","Namazı","Yolculuğu"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,308,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ramazan-deger' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-9','coktan_secmeli','Doğruluk güzel ahlaki davranış mıdır? En uygun açıklamayı seç.','["Hayır","Sadece okul kuralıdır","Sadece yetişkinlere","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,309,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ahlak' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-10','coktan_secmeli','Emanete sahip çıkmak hangi değerle ilişkilidir? En uygun açıklamayı seç.','["İsraf","Güvenilirlik","Kabalık","Tembellik"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,310,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-ahlak' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-11','coktan_secmeli','Başkalarının hakkını gözetmek önemli midir? En uygun açıklamayı seç.','["Hayır","Sadece kendi hakkımız önemlidir","Hak kavramı yoktur","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,311,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kul-hakki' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-12','coktan_secmeli','Adalet neyi gözetir? En uygun açıklamayı seç.','["Kayırmayı","Hakkaniyeti","Hileyi","Sadece gücü"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,312,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-kul-hakki' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-13','coktan_secmeli','Hz. Muhammed Mekke''de doğmuştur. Doğru mu? En uygun açıklamayı seç.','["Hayır","Medine''de doğmuştur","Kudüs''te doğmuştur","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,313,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-cocukluk' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-14','coktan_secmeli','Hz. Muhammed gençliğinde çalışmış ve toplum içinde güven kazanmış mıdır? En uygun açıklamayı seç.','["Hayır","Evet","Toplumdan tamamen uzaktı","Çalışmamıştır"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,314,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-cocukluk' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-15','coktan_secmeli','Hz. Muhammed''in güvenilirliğini ifade eden unvan? En uygun açıklamayı seç.','["el-Kebir","el-Hakim zorunlu","el-Melik","el-Emin"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,315,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-guven' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-16','coktan_secmeli','Doğruluk ve güven onun örnek özellikleri arasında mıdır? En uygun açıklamayı seç.','["Hayır","Evet","Sadece cesaret önemlidir","Güven önemsizdir"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,316,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-guven' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-17','coktan_secmeli','Hat sanatı dinî kültürle ilişkili olabilir mi? En uygun açıklamayı seç.','["Hayır","Sadece sporla","Sadece trafikle","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,317,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-18','coktan_secmeli','Geometrik süslemeler dinî mimaride görülebilir mi? En uygun açıklamayı seç.','["Hayır","Evet","Sadece resim vardır","Süsleme kullanılmaz"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,318,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-motif' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-19','coktan_secmeli','Mihrap camide kıble yönünü gösterir mi? En uygun açıklamayı seç.','["Hayır","Minareyi gösterir","Kapıyı gösterir","Evet"]',3,'Konu bilgisi bağlama göre değerlendirilir.',2,319,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-mekan' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6d-4-20','coktan_secmeli','Minare cami mimarisinin unsurlarından biri midir? En uygun açıklamayı seç.','["Hayır","Evet","Sadece saraylarda","Sadece evlerde"]',1,'Konu bilgisi bağlama göre değerlendirilir.',2,320,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='d6-mekan' AND (d.kod='din' OR d.ad='Din Kültürü ve Ahlak Bilgisi') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

