SET NAMES utf8mb4;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-gs-tasarim','Görsel Tasarım ve Kompozisyon','Görsel Tasarım ve Kompozisyon','Görsel Tasarım ve Kompozisyon becerilerini uygular.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='gs6-uretme' WHERE d.kod='gorsel' OR d.ad='Görsel Sanatlar' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-gs-miras','Sanat ve Kültürel Miras','Sanat ve Kültürel Miras','Sanat ve Kültürel Miras becerilerini uygular.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='gs6-miras' WHERE d.kod='gorsel' OR d.ad='Görsel Sanatlar' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-gs-elestiri','Sanat Eserini Çözümleme','Sanat Eserini Çözümleme','Sanat Eserini Çözümleme becerilerini uygular.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='gs6-estetik' WHERE d.kod='gorsel' OR d.ad='Görsel Sanatlar' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-muz-ses','Dinleme, Söyleme ve Ses','Dinleme, Söyleme ve Ses','Dinleme, Söyleme ve Ses becerilerini uygular.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='muz6-dinleme' WHERE d.kod='muzik' OR d.ad='Müzik' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-muz-ritim','Ritim ve Müzik Dili','Ritim ve Müzik Dili','Ritim ve Müzik Dili becerilerini uygular.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='muz6-ritim' WHERE d.kod='muzik' OR d.ad='Müzik' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-muz-uret','Müziksel Üretim','Müziksel Üretim','Müziksel Üretim becerilerini uygular.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='muz6-yaratici' WHERE d.kod='muzik' OR d.ad='Müzik' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-muz-kultur','Müzik Kültürü','Müzik Kültürü','Müzik Kültürü becerilerini uygular.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='muz6-kultur' WHERE d.kod='muzik' OR d.ad='Müzik' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-be-hareket','Hareket Becerileri','Hareket Becerileri','Hareket Becerileri becerilerini uygular.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='bes6-hareket' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-be-zindelik','Fiziksel Uygunluk','Fiziksel Uygunluk','Fiziksel Uygunluk becerilerini uygular.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='bes6-zindelik' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-be-takim','Takım ve Strateji','Takım ve Strateji','Takım ve Strateji becerilerini uygular.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='bes6-takim' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-be-ritim','Ritim ve Hareket','Ritim ve Hareket','Ritim ve Hareket becerilerini uygular.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='bes6-ritim' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-be-kultur','Spor Kültürü ve Değerler','Spor Kültürü ve Değerler','Spor Kültürü ve Değerler becerilerini uygular.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='bes6-kultur' WHERE d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-reh-kendim','Öz Farkındalık','Öz Farkındalık','Öz Farkındalık becerilerini uygular.','',130,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='reh6-kendim' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-reh-hedef','Hedef ve Öz Düzenleme','Hedef ve Öz Düzenleme','Hedef ve Öz Düzenleme becerilerini uygular.','',140,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='reh6-hedef' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-reh-iliski','Akran İlişkileri','Akran İlişkileri','Akran İlişkileri becerilerini uygular.','',150,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='reh6-iliski' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-reh-guven','Güvenli ve Sağlıklı Yaşam','Güvenli ve Sağlıklı Yaşam','Güvenli ve Sağlıklı Yaşam becerilerini uygular.','',160,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='reh6-guven' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'g6-reh-kariyer','Kariyer Farkındalığı','Kariyer Farkındalığı','Kariyer Farkındalığı becerilerini uygular.','',170,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='reh6-kariyer' WHERE d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-1','coktan_secmeli','Denge kompozisyonun bir ilkesi midir?','["Evet","Hayır","Sadece müzikte","Sadece matematikte"]',0,'Beceri uygun bağlamda değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-2','coktan_secmeli','Perspektif derinlik hissi verebilir mi?','["Hayır","Sadece renk verir","Evet","Sadece doku verir"]',2,'Beceri uygun bağlamda değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-3','coktan_secmeli','Sanat eserleri kültürel miras olabilir mi?','["Evet","Hayır","Sadece yeni eserler","Kültürle ilgisiz"]',0,'Beceri uygun bağlamda değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-4','coktan_secmeli','Müzeler koruma işlevi görür mü?','["Hayır","Sadece satış","Evet","Sadece eğlence"]',2,'Beceri uygun bağlamda değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-5','coktan_secmeli','Bir eseri biçim ve içerik açısından incelemek mümkün mü?','["Evet","Hayır","Sadece fiyat","Sadece çerçeve"]',0,'Beceri uygun bağlamda değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-6','coktan_secmeli','Farklı yorumlar mümkün olabilir mi?','["Hayır","Tek yorum vardır","Evet","Yorum yasaktır"]',2,'Beceri uygun bağlamda değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-7','coktan_secmeli','Doğru nefes söylemeyi destekler mi?','["Evet","Hayır","Sadece koşuyu","Müzikle ilgisiz"]',0,'Beceri uygun bağlamda değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-8','coktan_secmeli','Ses sağlığını korumak önemli midir?','["Hayır","Bağırmak iyidir","Evet","Ses etkilenmez"]',2,'Beceri uygun bağlamda değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-9','coktan_secmeli','Tempo müziğin hızını ifade eder mi?','["Evet","Hayır","Rengi ifade eder","Kütleyi ifade eder"]',0,'Beceri uygun bağlamda değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-10','coktan_secmeli','Ölçü ritmik düzenle ilişkili midir?','["Hayır","Sadece renk","Evet","Sadece alan"]',2,'Beceri uygun bağlamda değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-11','coktan_secmeli','Ritim kalıbı üretmek yaratıcılık mıdır?','["Evet","Hayır","Sadece kopya","Müzik değildir"]',0,'Beceri uygun bağlamda değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-12','coktan_secmeli','Basit ezgi üretilebilir mi?','["Hayır","Sadece profesyoneller","Evet","Ezgi üretilemez"]',2,'Beceri uygun bağlamda değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-13','coktan_secmeli','Türküler ortak kültürel mirasın parçası olabilir mi?','["Evet","Hayır","Sadece pop müzik","Kültürle ilgisiz"]',0,'Beceri uygun bağlamda değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-14','coktan_secmeli','Farklı kültür müziklerine saygı önemli midir?','["Hayır","Sadece kendi müziğimiz","Evet","Farklı müzik yasaktır"]',2,'Beceri uygun bağlamda değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-15','coktan_secmeli','Denge ve koordinasyon hareket becerisinin parçası mıdır?','["Evet","Hayır","Sadece yazma becerisi","Sadece müzik"]',0,'Beceri uygun bağlamda değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-16','coktan_secmeli','Güvenli hareket alanı önemli midir?','["Hayır","Sadece hız önemlidir","Evet","Alan önemsiz"]',2,'Beceri uygun bağlamda değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-17','coktan_secmeli','Isınma sakatlanma riskini azaltmaya yardımcı olabilir mi?','["Evet","Hayır","Sadece yorulmayı artırır","Suyla ilgilidir"]',0,'Beceri uygun bağlamda değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-18','coktan_secmeli','Düzenli aktivite zindeliği destekler mi?','["Hayır","Hareketsizlik destekler","Evet","Sadece sporculara"]',2,'Beceri uygun bağlamda değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-19','coktan_secmeli','Takım stratejisi iş birliğini gerektirir mi?','["Evet","Hayır","Sadece bireysel skor","İletişim gereksiz"]',0,'Beceri uygun bağlamda değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-20','coktan_secmeli','Adil oyun rakibe saygıyı içerir mi?','["Hayır","Hile kabul edilir","Evet","Sadece kazanmak önemlidir"]',2,'Beceri uygun bağlamda değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-21','coktan_secmeli','Ritim değişince hareket uyarlanabilir mi?','["Evet","Hayır","Hareket hep aynı","Ritim önemsiz"]',0,'Beceri uygun bağlamda değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-ritim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-22','coktan_secmeli','Grup ritmi uyum gerektirir mi?','["Hayır","Sadece bireysel","Evet","Uyum gerekmez"]',2,'Beceri uygun bağlamda değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-ritim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-23','coktan_secmeli','Geleneksel oyunlar kültürel miras olabilir mi?','["Evet","Hayır","Sadece dijital oyunlar","Kültürle ilgisiz"]',0,'Beceri uygun bağlamda değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-24','coktan_secmeli','Sportmenlik davranışları spor kültürünü destekler mi?','["Hayır","Sadece skor","Evet","Davranış önemli değil"]',2,'Beceri uygun bağlamda değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-25','coktan_secmeli','Güçlü yönleri fark etmek öz farkındalık mıdır?','["Evet","Hayır","Sadece notlar","Farkındalık değildir"]',0,'Beceri uygun bağlamda değerlendirilir.',1,25,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-26','coktan_secmeli','Gelişim alanını belirlemek yararlı mıdır?','["Hayır","Başarısızlık demektir","Evet","Sadece yetişkinler"]',2,'Beceri uygun bağlamda değerlendirilir.',1,26,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-27','coktan_secmeli','Hedefi küçük adımlara bölmek planlamayı kolaylaştırır mı?','["Evet","Hayır","Hedefi yok eder","Daha karmaşık yapar"]',0,'Beceri uygun bağlamda değerlendirilir.',1,27,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-28','coktan_secmeli','Çalışma planı öz düzenlemeyi destekler mi?','["Hayır","Sadece öğretmen için","Evet","Plan gereksiz"]',2,'Beceri uygun bağlamda değerlendirilir.',1,28,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-29','coktan_secmeli','Aktif dinleme anlaşmazlık çözümünde yararlı mıdır?','["Evet","Hayır","Bağırmak daha iyi","Dinleme gereksiz"]',0,'Beceri uygun bağlamda değerlendirilir.',1,29,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-30','coktan_secmeli','Kişisel sınırlar akran ilişkilerinde önemli midir?','["Hayır","Sadece yabancılarla","Evet","Sınır yoktur"]',2,'Beceri uygun bağlamda değerlendirilir.',1,30,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-31','coktan_secmeli','Dijital denge uyku ve dikkat için önemli midir?','["Evet","Hayır","Sınırsız ekran iyidir","Uyku gerekmez"]',0,'Beceri uygun bağlamda değerlendirilir.',1,31,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-32','coktan_secmeli','Riskli çevrim içi durumda yetişkin desteği alınmalı mı?','["Hayır","Gizlenmeli","Evet","Aynısı yapılmalı"]',2,'Beceri uygun bağlamda değerlendirilir.',1,32,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-33','coktan_secmeli','İlgi ve yetenekler meslek araştırmasında kullanılabilir mi?','["Evet","Hayır","Sadece maaş","Sadece yaş"]',0,'Beceri uygun bağlamda değerlendirilir.',1,33,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-1-34','coktan_secmeli','Meslekleri araştırmak gelecek farkındalığını artırır mı?','["Hayır","Araştırma gereksiz","Evet","Sadece tahmin yeter"]',2,'Beceri uygun bağlamda değerlendirilir.',1,34,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-1','coktan_secmeli','Denge kompozisyonun bir ilkesi midir? Uygulama örneğini düşün.','["Hayır","Sadece müzikte","Sadece matematikte","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,101,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-2','coktan_secmeli','Perspektif derinlik hissi verebilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece renk verir","Sadece doku verir"]',1,'Beceri uygun bağlamda değerlendirilir.',2,102,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-3','coktan_secmeli','Sanat eserleri kültürel miras olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece yeni eserler","Kültürle ilgisiz","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,103,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-4','coktan_secmeli','Müzeler koruma işlevi görür mü? Uygulama örneğini düşün.','["Hayır","Evet","Sadece satış","Sadece eğlence"]',1,'Beceri uygun bağlamda değerlendirilir.',2,104,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-5','coktan_secmeli','Bir eseri biçim ve içerik açısından incelemek mümkün mü? Uygulama örneğini düşün.','["Hayır","Sadece fiyat","Sadece çerçeve","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,105,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-6','coktan_secmeli','Farklı yorumlar mümkün olabilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Tek yorum vardır","Yorum yasaktır"]',1,'Beceri uygun bağlamda değerlendirilir.',2,106,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-7','coktan_secmeli','Doğru nefes söylemeyi destekler mi? Uygulama örneğini düşün.','["Hayır","Sadece koşuyu","Müzikle ilgisiz","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,107,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-8','coktan_secmeli','Ses sağlığını korumak önemli midir? Uygulama örneğini düşün.','["Hayır","Evet","Bağırmak iyidir","Ses etkilenmez"]',1,'Beceri uygun bağlamda değerlendirilir.',2,108,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-9','coktan_secmeli','Tempo müziğin hızını ifade eder mi? Uygulama örneğini düşün.','["Hayır","Rengi ifade eder","Kütleyi ifade eder","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,109,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-10','coktan_secmeli','Ölçü ritmik düzenle ilişkili midir? Uygulama örneğini düşün.','["Hayır","Evet","Sadece renk","Sadece alan"]',1,'Beceri uygun bağlamda değerlendirilir.',2,110,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-11','coktan_secmeli','Ritim kalıbı üretmek yaratıcılık mıdır? Uygulama örneğini düşün.','["Hayır","Sadece kopya","Müzik değildir","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,111,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-12','coktan_secmeli','Basit ezgi üretilebilir mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece profesyoneller","Ezgi üretilemez"]',1,'Beceri uygun bağlamda değerlendirilir.',2,112,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-13','coktan_secmeli','Türküler ortak kültürel mirasın parçası olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece pop müzik","Kültürle ilgisiz","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,113,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-14','coktan_secmeli','Farklı kültür müziklerine saygı önemli midir? Uygulama örneğini düşün.','["Hayır","Evet","Sadece kendi müziğimiz","Farklı müzik yasaktır"]',1,'Beceri uygun bağlamda değerlendirilir.',2,114,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-15','coktan_secmeli','Denge ve koordinasyon hareket becerisinin parçası mıdır? Uygulama örneğini düşün.','["Hayır","Sadece yazma becerisi","Sadece müzik","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,115,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-16','coktan_secmeli','Güvenli hareket alanı önemli midir? Uygulama örneğini düşün.','["Hayır","Evet","Sadece hız önemlidir","Alan önemsiz"]',1,'Beceri uygun bağlamda değerlendirilir.',2,116,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-17','coktan_secmeli','Isınma sakatlanma riskini azaltmaya yardımcı olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece yorulmayı artırır","Suyla ilgilidir","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,117,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-18','coktan_secmeli','Düzenli aktivite zindeliği destekler mi? Uygulama örneğini düşün.','["Hayır","Evet","Hareketsizlik destekler","Sadece sporculara"]',1,'Beceri uygun bağlamda değerlendirilir.',2,118,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-19','coktan_secmeli','Takım stratejisi iş birliğini gerektirir mi? Uygulama örneğini düşün.','["Hayır","Sadece bireysel skor","İletişim gereksiz","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,119,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-20','coktan_secmeli','Adil oyun rakibe saygıyı içerir mi? Uygulama örneğini düşün.','["Hayır","Evet","Hile kabul edilir","Sadece kazanmak önemlidir"]',1,'Beceri uygun bağlamda değerlendirilir.',2,120,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-21','coktan_secmeli','Ritim değişince hareket uyarlanabilir mi? Uygulama örneğini düşün.','["Hayır","Hareket hep aynı","Ritim önemsiz","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,121,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-ritim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-22','coktan_secmeli','Grup ritmi uyum gerektirir mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece bireysel","Uyum gerekmez"]',1,'Beceri uygun bağlamda değerlendirilir.',2,122,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-ritim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-23','coktan_secmeli','Geleneksel oyunlar kültürel miras olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece dijital oyunlar","Kültürle ilgisiz","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,123,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-24','coktan_secmeli','Sportmenlik davranışları spor kültürünü destekler mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece skor","Davranış önemli değil"]',1,'Beceri uygun bağlamda değerlendirilir.',2,124,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-25','coktan_secmeli','Güçlü yönleri fark etmek öz farkındalık mıdır? Uygulama örneğini düşün.','["Hayır","Sadece notlar","Farkındalık değildir","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,125,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-26','coktan_secmeli','Gelişim alanını belirlemek yararlı mıdır? Uygulama örneğini düşün.','["Hayır","Evet","Başarısızlık demektir","Sadece yetişkinler"]',1,'Beceri uygun bağlamda değerlendirilir.',2,126,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-27','coktan_secmeli','Hedefi küçük adımlara bölmek planlamayı kolaylaştırır mı? Uygulama örneğini düşün.','["Hayır","Hedefi yok eder","Daha karmaşık yapar","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,127,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-28','coktan_secmeli','Çalışma planı öz düzenlemeyi destekler mi? Uygulama örneğini düşün.','["Hayır","Evet","Sadece öğretmen için","Plan gereksiz"]',1,'Beceri uygun bağlamda değerlendirilir.',2,128,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-29','coktan_secmeli','Aktif dinleme anlaşmazlık çözümünde yararlı mıdır? Uygulama örneğini düşün.','["Hayır","Bağırmak daha iyi","Dinleme gereksiz","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,129,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-30','coktan_secmeli','Kişisel sınırlar akran ilişkilerinde önemli midir? Uygulama örneğini düşün.','["Hayır","Evet","Sadece yabancılarla","Sınır yoktur"]',1,'Beceri uygun bağlamda değerlendirilir.',2,130,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-31','coktan_secmeli','Dijital denge uyku ve dikkat için önemli midir? Uygulama örneğini düşün.','["Hayır","Sınırsız ekran iyidir","Uyku gerekmez","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,131,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-32','coktan_secmeli','Riskli çevrim içi durumda yetişkin desteği alınmalı mı? Uygulama örneğini düşün.','["Hayır","Evet","Gizlenmeli","Aynısı yapılmalı"]',1,'Beceri uygun bağlamda değerlendirilir.',2,132,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-33','coktan_secmeli','İlgi ve yetenekler meslek araştırmasında kullanılabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece maaş","Sadece yaş","Evet"]',3,'Beceri uygun bağlamda değerlendirilir.',2,133,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-2-34','coktan_secmeli','Meslekleri araştırmak gelecek farkındalığını artırır mı? Uygulama örneğini düşün.','["Hayır","Evet","Araştırma gereksiz","Sadece tahmin yeter"]',1,'Beceri uygun bağlamda değerlendirilir.',2,134,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-1','coktan_secmeli','Denge kompozisyonun bir ilkesi midir? Uygulama örneğini düşün.','["Hayır","Sadece müzikte","Evet","Sadece matematikte"]',2,'Beceri uygun bağlamda değerlendirilir.',2,201,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-2','coktan_secmeli','Perspektif derinlik hissi verebilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece renk verir","Sadece doku verir"]',0,'Beceri uygun bağlamda değerlendirilir.',2,202,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-tasarim' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-3','coktan_secmeli','Sanat eserleri kültürel miras olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece yeni eserler","Evet","Kültürle ilgisiz"]',2,'Beceri uygun bağlamda değerlendirilir.',2,203,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-4','coktan_secmeli','Müzeler koruma işlevi görür mü? Uygulama örneğini düşün.','["Evet","Hayır","Sadece satış","Sadece eğlence"]',0,'Beceri uygun bağlamda değerlendirilir.',2,204,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-miras' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-5','coktan_secmeli','Bir eseri biçim ve içerik açısından incelemek mümkün mü? Uygulama örneğini düşün.','["Hayır","Sadece fiyat","Evet","Sadece çerçeve"]',2,'Beceri uygun bağlamda değerlendirilir.',2,205,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-6','coktan_secmeli','Farklı yorumlar mümkün olabilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Tek yorum vardır","Yorum yasaktır"]',0,'Beceri uygun bağlamda değerlendirilir.',2,206,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-gs-elestiri' AND (d.kod='gorsel' OR d.ad='Görsel Sanatlar') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-7','coktan_secmeli','Doğru nefes söylemeyi destekler mi? Uygulama örneğini düşün.','["Hayır","Sadece koşuyu","Evet","Müzikle ilgisiz"]',2,'Beceri uygun bağlamda değerlendirilir.',2,207,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-8','coktan_secmeli','Ses sağlığını korumak önemli midir? Uygulama örneğini düşün.','["Evet","Hayır","Bağırmak iyidir","Ses etkilenmez"]',0,'Beceri uygun bağlamda değerlendirilir.',2,208,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ses' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-9','coktan_secmeli','Tempo müziğin hızını ifade eder mi? Uygulama örneğini düşün.','["Hayır","Rengi ifade eder","Evet","Kütleyi ifade eder"]',2,'Beceri uygun bağlamda değerlendirilir.',2,209,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-10','coktan_secmeli','Ölçü ritmik düzenle ilişkili midir? Uygulama örneğini düşün.','["Evet","Hayır","Sadece renk","Sadece alan"]',0,'Beceri uygun bağlamda değerlendirilir.',2,210,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-ritim' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-11','coktan_secmeli','Ritim kalıbı üretmek yaratıcılık mıdır? Uygulama örneğini düşün.','["Hayır","Sadece kopya","Evet","Müzik değildir"]',2,'Beceri uygun bağlamda değerlendirilir.',2,211,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-12','coktan_secmeli','Basit ezgi üretilebilir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece profesyoneller","Ezgi üretilemez"]',0,'Beceri uygun bağlamda değerlendirilir.',2,212,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-uret' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-13','coktan_secmeli','Türküler ortak kültürel mirasın parçası olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece pop müzik","Evet","Kültürle ilgisiz"]',2,'Beceri uygun bağlamda değerlendirilir.',2,213,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-14','coktan_secmeli','Farklı kültür müziklerine saygı önemli midir? Uygulama örneğini düşün.','["Evet","Hayır","Sadece kendi müziğimiz","Farklı müzik yasaktır"]',0,'Beceri uygun bağlamda değerlendirilir.',2,214,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-muz-kultur' AND (d.kod='muzik' OR d.ad='Müzik') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-15','coktan_secmeli','Denge ve koordinasyon hareket becerisinin parçası mıdır? Uygulama örneğini düşün.','["Hayır","Sadece yazma becerisi","Evet","Sadece müzik"]',2,'Beceri uygun bağlamda değerlendirilir.',2,215,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-16','coktan_secmeli','Güvenli hareket alanı önemli midir? Uygulama örneğini düşün.','["Evet","Hayır","Sadece hız önemlidir","Alan önemsiz"]',0,'Beceri uygun bağlamda değerlendirilir.',2,216,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-hareket' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-17','coktan_secmeli','Isınma sakatlanma riskini azaltmaya yardımcı olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece yorulmayı artırır","Evet","Suyla ilgilidir"]',2,'Beceri uygun bağlamda değerlendirilir.',2,217,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-18','coktan_secmeli','Düzenli aktivite zindeliği destekler mi? Uygulama örneğini düşün.','["Evet","Hayır","Hareketsizlik destekler","Sadece sporculara"]',0,'Beceri uygun bağlamda değerlendirilir.',2,218,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-zindelik' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-19','coktan_secmeli','Takım stratejisi iş birliğini gerektirir mi? Uygulama örneğini düşün.','["Hayır","Sadece bireysel skor","Evet","İletişim gereksiz"]',2,'Beceri uygun bağlamda değerlendirilir.',2,219,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-20','coktan_secmeli','Adil oyun rakibe saygıyı içerir mi? Uygulama örneğini düşün.','["Evet","Hayır","Hile kabul edilir","Sadece kazanmak önemlidir"]',0,'Beceri uygun bağlamda değerlendirilir.',2,220,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-takim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-21','coktan_secmeli','Ritim değişince hareket uyarlanabilir mi? Uygulama örneğini düşün.','["Hayır","Hareket hep aynı","Evet","Ritim önemsiz"]',2,'Beceri uygun bağlamda değerlendirilir.',2,221,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-ritim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-22','coktan_secmeli','Grup ritmi uyum gerektirir mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece bireysel","Uyum gerekmez"]',0,'Beceri uygun bağlamda değerlendirilir.',2,222,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-ritim' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-23','coktan_secmeli','Geleneksel oyunlar kültürel miras olabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece dijital oyunlar","Evet","Kültürle ilgisiz"]',2,'Beceri uygun bağlamda değerlendirilir.',2,223,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-24','coktan_secmeli','Sportmenlik davranışları spor kültürünü destekler mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece skor","Davranış önemli değil"]',0,'Beceri uygun bağlamda değerlendirilir.',2,224,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-be-kultur' AND (d.kod='beden_spor' OR d.ad='Beden Eğitimi ve Spor') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-25','coktan_secmeli','Güçlü yönleri fark etmek öz farkındalık mıdır? Uygulama örneğini düşün.','["Hayır","Sadece notlar","Evet","Farkındalık değildir"]',2,'Beceri uygun bağlamda değerlendirilir.',2,225,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-26','coktan_secmeli','Gelişim alanını belirlemek yararlı mıdır? Uygulama örneğini düşün.','["Evet","Hayır","Başarısızlık demektir","Sadece yetişkinler"]',0,'Beceri uygun bağlamda değerlendirilir.',2,226,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kendim' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-27','coktan_secmeli','Hedefi küçük adımlara bölmek planlamayı kolaylaştırır mı? Uygulama örneğini düşün.','["Hayır","Hedefi yok eder","Evet","Daha karmaşık yapar"]',2,'Beceri uygun bağlamda değerlendirilir.',2,227,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-28','coktan_secmeli','Çalışma planı öz düzenlemeyi destekler mi? Uygulama örneğini düşün.','["Evet","Hayır","Sadece öğretmen için","Plan gereksiz"]',0,'Beceri uygun bağlamda değerlendirilir.',2,228,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-hedef' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-29','coktan_secmeli','Aktif dinleme anlaşmazlık çözümünde yararlı mıdır? Uygulama örneğini düşün.','["Hayır","Bağırmak daha iyi","Evet","Dinleme gereksiz"]',2,'Beceri uygun bağlamda değerlendirilir.',2,229,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-30','coktan_secmeli','Kişisel sınırlar akran ilişkilerinde önemli midir? Uygulama örneğini düşün.','["Evet","Hayır","Sadece yabancılarla","Sınır yoktur"]',0,'Beceri uygun bağlamda değerlendirilir.',2,230,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-iliski' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-31','coktan_secmeli','Dijital denge uyku ve dikkat için önemli midir? Uygulama örneğini düşün.','["Hayır","Sınırsız ekran iyidir","Evet","Uyku gerekmez"]',2,'Beceri uygun bağlamda değerlendirilir.',2,231,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-32','coktan_secmeli','Riskli çevrim içi durumda yetişkin desteği alınmalı mı? Uygulama örneğini düşün.','["Evet","Hayır","Gizlenmeli","Aynısı yapılmalı"]',0,'Beceri uygun bağlamda değerlendirilir.',2,232,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-guven' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-33','coktan_secmeli','İlgi ve yetenekler meslek araştırmasında kullanılabilir mi? Uygulama örneğini düşün.','["Hayır","Sadece maaş","Evet","Sadece yaş"]',2,'Beceri uygun bağlamda değerlendirilir.',2,233,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6o-3-34','coktan_secmeli','Meslekleri araştırmak gelecek farkındalığını artırır mı? Uygulama örneğini düşün.','["Evet","Hayır","Araştırma gereksiz","Sadece tahmin yeter"]',0,'Beceri uygun bağlamda değerlendirilir.',2,234,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='g6-reh-kariyer' AND (d.kod='rehberlik' OR d.ad='Rehberlik ve Yönlendirme') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

