SET NAMES utf8mb4;
INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-sozvar','Söz Varlığı, Deyim ve Atasözü','Söz Varlığı, Deyim ve Atasözü','Söz Varlığı, Deyim ve Atasözü becerilerini metin, kanıt ve iletişim bağlamında uygular.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-dil' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-yapi','Sözcük Yapısı ve Ekler','Sözcük Yapısı ve Ekler','Sözcük Yapısı ve Ekler becerilerini metin, kanıt ve iletişim bağlamında uygular.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-dil' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-metin','Metinde Ana Fikir, Yardımcı Fikir ve Çıkarım','Metinde Ana Fikir, Yardımcı Fikir ve Çıkarım','Metinde Ana Fikir, Yardımcı Fikir ve Çıkarım becerilerini metin, kanıt ve iletişim bağlamında uygular.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-dil' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-tarih-metin','Tarihî Metinleri Anlama','Tarihî Metinleri Anlama','Tarihî Metinleri Anlama becerilerini metin, kanıt ve iletişim bağlamında uygular.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-bagimsizlik' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-kronoloji','Kronoloji, Neden-Sonuç ve Kaynak','Kronoloji, Neden-Sonuç ve Kaynak','Kronoloji, Neden-Sonuç ve Kaynak becerilerini metin, kanıt ve iletişim bağlamında uygular.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-bagimsizlik' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-anlatim','Millî Değerleri Yazılı ve Sözlü Anlatma','Millî Değerleri Yazılı ve Sözlü Anlatma','Millî Değerleri Yazılı ve Sözlü Anlatma becerilerini metin, kanıt ve iletişim bağlamında uygular.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-bagimsizlik' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-karsilastirma','Farklı Bakış Açılarını Karşılaştırma','Farklı Bakış Açılarını Karşılaştırma','Farklı Bakış Açılarını Karşılaştırma becerilerini metin, kanıt ve iletişim bağlamında uygular.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-dunyalar' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-metin-tur','Metin Türleri ve Anlatım Özellikleri','Metin Türleri ve Anlatım Özellikleri','Metin Türleri ve Anlatım Özellikleri becerilerini metin, kanıt ve iletişim bağlamında uygular.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-dunyalar' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-gorsel','Görsel ve Çoklu Ortam Okuryazarlığı','Görsel ve Çoklu Ortam Okuryazarlığı','Görsel ve Çoklu Ortam Okuryazarlığı becerilerini metin, kanıt ve iletişim bağlamında uygular.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-dunyalar' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-iletisim-beceri','Etkili İletişim ve Aktif Dinleme','Etkili İletişim ve Aktif Dinleme','Etkili İletişim ve Aktif Dinleme becerilerini metin, kanıt ve iletişim bağlamında uygular.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-iletisim' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-gorus','Görüş, Gerekçe ve Kanıt','Görüş, Gerekçe ve Kanıt','Görüş, Gerekçe ve Kanıt becerilerini metin, kanıt ve iletişim bağlamında uygular.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-iletisim' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-dijital','Dijital İletişim ve Medya Dili','Dijital İletişim ve Medya Dili','Dijital İletişim ve Medya Dili becerilerini metin, kanıt ve iletişim bağlamında uygular.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-iletisim' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-bilim-metin','Bilimsel ve Bilgilendirici Metin','Bilimsel ve Bilgilendirici Metin','Bilimsel ve Bilgilendirici Metin becerilerini metin, kanıt ve iletişim bağlamında uygular.','',130,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-bilim' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-kaynak','Bilgi Kaynağı, Özet ve Not Alma','Bilgi Kaynağı, Özet ve Not Alma','Bilgi Kaynağı, Özet ve Not Alma becerilerini metin, kanıt ve iletişim bağlamında uygular.','',140,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-bilim' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-yazim','Yazım, Noktalama ve Metin Düzenleme','Yazım, Noktalama ve Metin Düzenleme','Yazım, Noktalama ve Metin Düzenleme becerilerini metin, kanıt ve iletişim bağlamında uygular.','',150,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-bilim' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-karakter','Karakter, Liderlik ve Değer Çözümleme','Karakter, Liderlik ve Değer Çözümleme','Karakter, Liderlik ve Değer Çözümleme becerilerini metin, kanıt ve iletişim bağlamında uygular.','',160,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-lider' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-sozlu','Konuşma, Sunum ve Tartışma','Konuşma, Sunum ve Tartışma','Konuşma, Sunum ve Tartışma becerilerini metin, kanıt ve iletişim bağlamında uygular.','',170,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-lider' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'tr6-yazma','Planlı Yazma ve Paragraf Bütünlüğü','Planlı Yazma ve Paragraf Bütünlüğü','Planlı Yazma ve Paragraf Bütünlüğü becerilerini metin, kanıt ve iletişim bağlamında uygular.','',180,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='tr6-lider' WHERE d.kod='turkce' OR d.ad='Türkçe' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-1','coktan_secmeli','“Sorumluluk almak” ifadesine yakın deyim hangisidir?','["Elini taşın altına koymak","Kulak vermek","Gözden düşmek","Yola çıkmak"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-sozvar' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-2','coktan_secmeli','Atasözleri kültürel birikim taşır mı?','["Hayır","Sadece sayı verir","Evet","Sadece kişi adı içerir"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-sozvar' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-3','coktan_secmeli','“kitaplık” sözcüğündeki -lık eki yeni sözcük türetir mi?','["Evet","Hayır","Sadece çoğul yapar","Sadece zaman bildirir"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-yapi' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-4','coktan_secmeli','Kök ve ek ayrımı sözcüğün yapısını anlamaya yardım eder mi?','["Hayır","Sadece cümle uzunluğunu","Evet","Sadece noktalama"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-yapi' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-5','coktan_secmeli','Ana fikir neyi açıklar?','["Metnin temel iletisini","Her ayrıntıyı","Yazarın adresini","Sayfa sayısını"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-metin' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-6','coktan_secmeli','Yardımcı fikirler ana fikri destekleyebilir mi?','["Hayır","Her zaman karşıttır","Evet","Metinle ilgisizdir"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-metin' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-7','coktan_secmeli','Tarihî metindeki olayları dönemin koşullarıyla değerlendirmek yararlı mıdır?','["Evet","Hayır","Sadece bugüne bakılır","Koşullar önemsizdir"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-tarih-metin' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-8','coktan_secmeli','Bir tarihî metinde yazarın bakış açısı bulunabilir mi?','["Hayır","Tarih metinlerinde bakış açısı yoktur","Evet","Sadece şiirde olur"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-tarih-metin' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-9','coktan_secmeli','Kronoloji olayların hangi özelliğini düzenler?','["Zaman sırasını","Rengini","Mekânın büyüklüğünü","Yazarın yaşını"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-kronoloji' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-10','coktan_secmeli','Neden-sonuç ilişkisi tarihî gelişmeleri anlamaya yardım eder mi?','["Hayır","Sadece dilbilgisi içindir","Evet","Tarih olaylarında neden yoktur"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-kronoloji' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-11','coktan_secmeli','Bir millî değer hakkında konuşurken gerekçe ve örnek kullanmak anlatımı güçlendirir mi?','["Evet","Hayır","Sadece başlık yeter","Örnek kullanılamaz"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-anlatim' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-12','coktan_secmeli','Sunumda kaynak göstermek güvenilirliği artırır mı?','["Hayır","Kaynak gereksiz","Evet","Sadece görsel yeter"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-anlatim' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-13','coktan_secmeli','İki metindeki farklı görüşler ortak ölçütle karşılaştırılabilir mi?','["Evet","Hayır","Sadece benzer görüşler","Metin karşılaştırılmaz"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-karsilastirma' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-14','coktan_secmeli','Karşılaştırmada benzerlik ve farklılık birlikte ele alınabilir mi?','["Hayır","Sadece farklılık","Evet","Sadece benzerlik"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-karsilastirma' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-15','coktan_secmeli','Hikâye edici metin ile bilgilendirici metnin amaçları aynı mıdır?','["Her zaman değil","Her zaman aynıdır","İkisi de sadece şiirdir","İkisi de yalnız tablo içerir"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-metin-tur' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-16','coktan_secmeli','Şiirde imgeli anlatım kullanılabilir mi?','["Hayır","Sadece teknik metinde","Evet","Şiirde anlam yoktur"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-metin-tur' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-17','coktan_secmeli','İnfografik görsel ve metni birleştirerek bilgi sunabilir mi?','["Evet","Hayır","Sadece ses içerir","Sadece şiirdir"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-gorsel' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-18','coktan_secmeli','Grafikte eksen ve ölçek doğru yorum için önemli midir?','["Hayır","Sadece renk önemlidir","Evet","Başlık yeterlidir"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-gorsel' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-19','coktan_secmeli','Aktif dinleme konuşanın mesajını anlamaya yardım eder mi?','["Evet","Hayır","Söz kesmek daha etkilidir","Dinleme iletişim değildir"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-iletisim-beceri' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-20','coktan_secmeli','Ben dili çatışmada daha yapıcı iletişime katkı sağlayabilir mi?','["Hayır","Sadece suçlama gerekir","Evet","İletişimde dil önemli değildir"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-iletisim-beceri' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-21','coktan_secmeli','Bir görüşü desteklemek için kanıt ve gerekçe kullanılabilir mi?','["Evet","Hayır","Yüksek ses yeter","Tekrar yeter"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-gorus' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-22','coktan_secmeli','Olgu ile görüş aynı mıdır?','["Evet","Her zaman","Hayır","Sadece haberde"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-gorus' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-23','coktan_secmeli','Dijital mesajda bağlam ve ton yanlış anlaşılabilir mi?','["Evet","Hayır","Yazılı iletişim her zaman açıktır","Sadece sesli mesajda"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-dijital' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-24','coktan_secmeli','Kaynağı belirsiz dijital içerik doğrulanmalı mıdır?','["Hayır","Paylaşım sayısı yeter","Evet","Her içerik doğrudur"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-dijital' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-25','coktan_secmeli','Bilimsel metinde iddia kanıtla desteklenmeli midir?','["Evet","Hayır","Tahmin yeter","Kaynak gerekmez"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,25,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-bilim-metin' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-26','coktan_secmeli','Nesnel anlatım kişisel beğeniden bağımsız bilgi vermeye çalışır mı?','["Hayır","Nesnel anlatım tamamen duygusaldır","Evet","Sadece şiirde olur"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,26,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-bilim-metin' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-27','coktan_secmeli','Not alma önemli bilgiyi düzenlemeye yardım eder mi?','["Evet","Hayır","Metni bozar","Sadece sınavda"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,27,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-kaynak' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-28','coktan_secmeli','Birden fazla kaynak karşılaştırmak doğrulamaya yardım eder mi?','["Hayır","Tek kaynak her zaman yeter","Evet","Kaynaklar karşılaştırılmaz"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,28,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-kaynak' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-29','coktan_secmeli','Yazıyı düzenleme aşamasında anlam, yazım ve noktalama kontrol edilir mi?','["Evet","Hayır","Sadece başlık","Sadece uzunluk"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,29,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-yazim' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-30','coktan_secmeli','Bağlaç olan “ki” çoğu durumda ayrı yazılır mı?','["Hayır","Her zaman bitişik","Evet","Kesmeyle"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,30,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-yazim' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-31','coktan_secmeli','Karakterin seçimleri değerlerini anlamaya ipucu verir mi?','["Evet","Hayır","Sadece görünüş önemlidir","Karakter karar vermez"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,31,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-karakter' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-32','coktan_secmeli','Liderlik yalnız emir vermek midir?','["Evet","Sadece yüksek sesle konuşmaktır","Hayır","Sadece unvandır"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,32,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-karakter' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-33','coktan_secmeli','Sunumda ana düşünceyi açıkça belirtmek önemli midir?','["Evet","Hayır","Sadece görsel yeter","Konu gizlenmelidir"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,33,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-sozlu' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-34','coktan_secmeli','Tartışmada karşı görüşe saygı gerekli midir?','["Hayır","Kişiye saldırmak gerekir","Evet","Dinleme gereksizdir"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,34,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-sozlu' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-35','coktan_secmeli','Paragrafta cümleler aynı ana düşünceyi desteklemeli midir?','["Evet","Hayır","Tamamen ilgisiz olabilir","Sadece uzunluk önemlidir"]',0,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,35,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-yazma' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6t-1-36','coktan_secmeli','Taslak yazı gözden geçirilip geliştirilebilir mi?','["Hayır","İlk taslak değişmez","Evet","Düzeltme yasaktır"]',2,'Türkçe becerisi metin ve bağlam ipuçlarıyla değerlendirilir.',1,36,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='tr6-yazma' AND (d.kod='turkce' OR d.ad='Türkçe') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;
