SET NAMES utf8mb4;
INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-sistem','Güneş Sistemi','Güneş Sistemi','Güneş Sistemi kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-gunes' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-tutulma','Güneş ve Ay Tutulmaları','Güneş ve Ay Tutulmaları','Güneş ve Ay Tutulmaları kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-gunes' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-bileske','Bileşke Kuvvet ve Dengelenmiş Kuvvet','Bileşke Kuvvet ve Dengelenmiş Kuvvet','Bileşke Kuvvet ve Dengelenmiş Kuvvet kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-kuvvet' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-hareket','Sürat ve Hareket','Sürat ve Hareket','Sürat ve Hareket kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-kuvvet' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-destek','Destek ve Hareket Sistemi','Destek ve Hareket Sistemi','Destek ve Hareket Sistemi kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-sistem' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-dolasim','Dolaşım ve Solunum Sistemleri','Dolaşım ve Solunum Sistemleri','Dolaşım ve Solunum Sistemleri kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-sistem' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-sindirim','Sindirim ve Boşaltım Sistemleri','Sindirim ve Boşaltım Sistemleri','Sindirim ve Boşaltım Sistemleri kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-sistem' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-yansima','Işığın Yansıması','Işığın Yansıması','Işığın Yansıması kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-isik' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-renk','Işık ve Renkler','Işık ve Renkler','Işık ve Renkler kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-isik' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-yogunluk','Yoğunluk','Yoğunluk','Yoğunluk kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-madde' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-isi','Isı, Sıcaklık ve Hâl Değişimi','Isı, Sıcaklık ve Hâl Değişimi','Isı, Sıcaklık ve Hâl Değişimi kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-madde' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-iletken','İletkenlik ve Elektriksel Direnç','İletkenlik ve Elektriksel Direnç','İletkenlik ve Elektriksel Direnç kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-elektrik' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-devre','Devrede Direnç ve Ampul Parlaklığı','Devrede Direnç ve Ampul Parlaklığı','Devrede Direnç ve Ampul Parlaklığı kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',130,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-elektrik' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-ekosistem','Ekosistem ve Madde Döngüleri','Ekosistem ve Madde Döngüleri','Ekosistem ve Madde Döngüleri kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',140,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-surdur' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',6,'fen6-surdur-konu','Sürdürülebilir Yaşam ve Kaynaklar','Sürdürülebilir Yaşam ve Kaynaklar','Sürdürülebilir Yaşam ve Kaynaklar kavramlarını deney, model ve günlük yaşamla ilişkilendirir.','',150,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=6 AND b.kod='fen6-surdur' WHERE d.kod='fen' OR d.ad='Fen Bilimleri' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-1','coktan_secmeli','Güneş Sistemi''nin merkezinde hangi yıldız bulunur?','["Güneş","Dünya","Ay","Jüpiter"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-sistem' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-2','coktan_secmeli','Gezegenler Güneş etrafında dolanır mı?','["Hayır","Sadece Dünya","Evet","Sadece iç gezegenler"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-sistem' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-3','coktan_secmeli','Güneş tutulmasında hangi gök cismi Dünya ile Güneş arasına girer?','["Ay","Mars","Jüpiter","Venüs"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-tutulma' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-4','coktan_secmeli','Ay tutulmasında Dünya''nın gölgesi Ay üzerine düşebilir mi?','["Hayır","Sadece Güneş gölge yapar","Evet","Ay tutulması yoktur"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-tutulma' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-5','coktan_secmeli','Aynı yöndeki kuvvetler bileşke bulunurken toplanabilir mi?','["Evet","Hayır","Çarpılır","Her zaman çıkarılır"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-bileske' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-6','coktan_secmeli','Zıt yönlü eşit kuvvetler dengelenmiş kuvvet oluşturabilir mi?','["Hayır","Cisim kesin hızlanır","Evet","Kuvvet yok olur"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-bileske' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-7','coktan_secmeli','Sürat nasıl hesaplanır?','["Alınan yol / geçen zaman","Zaman / yol","Yol × zaman","Kütle / zaman"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-hareket' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-8','coktan_secmeli','Aynı yolu daha kısa sürede alan cisim daha süratli midir?','["Hayır","Sürat aynı","Evet","Yol ilgisiz"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-hareket' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-9','coktan_secmeli','Kemikler ve kaslar birlikte harekete yardım eder mi?','["Evet","Hayır","Sadece kemik","Sadece deri"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-destek' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-10','coktan_secmeli','Eklem kemiklerin hareket bağlantısında rol oynar mı?','["Hayır","Sadece kalpte","Evet","Sadece akciğerde"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-destek' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-11','coktan_secmeli','Kalp dolaşım sisteminin önemli organı mıdır?','["Evet","Hayır","Sadece sindirimde","Sadece boşaltımda"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-dolasim' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-12','coktan_secmeli','Akciğerler gaz alışverişinde rol oynar mı?','["Hayır","Sadece kan üretir","Evet","Sadece besin depolar"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-dolasim' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-13','coktan_secmeli','Sindirim besinleri daha küçük yapılara ayırmaya yardım eder mi?','["Evet","Hayır","Sadece suyu taşır","Sadece oksijeni taşır"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-sindirim' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-14','coktan_secmeli','Böbrekler boşaltım sisteminde görevli midir?','["Hayır","Sadece sindirim","Evet","Sadece solunum"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-sindirim' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-15','coktan_secmeli','Düzgün yüzeyde düzgün yansıma görülebilir mi?','["Evet","Hayır","Işık yansımaz","Sadece ses yansır"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-yansima' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-16','coktan_secmeli','Gelme açısı yansıma açısına eşit midir?','["Hayır","Her zaman iki katı","Evet","Açılar ilgisiz"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-yansima' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-17','coktan_secmeli','Beyaz ışık farklı renklerden oluşabilir mi?','["Evet","Hayır","Sadece beyazdır","Sadece kırmızı"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-renk' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-18','coktan_secmeli','Bir cismin görünen rengi yansıttığı ışıkla ilişkili midir?','["Hayır","Sadece kütleyle","Evet","Sadece sıcaklıkla"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-renk' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-19','coktan_secmeli','Yoğunluk nasıl ifade edilir?','["Kütle / hacim","Hacim / kütle","Kütle × hacim","Sıcaklık / hacim"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-yogunluk' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-20','coktan_secmeli','Aynı hacimde daha büyük kütleli madde genellikle daha yoğun mudur?','["Hayır","Yoğunluk kütleden bağımsızdır","Evet","Sadece renk belirler"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-yogunluk' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-21','coktan_secmeli','Isı ve sıcaklık aynı kavram mıdır?','["Hayır","Evet","Her zaman eşit","Sadece birimleri farklı isimdir"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-isi' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-22','coktan_secmeli','Isı alan katı eriyebilir mi?','["Hayır","Sadece donar","Evet","Maddenin hâli değişmez"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-isi' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-23','coktan_secmeli','Bakır iyi bir elektrik iletkeni midir?','["Evet","Hayır","Yalıtkandır","Elektrikle ilgisiz"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-iletken' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-24','coktan_secmeli','Direnç akımın geçişine karşı koyma özelliği midir?','["Hayır","Enerji kaynağıdır","Evet","Sadece ışık üretir"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-iletken' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-25','coktan_secmeli','Direnç arttığında aynı koşullarda akım azalabilir mi?','["Evet","Hayır","Her zaman artar","Direnç etkilemez"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,25,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-devre' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-26','coktan_secmeli','Devre elemanlarının bağlantısı ampul parlaklığını etkileyebilir mi?','["Hayır","Sadece ampul rengi","Evet","Bağlantı önemli değil"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,26,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-devre' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-27','coktan_secmeli','Üreticiler ekosistemde besin üretiminin temelini oluşturur mu?','["Evet","Hayır","Sadece tüketiciler","Üretici yoktur"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,27,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-ekosistem' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-28','coktan_secmeli','Madde döngüleri ekosistemin devamına katkı sağlar mı?','["Hayır","Madde döngüsü yoktur","Evet","Sadece enerji döner"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,28,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-ekosistem' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-29','coktan_secmeli','Yenilenebilir kaynak kullanımı sürdürülebilirliği destekleyebilir mi?','["Evet","Hayır","Her zaman kaynak tüketir","Sürdürülebilirlikle ilgisiz"]',0,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,29,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-surdur-konu' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g6f-1-30','coktan_secmeli','Enerji ve su tasarrufu doğal kaynakları korumaya yardım eder mi?','["Hayır","Sadece bütçeyi etkiler","Evet","Kaynaklar sınırsız"]',2,'Fen bilimleri bilgisi kanıt ve modelle değerlendirilir.',1,30,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=6 AND k.konu_kodu='fen6-surdur-konu' AND (d.kod='fen' OR d.ad='Fen Bilimleri') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;
