SET NAMES utf8mb4;
INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-iletisim','Etkili İletişim ve Toplumsal Katılım','Etkili İletişim ve Toplumsal Katılım','Etkili İletişim ve Toplumsal Katılım konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-birlikte' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-esitlik','Fırsat Eşitliği ve Millî Dayanışma','Fırsat Eşitliği ve Millî Dayanışma','Fırsat Eşitliği ve Millî Dayanışma konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-birlikte' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-nufus','Nüfus, Göç ve Yerleşme','Nüfus, Göç ve Yerleşme','Nüfus, Göç ve Yerleşme konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-dunya' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-cevre','Çevre Sorunları ve Coğrafi Etkileşim','Çevre Sorunları ve Coğrafi Etkileşim','Çevre Sorunları ve Coğrafi Etkileşim konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-dunya' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-osmanli','Osmanlı''dan Ortak Mirasa','Osmanlı''dan Ortak Mirasa','Osmanlı''dan Ortak Mirasa konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-miras' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-kultur','Kültürel Etkileşim ve Mirasın Korunması','Kültürel Etkileşim ve Mirasın Korunması','Kültürel Etkileşim ve Mirasın Korunması konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-miras' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-demokrasi','Demokratikleşme ve Katılım','Demokratikleşme ve Katılım','Demokratikleşme ve Katılım konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-demokrasi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-hak','Hak, Özgürlük ve Hukuk','Hak, Özgürlük ve Hukuk','Hak, Özgürlük ve Hukuk konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-demokrasi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-ekonomi','Üretim, Emek ve Ekonomik Sistem','Üretim, Emek ve Ekonomik Sistem','Üretim, Emek ve Ekonomik Sistem konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-ekonomi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-finans','Finansal Okuryazarlık ve Bütçe','Finansal Okuryazarlık ve Bütçe','Finansal Okuryazarlık ve Bütçe konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-ekonomi' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-bilim','Bilimsel Gelişmeler ve Toplum','Bilimsel Gelişmeler ve Toplum','Bilimsel Gelişmeler ve Toplum konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-teknoloji' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'s7-dijital','Dijital Toplum, Medya ve Etik','Dijital Toplum, Medya ve Etik','Dijital Toplum, Medya ve Etik konusunu örnek, metin ve uygulamalarla ilişkilendirir.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='sos7-teknoloji' WHERE d.kod='sosyal' OR d.ad='Sosyal Bilgiler' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-1','coktan_secmeli','Etkili iletişim toplumsal katılımı destekler mi?','["Evet","Hayır","Sadece bireysel","İletişim gerekmez"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-2','coktan_secmeli','Aktif dinleme çatışma çözümüne katkı sağlar mı?','["Hayır","Söz kesmek gerekir","Evet","Dinleme zararlıdır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-iletisim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-3','coktan_secmeli','Fırsat eşitliği herkesin aynı ihtiyaca sahip olduğu anlamına mı gelir?','["Hayır","Evet","Her zaman","Eşitlik yoktur"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-4','coktan_secmeli','Millî meselelerde dayanışma toplumsal birlikle ilişkili midir?','["Hayır","Sadece bireysel","Evet","Birlik önemsiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-esitlik' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-5','coktan_secmeli','Göç nüfus dağılışını etkileyebilir mi?','["Evet","Hayır","Sadece iklim","Nüfus sabittir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-6','coktan_secmeli','Kentleşme ekonomik ve sosyal nedenlerle artabilir mi?','["Hayır","Sadece hava durumu","Evet","Kentleşme değişmez"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-nufus' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-7','coktan_secmeli','İnsan faaliyetleri çevre sorunlarını artırabilir mi?','["Evet","Hayır","Sadece doğal olaylar","İnsan etkisi yok"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-8','coktan_secmeli','Sürdürülebilir şehir planlaması çevresel etkiyi azaltabilir mi?','["Hayır","Sadece maliyet artırır","Evet","Çevreyle ilgisiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-cevre' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-9','coktan_secmeli','Tarihî belgeler geçmiş toplumlar hakkında kanıt sunar mı?','["Evet","Hayır","Sadece süs","Tarih anlatmaz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-10','coktan_secmeli','Osmanlı mirası mimari ve kültürel ögelerde görülebilir mi?','["Hayır","Sadece siyasette","Evet","Miras yoktur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-osmanli' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-11','coktan_secmeli','Kültürel etkileşim ticaret ve göçle artabilir mi?','["Evet","Hayır","Kültür değişmez","Sadece savaşla"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-12','coktan_secmeli','Mirası korumak gelecek kuşaklar için önemli midir?','["Hayır","Sadece turistler","Evet","Koruma gereksiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-kultur' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-13','coktan_secmeli','Seçimler demokratik katılım yollarından biri midir?','["Evet","Hayır","Sadece oyun","Sadece ekonomi"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-14','coktan_secmeli','Sivil toplum katılımı destekleyebilir mi?','["Hayır","Sadece devlet","Evet","Katılım yoktur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-demokrasi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-15','coktan_secmeli','Hukukun üstünlüğü herkesin hukuk kurallarına bağlı olmasını ifade eder mi?','["Evet","Hayır","Sadece vatandaşlar","Sadece yöneticiler"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-16','coktan_secmeli','Özgürlükler başkalarının haklarıyla dengelenmeli midir?','["Hayır","Sınırsızdır","Evet","Haklarla ilgisiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-hak' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-17','coktan_secmeli','Emek üretim faktörlerinden biri midir?','["Evet","Hayır","Sadece tüketim","Sadece reklam"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-18','coktan_secmeli','Girişimcilik ekonomik faaliyeti etkileyebilir mi?','["Hayır","Sadece kamu","Evet","Ekonomiyle ilgisiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-ekonomi' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-19','coktan_secmeli','Bütçe gelir-gider planı mıdır?','["Evet","Hayır","Harita","Sadece vergi"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-20','coktan_secmeli','Tasarruf finansal hedefe ulaşmayı destekleyebilir mi?','["Hayır","Sadece harcama","Evet","Tasarruf zararlıdır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-finans' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-21','coktan_secmeli','Bilimsel gelişmeler toplumsal yaşamı değiştirebilir mi?','["Evet","Hayır","Sadece laboratuvar","Toplumu etkilemez"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-22','coktan_secmeli','Bilim insanlarının katkıları farklı toplumlarda ortaya çıkabilir mi?','["Hayır","Tek toplum","Evet","Bilim kültürden bağımsızdır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-bilim' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-23','coktan_secmeli','Dijital medya okuryazarlığı yanlış bilgiyi ayırt etmeye yardım eder mi?','["Evet","Hayır","Her içerik doğrudur","Paylaşım sayısı yeter"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7s-1-24','coktan_secmeli','Çevrim içi etik gerçek hayattaki saygı kurallarıyla ilişkili midir?','["Hayır","İnternette kural yok","Evet","Sadece okulda"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='s7-dijital' AND (d.kod='sosyal' OR d.ad='Sosyal Bilgiler') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;
