SET NAMES utf8mb4;
INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-tasarim','Tasarım Odaklı Düşünme','Tasarım Odaklı Düşünme','Tasarım Odaklı Düşünme konusunu iletişim ve günlük yaşam bağlamında uygular.','',10,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-surec' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-arastirma','Araştırma ve Ölçüt Belirleme','Araştırma ve Ölçüt Belirleme','Araştırma ve Ölçüt Belirleme konusunu iletişim ve günlük yaşam bağlamında uygular.','',20,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-surec' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-problem','İhtiyaç ve Problem Tanımlama','İhtiyaç ve Problem Tanımlama','İhtiyaç ve Problem Tanımlama konusunu iletişim ve günlük yaşam bağlamında uygular.','',30,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-ihtiyac' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-kullanici','Kullanıcı ve Ergonomi','Kullanıcı ve Ergonomi','Kullanıcı ve Ergonomi konusunu iletişim ve günlük yaşam bağlamında uygular.','',40,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-ihtiyac' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-inovasyon','İnovasyon ve Değer Üretme','İnovasyon ve Değer Üretme','İnovasyon ve Değer Üretme konusunu iletişim ve günlük yaşam bağlamında uygular.','',50,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-inovasyon' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-girisim','Girişimcilik ve Sunum','Girişimcilik ve Sunum','Girişimcilik ve Sunum konusunu iletişim ve günlük yaşam bağlamında uygular.','',60,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-inovasyon' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-yapi-konu','Yapı, Dayanıklılık ve Malzeme','Yapı, Dayanıklılık ve Malzeme','Yapı, Dayanıklılık ve Malzeme konusunu iletişim ve günlük yaşam bağlamında uygular.','',70,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-yapi' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-model','Model ve Maket','Model ve Maket','Model ve Maket konusunu iletişim ve günlük yaşam bağlamında uygular.','',80,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-yapi' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-enerji-konu','Enerji Verimliliği','Enerji Verimliliği','Enerji Verimliliği konusunu iletişim ve günlük yaşam bağlamında uygular.','',90,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-enerji' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-surdur','Sürdürülebilir Tasarım','Sürdürülebilir Tasarım','Sürdürülebilir Tasarım konusunu iletişim ve günlük yaşam bağlamında uygular.','',100,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-enerji' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-prototip','Prototipleme','Prototipleme','Prototipleme konusunu iletişim ve günlük yaşam bağlamında uygular.','',110,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-urun' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_konulari (ders_id,bolum_id,kademe_kodu,sinif_seviyesi,konu_kodu,ad,aciklama,anlatim,ornek_metni,sira,aktif) SELECT d.id,b.id,'temel_egitim',7,'tt7-test','Test, Geri Bildirim ve İyileştirme','Test, Geri Bildirim ve İyileştirme','Test, Geri Bildirim ve İyileştirme konusunu iletişim ve günlük yaşam bağlamında uygular.','',120,1 FROM dersler d INNER JOIN ders_bolumleri b ON b.ders_id=d.id AND b.kademe_kodu='temel_egitim' AND b.sinif_seviyesi=7 AND b.kod='tt7-urun' WHERE d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım' ON DUPLICATE KEY UPDATE bolum_id=VALUES(bolum_id),ad=VALUES(ad),anlatim=VALUES(anlatim),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-1','coktan_secmeli','Tasarım süreci problemi anlamakla başlayabilir mi?','["Evet","Hayır","Sadece ürün boyamakla","Sadece satışla"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,1,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-tasarim' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-2','coktan_secmeli','Birden fazla çözüm fikri üretmek tasarım sürecinin parçası mıdır?','["Hayır","Tek fikir zorunlu","Evet","Fikir üretmek gerekmez"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,2,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-tasarim' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-3','coktan_secmeli','Tasarım ölçütleri çözümü değerlendirmeye yardım eder mi?','["Evet","Hayır","Sadece renk seçer","Ölçüt gereksiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,3,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-arastirma' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-4','coktan_secmeli','Kaynak araştırması mevcut çözümleri tanımaya yardım eder mi?','["Hayır","Sadece kopya için","Evet","Araştırma yasaktır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,4,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-arastirma' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-5','coktan_secmeli','İyi tanımlanmış problem çözüm geliştirmeyi kolaylaştırır mı?','["Evet","Hayır","Problem tanımı gereksiz","Sadece sonuç önemlidir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,5,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-problem' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-6','coktan_secmeli','İhtiyaç ile istek her zaman aynı mıdır?','["Evet","Her zaman","Hayır","Sadece okulda"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,6,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-problem' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-7','coktan_secmeli','Ergonomi kullanıcı rahatlığı ve güvenliğiyle ilişkili midir?','["Evet","Hayır","Sadece renk","Sadece fiyat"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,7,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-kullanici' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-8','coktan_secmeli','Kullanıcı geri bildirimi tasarımı geliştirebilir mi?','["Hayır","Sadece tasarımcı bilir","Evet","Geri bildirim zararlıdır"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,8,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-kullanici' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-9','coktan_secmeli','İnovasyon mevcut ürünü anlamlı biçimde geliştirmeyi de içerebilir mi?','["Evet","Hayır","Sadece tamamen yeni icat","İnovasyon yalnız reklamdır"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,9,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-inovasyon' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-10','coktan_secmeli','Yenilik kullanıcı için değer üretmeli midir?','["Hayır","Değer önemli değildir","Evet","Sadece görünüş yeter"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,10,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-inovasyon' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-11','coktan_secmeli','Bir ürün fikrini sunarken hedef kitle önemli midir?','["Evet","Hayır","Sadece fiyat","Kitle önemsiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,11,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-girisim' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-12','coktan_secmeli','Maliyet hesabı girişim planında önemli olabilir mi?','["Hayır","Sadece logo","Evet","Maliyet gereksiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,12,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-girisim' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-13','coktan_secmeli','Üçgen biçimler bazı yapılarda dayanıklılığı artırabilir mi?','["Evet","Hayır","Sadece daire","Geometri etkisizdir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,13,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-yapi-konu' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-14','coktan_secmeli','Malzeme seçimi dayanıklılığı etkiler mi?','["Hayır","Sadece renk","Evet","Malzeme önemsiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,14,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-yapi-konu' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-15','coktan_secmeli','Maket gerçek ürünün ölçekli temsili olabilir mi?','["Evet","Hayır","Sadece resim","Model gerçek ürünün aynısı olmak zorunda"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,15,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-model' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-16','coktan_secmeli','Model testleri tasarım hatalarını fark etmeye yardım eder mi?','["Hayır","Sadece süs","Evet","Test gereksiz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,16,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-model' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-17','coktan_secmeli','Enerji verimli ürün daha az kaynak tüketebilir mi?','["Evet","Hayır","Her zaman daha çok","Enerjiyle ilgisiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,17,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-enerji-konu' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-18','coktan_secmeli','Gereksiz enerji kaybını azaltmak tasarım hedefi olabilir mi?','["Hayır","Sadece fiyat hedefi","Evet","Kayıp önemli değil"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,18,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-enerji-konu' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-19','coktan_secmeli','Geri dönüştürülebilir malzeme sürdürülebilir tasarımı destekleyebilir mi?','["Evet","Hayır","Sadece plastik","Malzeme etkisiz"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,19,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-surdur' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-20','coktan_secmeli','Ürünün ömrünü uzatmak atığı azaltabilir mi?','["Hayır","Atığı artırır","Evet","Ömür önemli değil"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,20,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-surdur' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-21','coktan_secmeli','Prototip nihai üründen önce denenebilir mi?','["Evet","Hayır","Prototip son üründür","Test edilmez"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,21,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-prototip' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-22','coktan_secmeli','Hızlı prototip fikirleri karşılaştırmaya yardım eder mi?','["Hayır","Sadece satış","Evet","Karşılaştırma yapılamaz"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,22,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-prototip' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-23','coktan_secmeli','Test sonucu tasarım değiştirilebilir mi?','["Evet","Hayır","İlk tasarım değişmez","Test sadece not içindir"]',0,'Konu bilgisi bağlama göre değerlendirilir.',1,23,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-test' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;

INSERT INTO ders_sorulari (konu_id,soru_kodu,soru_turu,soru,secenekler_json,dogru_cevap_indeksi,aciklama,zorluk,sira,aktif) SELECT k.id,'g7tt-1-24','coktan_secmeli','Geri bildirim iyileştirme döngüsünün parçası mıdır?','["Hayır","Sadece eleştiri","Evet","İyileştirme yoktur"]',2,'Konu bilgisi bağlama göre değerlendirilir.',1,24,1 FROM ders_konulari k INNER JOIN dersler d ON d.id=k.ders_id WHERE k.kademe_kodu='temel_egitim' AND k.sinif_seviyesi=7 AND k.konu_kodu='tt7-test' AND (d.kod='teknoloji_tasarim' OR d.ad='Teknoloji ve Tasarım') ON DUPLICATE KEY UPDATE soru=VALUES(soru),secenekler_json=VALUES(secenekler_json),dogru_cevap_indeksi=VALUES(dogru_cevap_indeksi),aciklama=VALUES(aciklama),zorluk=VALUES(zorluk),sira=VALUES(sira),aktif=1;
